package com.android.systemui.keyguard.ui.viewmodel;

import android.content.Context;
import com.android.systemui.common.ui.domain.interactor.ConfigurationInteractor;
import com.android.systemui.keyguard.domain.interactor.KeyguardTransitionInteractor;
import kotlinx.coroutines.flow.FlowKt;
import kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest;

/* loaded from: classes2.dex */
public final class DeviceEntryBackgroundViewModel {
    public final ChannelFlowTransformLatest alpha;
    public final ChannelFlowTransformLatest color;
    public final Context context;

    public DeviceEntryBackgroundViewModel(Context context, DeviceEntryIconViewModel deviceEntryIconViewModel, KeyguardTransitionInteractor keyguardTransitionInteractor, ConfigurationInteractor configurationInteractor, AlternateBouncerToAodTransitionViewModel alternateBouncerToAodTransitionViewModel, AlternateBouncerToDozingTransitionViewModel alternateBouncerToDozingTransitionViewModel, AodToLockscreenTransitionViewModel aodToLockscreenTransitionViewModel, DozingToLockscreenTransitionViewModel dozingToLockscreenTransitionViewModel, DreamingToAodTransitionViewModel dreamingToAodTransitionViewModel, DreamingToLockscreenTransitionViewModel dreamingToLockscreenTransitionViewModel, GoneToAodTransitionViewModel goneToAodTransitionViewModel, GoneToDozingTransitionViewModel goneToDozingTransitionViewModel, GoneToLockscreenTransitionViewModel goneToLockscreenTransitionViewModel, LockscreenToAodTransitionViewModel lockscreenToAodTransitionViewModel, OccludedToAodTransitionViewModel occludedToAodTransitionViewModel, OccludedToDozingTransitionViewModel occludedToDozingTransitionViewModel, OccludedToLockscreenTransitionViewModel occludedToLockscreenTransitionViewModel, OffToLockscreenTransitionViewModel offToLockscreenTransitionViewModel, PrimaryBouncerToAodTransitionViewModel primaryBouncerToAodTransitionViewModel, PrimaryBouncerToDozingTransitionViewModel primaryBouncerToDozingTransitionViewModel, PrimaryBouncerToLockscreenTransitionViewModel primaryBouncerToLockscreenTransitionViewModel, LockscreenToDozingTransitionViewModel lockscreenToDozingTransitionViewModel, GlanceableHubToAodTransitionViewModel glanceableHubToAodTransitionViewModel, GlanceableHubToLockscreenTransitionViewModel glanceableHubToLockscreenTransitionViewModel) {
        this.context = context;
        this.color = FlowKt.transformLatest(deviceEntryIconViewModel.useBackgroundProtection, new DeviceEntryBackgroundViewModel$special$$inlined$flatMapLatest$1(null, configurationInteractor, this));
        this.alpha = FlowKt.transformLatest(deviceEntryIconViewModel.useBackgroundProtection, new DeviceEntryBackgroundViewModel$special$$inlined$flatMapLatest$2(null, alternateBouncerToAodTransitionViewModel, alternateBouncerToDozingTransitionViewModel, aodToLockscreenTransitionViewModel, dozingToLockscreenTransitionViewModel, dreamingToAodTransitionViewModel, dreamingToLockscreenTransitionViewModel, goneToAodTransitionViewModel, goneToDozingTransitionViewModel, goneToLockscreenTransitionViewModel, lockscreenToAodTransitionViewModel, occludedToAodTransitionViewModel, occludedToDozingTransitionViewModel, occludedToLockscreenTransitionViewModel, offToLockscreenTransitionViewModel, primaryBouncerToAodTransitionViewModel, primaryBouncerToDozingTransitionViewModel, primaryBouncerToLockscreenTransitionViewModel, lockscreenToDozingTransitionViewModel, glanceableHubToAodTransitionViewModel, glanceableHubToLockscreenTransitionViewModel, keyguardTransitionInteractor));
    }
}
