package com.android.systemui.flags;

import com.android.systemui.R;

/* compiled from: qb/89523975 427a50d40ec74a85ca352b86f77450b1c52ece5389e11158752b0d641a3a5098 */
/* loaded from: classes2.dex */
public final class Flags {
    public static final ReleasedFlag ALWAYS_SHOW_HOME_CONTROLS_ON_DREAMS;
    public static final SysPropBooleanFlag BUILDER_EXTRAS_OVERRIDE;
    public static final ResourceBooleanFlag CHARGING_RIPPLE;
    public static final ResourceBooleanFlag COMMUNAL_SERVICE_ENABLED;
    public static final UnreleasedFlag ENABLE_DARK_VIGNETTE_WHEN_FOLDING;
    public static final UnreleasedFlag ENABLE_NOTIFICATIONS_SIMULATE_SLOW_MEASURE;
    public static final UnreleasedFlag ENABLE_UNFOLD_STATUS_BAR_ANIMATIONS;
    public static final ReleasedFlag ENABLE_USI_BATTERY_NOTIFICATIONS;
    public static final ReleasedFlag ENABLE_WALLET_CONTEXTUAL_LOYALTY_CARDS;
    public static final ReleasedFlag FALSING_OFF_FOR_UNFOLDED;
    public static final ResourceBooleanFlag FULL_SCREEN_USER_SWITCHER;
    public static final ReleasedFlag INCOMPATIBLE_CHARGING_BATTERY_ICON;
    public static final Flags INSTANCE = new Flags();
    public static final ReleasedFlag INSTANT_TETHER;
    public static final ReleasedFlag KEYBOARD_BACKLIGHT_INDICATOR;
    public static final ResourceBooleanFlag LOCKSCREEN_CUSTOM_CLOCKS;
    public static final UnreleasedFlag LOCKSCREEN_ENABLE_LANDSCAPE;
    public static final ReleasedFlag LOCK_SCREEN_LONG_PRESS_ENABLED;
    public static final ReleasedFlag MEDIA_RESUME_PROGRESS;
    public static final ReleasedFlag MEDIA_TAP_TO_TRANSFER;
    public static final ResourceBooleanFlag MONET;
    public static final ReleasedFlag MONOCHROMATIC_THEME;
    public static final ReleasedFlag NEW_NETWORK_SLICE_UI;
    public static final ReleasedFlag NEW_UNLOCK_SWIPE_ANIMATION;
    public static final ReleasedFlag NOTE_TASKS;
    public static final ResourceBooleanFlag NOTIFICATION_DRAG_TO_CONTENTS;
    public static final UnreleasedFlag NULL_FLAG;
    public static final ReleasedFlag POWER_MENU_LITE;
    public static final ReleasedFlag QS_SECONDARY_DATA_SUB_INFO;
    public static final ResourceBooleanFlag QS_USER_DETAIL_SHORTCUT;
    public static final ReleasedFlag ROAMING_INDICATOR_VIA_DISPLAY_INFO;
    public static final ReleasedFlag SCREENSHOT_APP_CLIPS;
    public static final ReleasedFlag SHARE_WIFI_QS_BUTTON;
    public static final ReleasedFlag SHORTCUT_LIST_SEARCH_LAYOUT;
    public static final ReleasedFlag SIGNAL_CALLBACK_DEPRECATION;
    public static final ReleasedFlag STEP_CLOCK_ANIMATION;
    public static final ReleasedFlag TRACK_STYLUS_EVER_USED;
    public static final ReleasedFlag TRANSIT_CLOCK;
    public static final ReleasedFlag WALLPAPER_FULLSCREEN_PREVIEW;
    public static final ReleasedFlag WALLPAPER_PICKER_PAGE_TRANSITIONS;
    public static final ReleasedFlag WALLPAPER_PICKER_PREVIEW_ANIMATION;
    public static final ReleasedFlag WALLPAPER_PICKER_UI_FOR_AIWP;
    public static final ReleasedFlag WIFI_SECONDARY_NETWORKS;
    public static final SysPropBooleanFlag WM_ALWAYS_ENFORCE_PREDICTIVE_BACK;
    public static final SysPropBooleanFlag WM_BUBBLE_BAR;
    public static final ReleasedFlag WM_ENABLE_PARTIAL_SCREEN_SHARING;
    public static final ReleasedFlag WM_ENABLE_PARTIAL_SCREEN_SHARING_ENTERPRISE_POLICIES;
    public static final SysPropBooleanFlag WM_ENABLE_PREDICTIVE_BACK_ANIM;
    public static final SysPropBooleanFlag WM_ENABLE_SHELL_TRANSITIONS;
    public static final ReleasedFlag ZJ_285570694_LOCKSCREEN_TRANSITION_FROM_AOD;

    static {
        FlagsFactory flagsFactory = FlagsFactory.INSTANCE;
        NULL_FLAG = FlagsFactory.unreleasedFlag$default(6, flagsFactory, "null_flag");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "notification_pipeline_developer_logging");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "nssl_debug_lines");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "nssl_debug_remove_animation");
        NOTIFICATION_DRAG_TO_CONTENTS = FlagsFactory.resourceBooleanFlag$default(R.bool.config_notificationToContents, flagsFactory, "notification_drag_to_contents");
        BUILDER_EXTRAS_OVERRIDE = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, "persist.sysui.notification.builder_extras_override", true);
        NEW_UNLOCK_SWIPE_ANIMATION = FlagsFactory.releasedFlag("new_unlock_swipe_animation", "systemui");
        CHARGING_RIPPLE = FlagsFactory.resourceBooleanFlag$default(R.bool.flag_charging_ripple, flagsFactory, "charging_ripple");
        LOCKSCREEN_CUSTOM_CLOCKS = FlagsFactory.resourceBooleanFlag$default(R.bool.config_enableLockScreenCustomClocks, flagsFactory, "lockscreen_custom_clocks");
        STEP_CLOCK_ANIMATION = FlagsFactory.releasedFlag("step_clock_animation", "systemui");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "dozing_migration_1");
        FlagsFactory.unreleasedFlag$default(2, flagsFactory, "refactor_getcurrentuser");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "biometrics_animation_revamp");
        FlagsFactory.releasedFlag("auto_pin_confirmation", "auto_pin_confirmation");
        FALSING_OFF_FOR_UNFOLDED = FlagsFactory.releasedFlag("falsing_off_for_unfolded", "systemui");
        ENABLE_WALLET_CONTEXTUAL_LOYALTY_CARDS = FlagsFactory.releasedFlag("enable_wallet_contextual_loyalty_cards", "systemui");
        WALLPAPER_FULLSCREEN_PREVIEW = FlagsFactory.releasedFlag("wallpaper_fullscreen_preview", "systemui");
        LOCK_SCREEN_LONG_PRESS_ENABLED = FlagsFactory.releasedFlag("lock_screen_long_press_enabled", "systemui");
        FlagsFactory.releasedFlag("lazy_inflate_keyguard", "systemui");
        WALLPAPER_PICKER_UI_FOR_AIWP = FlagsFactory.releasedFlag("wallpaper_picker_ui_for_aiwp", "systemui");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "lock_screen_long_press_directly_opens_wallpaper_picker");
        WALLPAPER_PICKER_PAGE_TRANSITIONS = FlagsFactory.releasedFlag("wallpaper_picker_page_transitions", "systemui");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "wallpaper_picker_grid_apply_button");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "keyguard_talkback_fix");
        TRANSIT_CLOCK = FlagsFactory.releasedFlag("lockscreen_custom_transit_clock", "systemui");
        WALLPAPER_PICKER_PREVIEW_ANIMATION = FlagsFactory.releasedFlag("wallpaper_picker_preview_animation", "systemui");
        POWER_MENU_LITE = FlagsFactory.releasedFlag("power_menu_lite", "systemui");
        FlagsFactory.releasedFlag("smartspace_shared_element_transition_enabled", "systemui");
        FlagsFactory.releasedFlag("hide_smartspace_on_dream_overlay", "systemui");
        FlagsFactory.releasedFlag("show_weather_complication_on_dream_overlay", "systemui");
        FlagsFactory.resourceBooleanFlag$default(R.bool.flag_conversations, flagsFactory, "people_tile");
        QS_USER_DETAIL_SHORTCUT = FlagsFactory.resourceBooleanFlag$default(R.bool.flag_lockscreen_qs_user_detail_shortcut, flagsFactory, "qs_user_detail_shortcut");
        FULL_SCREEN_USER_SWITCHER = FlagsFactory.resourceBooleanFlag$default(R.bool.config_enableFullscreenUserSwitcher, flagsFactory, "full_screen_user_switcher");
        QS_SECONDARY_DATA_SUB_INFO = FlagsFactory.releasedFlag("qs_secondary_data_sub_info", "systemui");
        FlagsFactory.unreleasedFlag$default(2, flagsFactory, "enable_new_qs_edit_mode");
        SIGNAL_CALLBACK_DEPRECATION = FlagsFactory.releasedFlag("signal_callback_deprecation", "systemui");
        NEW_NETWORK_SLICE_UI = FlagsFactory.releasedFlag("new_network_slice_ui", "systemui");
        ROAMING_INDICATOR_VIA_DISPLAY_INFO = FlagsFactory.releasedFlag("roaming_indicator_via_display_info", "systemui");
        FlagsFactory.releasedFlag("filter_provisioning_network_subscriptions", "systemui");
        INCOMPATIBLE_CHARGING_BATTERY_ICON = FlagsFactory.releasedFlag("incompatible_charging_battery_icon", "systemui");
        INSTANT_TETHER = FlagsFactory.releasedFlag("instant_tether", "systemui");
        WIFI_SECONDARY_NETWORKS = FlagsFactory.releasedFlag("wifi_secondary_networks", "systemui");
        FlagsFactory.unreleasedFlag$default(2, flagsFactory, "new_shade_carrier_group_mobile_icons");
        MONET = FlagsFactory.resourceBooleanFlag$default(R.bool.flag_monet, flagsFactory, "monet");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "region_sampling");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "screen_contents_translation");
        MONOCHROMATIC_THEME = FlagsFactory.releasedFlag("monochromatic", "systemui");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "color_fidelity");
        MEDIA_TAP_TO_TRANSFER = FlagsFactory.releasedFlag("media_tap_to_transfer", "systemui");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "media_session_actions");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "dream_media_complication");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "dream_media_tap_to_open");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "media_retain_sessions");
        MEDIA_RESUME_PROGRESS = FlagsFactory.releasedFlag("media_resume_progress", "systemui");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "media_retain_recommendations");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "media_remote_resume");
        FlagsFactory.releasedFlag("simulate_dock_through_charging", "systemui");
        ALWAYS_SHOW_HOME_CONTROLS_ON_DREAMS = FlagsFactory.releasedFlag("always_show_home_controls_on_dreams", "systemui");
        WM_ENABLE_SHELL_TRANSITIONS = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, "persist.wm.debug.shell_transit", true);
        WM_ENABLE_PARTIAL_SCREEN_SHARING = FlagsFactory.releasedFlag("enable_record_task_content", "window_manager");
        WM_BUBBLE_BAR = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, "persist.wm.debug.bubble_bar", false);
        WM_ENABLE_PARTIAL_SCREEN_SHARING_ENTERPRISE_POLICIES = FlagsFactory.releasedFlag("enable_screen_record_enterprise_policies", "window_manager");
        LOCKSCREEN_ENABLE_LANDSCAPE = FlagsFactory.unreleasedFlag$default(2, flagsFactory, "lockscreen.enable_landscape");
        WM_ENABLE_PREDICTIVE_BACK_ANIM = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, "persist.wm.debug.predictive_back_anim", true);
        WM_ALWAYS_ENFORCE_PREDICTIVE_BACK = FlagsFactory.sysPropBooleanFlag$default(flagsFactory, "persist.wm.debug.predictive_back_always_enforce", false);
        SCREENSHOT_APP_CLIPS = FlagsFactory.releasedFlag("screenshot_app_clips", "systemui");
        FlagsFactory.releasedFlag("quick_tap_in_pcc", "systemui");
        FlagsFactory.unreleasedFlag$default(2, flagsFactory, "quick_tap_flow_framework");
        FlagsFactory.releasedFlag("clipboard_remote_behavior", "systemui");
        FlagsFactory.unreleasedFlag$default(2, flagsFactory, "clipboard_image_timeout");
        FlagsFactory.unreleasedFlag$default(2, flagsFactory, "clipboard_shared_transitions");
        NOTE_TASKS = FlagsFactory.releasedFlag("keycode_flag", "systemui");
        TRACK_STYLUS_EVER_USED = FlagsFactory.releasedFlag("track_stylus_ever_used", "systemui");
        FlagsFactory.releasedFlag("enable_stylus_charging_ui", "systemui");
        ENABLE_USI_BATTERY_NOTIFICATIONS = FlagsFactory.releasedFlag("enable_usi_battery_notifications", "systemui");
        FlagsFactory.releasedFlag("enable_stylus_education", "systemui");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "warn_on_blocking_binder_transactions");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "user_tracker_background_callbacks");
        ENABLE_DARK_VIGNETTE_WHEN_FOLDING = FlagsFactory.unreleasedFlag$default(6, flagsFactory, "enable_dark_vignette_when_folding");
        ENABLE_UNFOLD_STATUS_BAR_ANIMATIONS = FlagsFactory.unreleasedFlag$default(6, flagsFactory, "enable_unfold_status_bar_animations");
        ENABLE_NOTIFICATIONS_SIMULATE_SLOW_MEASURE = FlagsFactory.unreleasedFlag$default(6, flagsFactory, "enable_notifications_simulate_slow_measure");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "exp_flag_release");
        SHORTCUT_LIST_SEARCH_LAYOUT = FlagsFactory.releasedFlag("shortcut_list_search_layout", "systemui");
        KEYBOARD_BACKLIGHT_INDICATOR = FlagsFactory.releasedFlag("keyboard_backlight_indicator", "systemui");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "split_shade_subpixel_optimization");
        FlagsFactory.releasedFlag("use_new_activity_starter", "systemui");
        ZJ_285570694_LOCKSCREEN_TRANSITION_FROM_AOD = FlagsFactory.releasedFlag("zj_285570694_lockscreen_transition_from_aod", "systemui");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "enable_lockscreen_wallpaper_dream");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "bigpicture_notification_lazy_loading");
        FlagsFactory.releasedFlag("enable_new_privacy_dialog", "systemui");
        FlagsFactory.unreleasedFlag$default(6, flagsFactory, "decouple_remote_input_delegate_and_callback_update");
        FlagsFactory.releasedFlag("enable_clock_keyguard_presentation", "systemui");
        SHARE_WIFI_QS_BUTTON = FlagsFactory.releasedFlag("share_wifi_qs_button", "systemui");
        FlagsFactory.releasedFlag("bluetooth_qs_tile_dialog", "systemui");
        COMMUNAL_SERVICE_ENABLED = FlagsFactory.resourceBooleanFlag$default(R.bool.config_communalServiceEnabled, flagsFactory, "communal_service_enabled");
    }

    private Flags() {
    }
}
