package com.android.systemui.plugins.keyguardstatusview;

public interface PluginLockscreenShadeTransitionController {
    void addCallback(PluginLockscreenShadeTransitionControllerCallback pluginLockscreenShadeTransitionControllerCallback);

    void removeCallback(PluginLockscreenShadeTransitionControllerCallback pluginLockscreenShadeTransitionControllerCallback);
}
