package androidx.compose.ui.autofill;

import com.samsung.android.knox.accounts.Account;
import com.samsung.android.knox.accounts.HostAuth;
import com.samsung.android.knox.container.EnterpriseContainerConstants;
import java.util.HashMap;
import kotlin.Pair;
import kotlin.collections.MapsKt__MapsKt;

/* loaded from: classes.dex */
public abstract class AndroidAutofillType_androidKt {
    public static final HashMap androidAutofillTypes = MapsKt__MapsKt.hashMapOf(new Pair(AutofillType.EmailAddress, Account.EMAIL_ADDRESS), new Pair(AutofillType.Username, EnterpriseContainerConstants.EMAIL_USERNAME), new Pair(AutofillType.Password, HostAuth.PASSWORD), new Pair(AutofillType.NewUsername, "newUsername"), new Pair(AutofillType.NewPassword, "newPassword"), new Pair(AutofillType.PostalAddress, "postalAddress"), new Pair(AutofillType.PostalCode, "postalCode"), new Pair(AutofillType.CreditCardNumber, "creditCardNumber"), new Pair(AutofillType.CreditCardSecurityCode, "creditCardSecurityCode"), new Pair(AutofillType.CreditCardExpirationDate, "creditCardExpirationDate"), new Pair(AutofillType.CreditCardExpirationMonth, "creditCardExpirationMonth"), new Pair(AutofillType.CreditCardExpirationYear, "creditCardExpirationYear"), new Pair(AutofillType.CreditCardExpirationDay, "creditCardExpirationDay"), new Pair(AutofillType.AddressCountry, "addressCountry"), new Pair(AutofillType.AddressRegion, "addressRegion"), new Pair(AutofillType.AddressLocality, "addressLocality"), new Pair(AutofillType.AddressStreet, "streetAddress"), new Pair(AutofillType.AddressAuxiliaryDetails, "extendedAddress"), new Pair(AutofillType.PostalCodeExtended, "extendedPostalCode"), new Pair(AutofillType.PersonFullName, "personName"), new Pair(AutofillType.PersonFirstName, "personGivenName"), new Pair(AutofillType.PersonLastName, "personFamilyName"), new Pair(AutofillType.PersonMiddleName, "personMiddleName"), new Pair(AutofillType.PersonMiddleInitial, "personMiddleInitial"), new Pair(AutofillType.PersonNamePrefix, "personNamePrefix"), new Pair(AutofillType.PersonNameSuffix, "personNameSuffix"), new Pair(AutofillType.PhoneNumber, "phoneNumber"), new Pair(AutofillType.PhoneNumberDevice, "phoneNumberDevice"), new Pair(AutofillType.PhoneCountryCode, "phoneCountryCode"), new Pair(AutofillType.PhoneNumberNational, "phoneNational"), new Pair(AutofillType.Gender, "gender"), new Pair(AutofillType.BirthDateFull, "birthDateFull"), new Pair(AutofillType.BirthDateDay, "birthDateDay"), new Pair(AutofillType.BirthDateMonth, "birthDateMonth"), new Pair(AutofillType.BirthDateYear, "birthDateYear"), new Pair(AutofillType.SmsOtpCode, "smsOTPCode"));
}
