package com.android.systemui.keyguard;

import kotlin.jvm.functions.Function0;
import kotlin.jvm.functions.Function1;
import kotlin.jvm.functions.Function3;

/* compiled from: qb/97869455 e70885ee4e20e40425471e4b47759369a50273352e1b7033cea52247075b3cbb */
/* loaded from: classes2.dex */
public final class ViewMediatorProvider {
    public final Function0 adjustStatusBarLocked;
    public final Function0 alarmManager;
    public final Function0 cancelKeyguardExitAnimMsg;
    public final Function0 dismissMsg;
    public final Function0 doKeyguardLaterLocked;
    public final Function1 doKeyguardLocked;
    public final Function0 getDelayedShowingSequence;
    public final Function1 getLockTimeout;
    public final Function0 getStateCallbackCount;
    public final Function0 getSurfaceBehindRemoteAnimationFinishedCallback;
    public final Function0 handleHide;
    public final Function0 handler;
    public final Function0 hasPendingLock;
    public final Function0 hideLocked;
    public final Function0 hideMsg;
    public final Function0 increaseDelayedShowingSeq;
    public final Function1 initAlphaForAnimationTargets;
    public final Function0 isExternallyEnabled;
    public final Function0 isKeyguardDonePending;
    public final Function0 isShowing;
    public final Function0 isWakeAndUnlocking;
    public final Function0 keyguardDOnePendingTimeoutMsg;
    public final Function0 keyguardDoneDrawingMsg;
    public final Function0 keyguardDoneMsg;
    public final Function0 keyguardInteractor;
    public final Function0 keyguardTimeoutMsg;
    public final Function0 lock;
    public final Function0 notifyFinishedGoingToSleepMsg;
    public final Function0 notifyStartedGoingToSleepMsg;
    public final Function0 notifyStartedWakingUoMsg;
    public final Function1 playSound;
    public final Function0 resetMsg;
    public final Function0 resetPendingLock;
    public final Function0 resetPendingReset;
    public final Function0 resetStateLocked;
    public final Function0 resetSurfaceBehindRemoteAnimationFinishedCallback;
    public final Function1 setHiding;
    public final Function0 setOccludedMsg;
    public final Function1 setRemoteAnimationTarget;
    public final Function3 setShowingLocked;
    public final Function1 setUnoccludeFinishedCallback;
    public final Function0 showKeyguardWakeLock;
    public final Function0 showMsg;
    public final Function0 startKeyguardExitAnimMsg;
    public final Function0 systemReadyMsg;
    public final Function0 tryKeyguardDone;
    public final Function1 updatePhoneState;
    public final Function0 userPresentIntent;

    public ViewMediatorProvider(Function0 function0, Function0 function02, Function0 function03, Function0 function04, Function0 function05, Function0 function06, Function0 function07, Function0 function08, Function0 function09, Function0 function010, Function0 function011, Function0 function012, Function0 function013, Function0 function014, Function0 function015, Function0 function016, Function0 function017, Function0 function018, Function0 function019, Function0 function020, Function0 function021, Function0 function022, Function0 function023, Function0 function024, Function0 function025, Function0 function026, Function0 function027, Function0 function028, Function0 function029, Function0 function030, Function0 function031, Function0 function032, Function0 function033, Function0 function034, Function0 function035, Function0 function036, Function0 function037, Function0 function038, Function0 function039, Function3 function3, Function1 function1, Function1 function12, Function0 function040, Function0 function041, Function1 function13, Function0 function042, Function0 function043, Function1 function14, Function1 function15, Function1 function16, Function1 function17, Function1 function18) {
        this.showMsg = function0;
        this.hideMsg = function02;
        this.resetMsg = function03;
        this.notifyFinishedGoingToSleepMsg = function04;
        this.keyguardDoneMsg = function05;
        this.keyguardDoneDrawingMsg = function06;
        this.setOccludedMsg = function07;
        this.keyguardTimeoutMsg = function08;
        this.dismissMsg = function09;
        this.startKeyguardExitAnimMsg = function010;
        this.keyguardDOnePendingTimeoutMsg = function011;
        this.notifyStartedWakingUoMsg = function012;
        this.notifyStartedGoingToSleepMsg = function013;
        this.systemReadyMsg = function014;
        this.cancelKeyguardExitAnimMsg = function015;
        this.lock = function016;
        this.keyguardInteractor = function018;
        this.handler = function019;
        this.alarmManager = function020;
        this.showKeyguardWakeLock = function021;
        this.userPresentIntent = function022;
        this.isWakeAndUnlocking = function023;
        this.hasPendingLock = function024;
        this.isShowing = function025;
        this.isExternallyEnabled = function027;
        this.isKeyguardDonePending = function030;
        this.getDelayedShowingSequence = function031;
        this.getSurfaceBehindRemoteAnimationFinishedCallback = function032;
        this.resetSurfaceBehindRemoteAnimationFinishedCallback = function033;
        this.resetStateLocked = function034;
        this.adjustStatusBarLocked = function035;
        this.doKeyguardLaterLocked = function036;
        this.handleHide = function037;
        this.hideLocked = function038;
        this.tryKeyguardDone = function039;
        this.setShowingLocked = function3;
        this.doKeyguardLocked = function1;
        this.playSound = function12;
        this.resetPendingLock = function040;
        this.resetPendingReset = function041;
        this.setHiding = function13;
        this.increaseDelayedShowingSeq = function042;
        this.getStateCallbackCount = function043;
        this.getLockTimeout = function14;
        this.updatePhoneState = function15;
        this.initAlphaForAnimationTargets = function16;
        this.setRemoteAnimationTarget = function17;
        this.setUnoccludeFinishedCallback = function18;
    }
}
