package com.android.compose.theme.typography;

import androidx.compose.ui.text.font.FontListFontFamily;
import androidx.compose.ui.text.font.FontWeight;
import androidx.compose.ui.unit.TextUnitKt;

/* compiled from: qb/97869455 e70885ee4e20e40425471e4b47759369a50273352e1b7033cea52247075b3cbb */
/* loaded from: classes.dex */
public final class TypeScaleTokens {
    public final FontListFontFamily bodyLargeFont;
    public final long bodyLargeLineHeight = TextUnitKt.getSp(24.0d);
    public final long bodyLargeSize = TextUnitKt.getSp(16);
    public final long bodyLargeTracking = TextUnitKt.getSp(0.0d);
    public final FontWeight bodyLargeWeight;
    public final FontListFontFamily bodyMediumFont;
    public final long bodyMediumLineHeight;
    public final long bodyMediumSize;
    public final long bodyMediumTracking;
    public final FontWeight bodyMediumWeight;
    public final FontListFontFamily bodySmallFont;
    public final long bodySmallLineHeight;
    public final long bodySmallSize;
    public final long bodySmallTracking;
    public final FontWeight bodySmallWeight;
    public final FontListFontFamily displayLargeFont;
    public final long displayLargeLineHeight;
    public final long displayLargeSize;
    public final long displayLargeTracking;
    public final FontWeight displayLargeWeight;
    public final FontListFontFamily displayMediumFont;
    public final long displayMediumLineHeight;
    public final long displayMediumSize;
    public final long displayMediumTracking;
    public final FontWeight displayMediumWeight;
    public final FontListFontFamily displaySmallFont;
    public final long displaySmallLineHeight;
    public final long displaySmallSize;
    public final long displaySmallTracking;
    public final FontWeight displaySmallWeight;
    public final FontListFontFamily headlineLargeFont;
    public final long headlineLargeLineHeight;
    public final long headlineLargeSize;
    public final long headlineLargeTracking;
    public final FontWeight headlineLargeWeight;
    public final FontListFontFamily headlineMediumFont;
    public final long headlineMediumLineHeight;
    public final long headlineMediumSize;
    public final long headlineMediumTracking;
    public final FontWeight headlineMediumWeight;
    public final FontListFontFamily headlineSmallFont;
    public final long headlineSmallLineHeight;
    public final long headlineSmallSize;
    public final long headlineSmallTracking;
    public final FontWeight headlineSmallWeight;
    public final FontListFontFamily labelLargeFont;
    public final long labelLargeLineHeight;
    public final long labelLargeSize;
    public final long labelLargeTracking;
    public final FontWeight labelLargeWeight;
    public final FontListFontFamily labelMediumFont;
    public final long labelMediumLineHeight;
    public final long labelMediumSize;
    public final long labelMediumTracking;
    public final FontWeight labelMediumWeight;
    public final FontListFontFamily labelSmallFont;
    public final long labelSmallLineHeight;
    public final long labelSmallSize;
    public final long labelSmallTracking;
    public final FontWeight labelSmallWeight;
    public final FontListFontFamily titleLargeFont;
    public final long titleLargeLineHeight;
    public final long titleLargeSize;
    public final long titleLargeTracking;
    public final FontWeight titleLargeWeight;
    public final FontListFontFamily titleMediumFont;
    public final long titleMediumLineHeight;
    public final long titleMediumSize;
    public final long titleMediumTracking;
    public final FontWeight titleMediumWeight;
    public final FontListFontFamily titleSmallFont;
    public final long titleSmallLineHeight;
    public final long titleSmallSize;
    public final long titleSmallTracking;
    public final FontWeight titleSmallWeight;

    public TypeScaleTokens(TypefaceTokens typefaceTokens) {
        this.bodyLargeFont = typefaceTokens.plain;
        TypefaceTokens.Companion.getClass();
        FontWeight fontWeight = TypefaceTokens.WeightRegular;
        this.bodyLargeWeight = fontWeight;
        FontListFontFamily fontListFontFamily = typefaceTokens.plain;
        this.bodyMediumFont = fontListFontFamily;
        this.bodyMediumLineHeight = TextUnitKt.getSp(20.0d);
        this.bodyMediumSize = TextUnitKt.getSp(14);
        this.bodyMediumTracking = TextUnitKt.getSp(0.0d);
        this.bodyMediumWeight = fontWeight;
        this.bodySmallFont = fontListFontFamily;
        this.bodySmallLineHeight = TextUnitKt.getSp(16.0d);
        this.bodySmallSize = TextUnitKt.getSp(12);
        this.bodySmallTracking = TextUnitKt.getSp(0.1d);
        this.bodySmallWeight = fontWeight;
        FontListFontFamily fontListFontFamily2 = typefaceTokens.brand;
        this.displayLargeFont = fontListFontFamily2;
        this.displayLargeLineHeight = TextUnitKt.getSp(64.0d);
        this.displayLargeSize = TextUnitKt.getSp(57);
        this.displayLargeTracking = TextUnitKt.getSp(0.0d);
        this.displayLargeWeight = fontWeight;
        this.displayMediumFont = fontListFontFamily2;
        this.displayMediumLineHeight = TextUnitKt.getSp(52.0d);
        this.displayMediumSize = TextUnitKt.getSp(45);
        this.displayMediumTracking = TextUnitKt.getSp(0.0d);
        this.displayMediumWeight = fontWeight;
        this.displaySmallFont = fontListFontFamily2;
        this.displaySmallLineHeight = TextUnitKt.getSp(44.0d);
        this.displaySmallSize = TextUnitKt.getSp(36);
        this.displaySmallTracking = TextUnitKt.getSp(0.0d);
        this.displaySmallWeight = fontWeight;
        this.headlineLargeFont = fontListFontFamily2;
        this.headlineLargeLineHeight = TextUnitKt.getSp(40.0d);
        this.headlineLargeSize = TextUnitKt.getSp(32);
        this.headlineLargeTracking = TextUnitKt.getSp(0.0d);
        this.headlineLargeWeight = fontWeight;
        this.headlineMediumFont = fontListFontFamily2;
        this.headlineMediumLineHeight = TextUnitKt.getSp(36.0d);
        this.headlineMediumSize = TextUnitKt.getSp(28);
        this.headlineMediumTracking = TextUnitKt.getSp(0.0d);
        this.headlineMediumWeight = fontWeight;
        this.headlineSmallFont = fontListFontFamily2;
        this.headlineSmallLineHeight = TextUnitKt.getSp(32.0d);
        this.headlineSmallSize = TextUnitKt.getSp(24);
        this.headlineSmallTracking = TextUnitKt.getSp(0.0d);
        this.headlineSmallWeight = fontWeight;
        this.labelLargeFont = fontListFontFamily;
        this.labelLargeLineHeight = TextUnitKt.getSp(20.0d);
        this.labelLargeSize = TextUnitKt.getSp(14);
        this.labelLargeTracking = TextUnitKt.getSp(0.0d);
        FontWeight fontWeight2 = TypefaceTokens.WeightMedium;
        this.labelLargeWeight = fontWeight2;
        this.labelMediumFont = fontListFontFamily;
        this.labelMediumLineHeight = TextUnitKt.getSp(16.0d);
        this.labelMediumSize = TextUnitKt.getSp(12);
        this.labelMediumTracking = TextUnitKt.getSp(0.1d);
        this.labelMediumWeight = fontWeight2;
        this.labelSmallFont = fontListFontFamily;
        this.labelSmallLineHeight = TextUnitKt.getSp(16.0d);
        this.labelSmallSize = TextUnitKt.getSp(11);
        this.labelSmallTracking = TextUnitKt.getSp(0.1d);
        this.labelSmallWeight = fontWeight2;
        this.titleLargeFont = fontListFontFamily2;
        this.titleLargeLineHeight = TextUnitKt.getSp(28.0d);
        this.titleLargeSize = TextUnitKt.getSp(22);
        this.titleLargeTracking = TextUnitKt.getSp(0.0d);
        this.titleLargeWeight = fontWeight;
        this.titleMediumFont = fontListFontFamily;
        this.titleMediumLineHeight = TextUnitKt.getSp(24.0d);
        this.titleMediumSize = TextUnitKt.getSp(16);
        this.titleMediumTracking = TextUnitKt.getSp(0.0d);
        this.titleMediumWeight = fontWeight2;
        this.titleSmallFont = fontListFontFamily;
        this.titleSmallLineHeight = TextUnitKt.getSp(20.0d);
        this.titleSmallSize = TextUnitKt.getSp(14);
        this.titleSmallTracking = TextUnitKt.getSp(0.0d);
        this.titleSmallWeight = fontWeight2;
    }
}
