package com.android.compose.theme.typography;

import androidx.compose.ui.graphics.Shadow;
import androidx.compose.ui.graphics.drawscope.DrawStyle;
import androidx.compose.ui.text.PlatformTextStyle;
import androidx.compose.ui.text.TextStyle;
import androidx.compose.ui.text.font.FontStyle;
import androidx.compose.ui.text.font.FontSynthesis;
import androidx.compose.ui.text.font.FontWeight;
import androidx.compose.ui.text.intl.LocaleList;
import androidx.compose.ui.text.style.BaselineShift;
import androidx.compose.ui.text.style.LineHeightStyle;
import androidx.compose.ui.text.style.TextDecoration;
import androidx.compose.ui.text.style.TextGeometricTransform;
import androidx.compose.ui.text.style.TextIndent;
import androidx.compose.ui.text.style.TextMotion;
import kotlin.jvm.internal.DefaultConstructorMarker;

/* loaded from: classes.dex */
public final class TypographyTokens {
    public final TextStyle bodyLarge;
    public final TextStyle bodyLargeEmphasized;
    public final TextStyle bodyMedium;
    public final TextStyle bodyMediumEmphasized;
    public final TextStyle bodySmall;
    public final TextStyle bodySmallEmphasized;
    public final TextStyle displayLarge;
    public final TextStyle displayLargeEmphasized;
    public final TextStyle displayMedium;
    public final TextStyle displayMediumEmphasized;
    public final TextStyle displaySmall;
    public final TextStyle displaySmallEmphasized;
    public final TextStyle headlineLarge;
    public final TextStyle headlineLargeEmphasized;
    public final TextStyle headlineMedium;
    public final TextStyle headlineMediumEmphasized;
    public final TextStyle headlineSmall;
    public final TextStyle headlineSmallEmphasized;
    public final TextStyle labelLarge;
    public final TextStyle labelLargeEmphasized;
    public final TextStyle labelMedium;
    public final TextStyle labelMediumEmphasized;
    public final TextStyle labelSmall;
    public final TextStyle labelSmallEmphasized;
    public final TextStyle titleLarge;
    public final TextStyle titleLargeEmphasized;
    public final TextStyle titleMedium;
    public final TextStyle titleMediumEmphasized;
    public final TextStyle titleSmall;
    public final TextStyle titleSmallEmphasized;

    public TypographyTokens(TypeScaleTokens typeScaleTokens, VariableFontTypeScaleEmphasizedTokens variableFontTypeScaleEmphasizedTokens) {
        this.bodyLarge = new TextStyle(0L, typeScaleTokens.bodyLargeSize, typeScaleTokens.bodyLargeWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.bodyLargeFont, (String) null, typeScaleTokens.bodyLargeTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.bodyLargeLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.bodyMedium = new TextStyle(0L, typeScaleTokens.bodyMediumSize, typeScaleTokens.bodyMediumWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.bodyMediumFont, (String) null, typeScaleTokens.bodyMediumTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.bodyMediumLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.bodySmall = new TextStyle(0L, typeScaleTokens.bodySmallSize, typeScaleTokens.bodySmallWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.bodySmallFont, (String) null, typeScaleTokens.bodySmallTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.bodySmallLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.displayLarge = new TextStyle(0L, typeScaleTokens.displayLargeSize, typeScaleTokens.displayLargeWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.displayLargeFont, (String) null, typeScaleTokens.displayLargeTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.displayLargeLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.displayMedium = new TextStyle(0L, typeScaleTokens.displayMediumSize, typeScaleTokens.displayMediumWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.displayMediumFont, (String) null, typeScaleTokens.displayMediumTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.displayMediumLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.displaySmall = new TextStyle(0L, typeScaleTokens.displaySmallSize, typeScaleTokens.displaySmallWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.displaySmallFont, (String) null, typeScaleTokens.displaySmallTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.displaySmallLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.headlineLarge = new TextStyle(0L, typeScaleTokens.headlineLargeSize, typeScaleTokens.headlineLargeWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.headlineLargeFont, (String) null, typeScaleTokens.headlineLargeTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.headlineLargeLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.headlineMedium = new TextStyle(0L, typeScaleTokens.headlineMediumSize, typeScaleTokens.headlineMediumWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.headlineMediumFont, (String) null, typeScaleTokens.headlineMediumTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.headlineMediumLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.headlineSmall = new TextStyle(0L, typeScaleTokens.headlineSmallSize, typeScaleTokens.headlineSmallWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.headlineSmallFont, (String) null, typeScaleTokens.headlineSmallTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.headlineSmallLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.labelLarge = new TextStyle(0L, typeScaleTokens.labelLargeSize, typeScaleTokens.labelLargeWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.labelLargeFont, (String) null, typeScaleTokens.labelLargeTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.labelLargeLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.labelMedium = new TextStyle(0L, typeScaleTokens.labelMediumSize, typeScaleTokens.labelMediumWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.labelMediumFont, (String) null, typeScaleTokens.labelMediumTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.labelMediumLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.labelSmall = new TextStyle(0L, typeScaleTokens.labelSmallSize, typeScaleTokens.labelSmallWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.labelSmallFont, (String) null, typeScaleTokens.labelSmallTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.labelSmallLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.titleLarge = new TextStyle(0L, typeScaleTokens.titleLargeSize, typeScaleTokens.titleLargeWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.titleLargeFont, (String) null, typeScaleTokens.titleLargeTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.titleLargeLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.titleMedium = new TextStyle(0L, typeScaleTokens.titleMediumSize, typeScaleTokens.titleMediumWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.titleMediumFont, (String) null, typeScaleTokens.titleMediumTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.titleMediumLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.titleSmall = new TextStyle(0L, typeScaleTokens.titleSmallSize, typeScaleTokens.titleSmallWeight, (FontStyle) null, (FontSynthesis) null, typeScaleTokens.titleSmallFont, (String) null, typeScaleTokens.titleSmallTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, typeScaleTokens.titleSmallLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645977, (DefaultConstructorMarker) null);
        this.displayLargeEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.displayLargeSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.displayLargeFont, (String) null, variableFontTypeScaleEmphasizedTokens.displayLargeTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.displayLargeLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.displayMediumEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.displayMediumSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.displayMediumFont, (String) null, variableFontTypeScaleEmphasizedTokens.displayMediumTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.displayMediumLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.displaySmallEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.displaySmallSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.displaySmallFont, (String) null, variableFontTypeScaleEmphasizedTokens.displaySmallTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.displaySmallLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.headlineLargeEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.headlineLargeSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.headlineLargeFont, (String) null, variableFontTypeScaleEmphasizedTokens.headlineLargeTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.headlineLargeLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.headlineMediumEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.headlineMediumSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.headlineMediumFont, (String) null, variableFontTypeScaleEmphasizedTokens.headlineMediumTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.headlineMediumLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.headlineSmallEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.headlineSmallSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.headlineSmallFont, (String) null, variableFontTypeScaleEmphasizedTokens.headlineSmallTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.headlineSmallLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.titleLargeEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.titleLargeSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.titleLargeFont, (String) null, variableFontTypeScaleEmphasizedTokens.titleLargeTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.titleLargeLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.titleMediumEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.titleMediumSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.titleMediumFont, (String) null, variableFontTypeScaleEmphasizedTokens.titleMediumTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.titleMediumLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.titleSmallEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.titleSmallSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.titleSmallFont, (String) null, variableFontTypeScaleEmphasizedTokens.titleSmallTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.titleSmallLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.bodyLargeEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.bodyLargeSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.bodyLargeFont, (String) null, variableFontTypeScaleEmphasizedTokens.bodyLargeTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.bodyLargeLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.bodyMediumEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.bodyMediumSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.bodyMediumFont, (String) null, variableFontTypeScaleEmphasizedTokens.bodyMediumTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.bodyMediumLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.bodySmallEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.bodySmallSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.bodySmallFont, (String) null, variableFontTypeScaleEmphasizedTokens.bodySmallTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.bodySmallLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.labelLargeEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.labelLargeSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.labelLargeFont, (String) null, variableFontTypeScaleEmphasizedTokens.labelLargeTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.labelLargeLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.labelMediumEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.labelMediumSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.labelMediumFont, (String) null, variableFontTypeScaleEmphasizedTokens.labelMediumTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.labelMediumLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
        this.labelSmallEmphasized = new TextStyle(0L, variableFontTypeScaleEmphasizedTokens.labelSmallSize, (FontWeight) null, (FontStyle) null, (FontSynthesis) null, variableFontTypeScaleEmphasizedTokens.labelSmallFont, (String) null, variableFontTypeScaleEmphasizedTokens.labelSmallTracking, (BaselineShift) null, (TextGeometricTransform) null, (LocaleList) null, 0L, (TextDecoration) null, (Shadow) null, (DrawStyle) null, 0, 0, variableFontTypeScaleEmphasizedTokens.labelSmallLineHeight, (TextIndent) null, (PlatformTextStyle) null, (LineHeightStyle) null, 0, 0, (TextMotion) null, 16645981, (DefaultConstructorMarker) null);
    }
}
