package com.samsung.android.telephonyui.multisimicons;

import com.android.systemui.R;

/* compiled from: qb/97869455 e70885ee4e20e40425471e4b47759369a50273352e1b7033cea52247075b3cbb */
/* loaded from: classes4.dex */
public class MultiSimIcons {
    public static final int[][] PSIM_ICON_16DP_RES = {new int[]{R.drawable.multi_sim_ic_16_psim_01, R.drawable.multi_sim_ic_16_psim_01_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_02, R.drawable.multi_sim_ic_16_psim_02_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_travel, R.drawable.multi_sim_ic_16_psim_travel_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_business_trip, R.drawable.multi_sim_ic_16_psim_business_trip_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_call, R.drawable.multi_sim_ic_16_psim_call_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_sms, R.drawable.multi_sim_ic_16_psim_mms_sms_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_mms, R.drawable.multi_sim_ic_16_psim_mms_sms_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_internet, R.drawable.multi_sim_ic_16_psim_internet_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_home, R.drawable.multi_sim_ic_16_psim_home_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_office, R.drawable.multi_sim_ic_16_psim_office_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_heart, R.drawable.multi_sim_ic_16_psim_heart_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_num_01, R.drawable.multi_sim_ic_16_psim_num_01_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_num_02, R.drawable.multi_sim_ic_16_psim_num_02_dim}, new int[]{R.drawable.multi_sim_ic_16_psim_num_03, R.drawable.multi_sim_ic_16_psim_num_03_dim}};
    public static final int[][] ESIM_ICON_16DP_RES = {new int[]{R.drawable.multi_sim_ic_16_esim_01, R.drawable.multi_sim_ic_16_esim_01_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_02, R.drawable.multi_sim_ic_16_esim_02_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_travel, R.drawable.multi_sim_ic_16_esim_travel_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_business_trip, R.drawable.multi_sim_ic_16_esim_business_trip_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_call, R.drawable.multi_sim_ic_16_esim_call_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_sms, R.drawable.multi_sim_ic_16_esim_mms_sms_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_mms, R.drawable.multi_sim_ic_16_esim_mms_sms_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_internet, R.drawable.multi_sim_ic_16_esim_internet_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_home, R.drawable.multi_sim_ic_16_esim_home_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_office, R.drawable.multi_sim_ic_16_esim_office_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_heart, R.drawable.multi_sim_ic_16_esim_heart_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_num_01, R.drawable.multi_sim_ic_16_esim_num_01_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_num_02, R.drawable.multi_sim_ic_16_esim_num_02_dim}, new int[]{R.drawable.multi_sim_ic_16_esim_num_03, R.drawable.multi_sim_ic_16_esim_num_03_dim}};
}
