package com.samsung.android.sdk.scs.ai.visual.c2pa;

/* loaded from: classes4.dex */
public enum Exif {
    EXIF_APERTURE_VALUE("exif:ApertureValue"),
    EXIF_BRIGHTNESS_VALUE("exif:BrightnessValue"),
    EXIF_CFAPATTERN("exif:CFAPattern"),
    EXIF_COLORSPACE("exif:ColorSpace"),
    EXIF_COMPRESSED_BITS_PER_PIXEL("exif:CompressedBitsPerPixel"),
    EXIF_CONTRAST("exif:Contrast"),
    EXIF_CUSTOM_RENDERED("exif:CustomRendered"),
    EXIF_DATE_TIME_DIGITIZED("exif:DateTimeDigitized"),
    EXIF_DATE_TIME_ORIGINAL("exif:DateTimeOriginal"),
    EXIF_DEVICE_SETTING_DESCRIPTION("exif:DeviceSettingDescription"),
    EXIF_DIGITAL_ZOOM_RATIO("exif:DigitalZoomRatio"),
    EXIF_EXIF_VERSION("exif:ExifVersion"),
    EXIF_EXPOSURE_BIAS_VALUE("exif:ExposureBiasValue"),
    EXIF_EXPOSURE_INDEX("exif:ExposureIndex"),
    EXIF_EXPOSURE_MODE("exif:ExposureMode"),
    EXIF_EXPOSURE_PROGRAM("exif:ExposureProgram"),
    EXIF_EXPOSURE_TIME("exif:ExposureTime"),
    EXIF_FILE_SOURCE("exif:FileSource"),
    EXIF_FLASH("exif:Flash"),
    EXIF_FLASH_ENERGY("exif:FlashEnergy"),
    EXIF_FLASHPIX_VERSION("exif:FlashpixVersion"),
    EXIF_FNUMBER("exif:FNumber"),
    EXIF_FOCAL_LENGTH("exif:FocalLength"),
    EXIF_FOCAL_LENGTH_IN_35MM_FILM("exif:FocalLengthIn35mmFilm"),
    EXIF_FOCAL_PLANE_RESOLUTION_UNIT("exif:FocalPlaneResolutionUnit"),
    EXIF_FOCAL_PLANE_X_RESOLUTION("exif:FocalPlaneXResolution"),
    EXIF_FOCAL_PLANE_Y_RESOLUTION("exif:FocalPlaneYResolution"),
    EXIF_GAIN_CONTROL("exif:GainControl"),
    EXIF_IMAGE_UNIQUE_ID("exif:ImageUniqueID"),
    EXIF_ISO_SPEED_RATINGS("exif:ISOSpeedRatings"),
    EXIF_LIGHT_SOURCE("exif:LightSource"),
    EXIF_MAX_APERTURE_VALUE("exif:MaxApertureValue"),
    EXIF_METERING_MODE("exif:MeteringMode"),
    EXIF_OECF("exif:OECF"),
    EXIF_PIXEL_X_DIMENSION("exif:PixelXDimension"),
    EXIF_PIXEL_Y_DIMENSION("exif:PixelYDimension"),
    EXIF_RELATED_SOUND_FILE("exif:RelatedSoundFile"),
    EXIF_SATURATION("exif:Saturation"),
    EXIF_SCENE_CAPTURE_TYPE("exif:SceneCaptureType"),
    EXIF_SCENE_TYPE("exif:SceneType"),
    EXIF_SENSING_METHOD("exif:SensingMethod"),
    EXIF_SHARPNESS("exif:Sharpness"),
    EXIF_SHUTTER_SPEED_VALUE("exif:ShutterSpeedValue"),
    EXIF_SPATIAL_FREQUENCY_RESPONSE("exif:SpatialFrequencyResponse"),
    EXIF_SPECTRAL_SENSITIVITY("exif:SpectralSensitivity"),
    EXIF_SUBJECT_AREA("exif:SubjectArea"),
    EXIF_SUBJECT_DISTANCE("exif:SubjectDistance"),
    EXIF_SUBJECT_DISTANCE_RANGE("exif:SubjectDistanceRange"),
    EXIF_SUBJECT_LOCATION("exif:SubjectLocation"),
    EXIF_WHITE_BALANCE("exif:WhiteBalance"),
    EXIF_GPS_ALTITUDE("exif:GPSAltitude"),
    EXIF_GPS_ALTITUDE_REF("exif:GPSAltitudeRef"),
    EXIF_GPS_DEST_BEARING("exif:GPSDestBearing"),
    EXIF_GPS_DEST_BEARING_REF("exif:GPSDestBearingRef"),
    EXIF_GPS_DEST_DISTANCE("exif:GPSDestDistance"),
    EXIF_GPS_DEST_DISTANCE_REF("exif:GPSDestDistanceRef"),
    EXIF_GPS_DEST_LATITUDE("exif:GPSDestLatitude"),
    EXIF_GPS_DEST_LONGITUDE("exif:GPSDestLongitude"),
    EXIF_GPS_DIFFERENTIAL("exif:GPSDifferential"),
    EXIF_GPS_DOP("exif:GPSDOP"),
    EXIF_GPS_HPOSITIONING_ERROR("exif:GPSHPositioningError"),
    EXIF_GPS_IMG_DIRECTION("exif:GPSImgDirection"),
    EXIF_GPS_IMG_DIRECTION_REF("exif:GPSImgDirectionRef"),
    EXIF_GPS_LATITUDE("exif:GPSLatitude"),
    EXIF_GPS_LONGITUDE("exif:GPSLongitude"),
    EXIF_GPS_MAP_DATUM("exif:GPSMapDatum"),
    EXIF_GPS_MEASURE_MODE("exif:GPSMeasureMode"),
    EXIF_GPS_PROCESSING_METHOD("exif:GPSProcessingMethod"),
    EXIF_GPS_SATELLITES("exif:GPSSatellites"),
    EXIF_GPS_SPEED("exif:GPSSpeed"),
    EXIF_GPS_SPEED_REF("exif:GPSSpeedRef"),
    EXIF_GPS_STATUS("exif:GPSStatus"),
    EXIF_GPS_TIMESTAMP("exif:GPSTimeStamp"),
    EXIF_GPS_TRACK("exif:GPSTrack"),
    EXIF_GPS_TRACK_REF("exif:GPSTrackRef"),
    EXIF_GPS_VERSION_ID("exif:GPSVersionID"),
    EXIFEX_BODY_SERIAL_NUMBER("exifEX:BodySerialNumber"),
    EXIFEX_GAMMA("exifEX:Gamma"),
    EXIFEX_INTEROPERABILITY_INDEX("exifEX:InteroperabilityIndex"),
    EXIFEX_ISO_SPEED("exifEX:ISOSpeed"),
    EXIFEX_ISO_SPEED_LATITUDEYYY("exifEX:ISOSpeedLatitudeyyy"),
    EXIFEX_ISO_SPEED_LATITUDEZZZ("exifEX:ISOSpeedLatitudezzz"),
    EXIFEX_LENS_MAKE("exifEX:LensMake"),
    EXIFEX_LENS_MODEL("exifEX:LensModel"),
    EXIFEX_LENS_SERIAL_NUMBER("exifEX:LensSerialNumber"),
    EXIFEX_LENS_SPECIFICATION("exifEX:LensSpecification"),
    EXIFEX_PHOTOGRAPHIC_SENSITIVITY("exifEX:PhotographicSensitivity"),
    EXIFEX_RECOMMENDED_EXPOSURE_INDEX("exifEX:RecommendedExposureIndex"),
    EXIFEX_SENSITIVITY_TYPE("exifEX:SensitivityType"),
    EXIFEX_STANDARD_OUTPUT_SENSITIVITY("exifEX:StandardOutput-Sensitivity"),
    TIFF_BITS_PER_SAMPLE("tiff:BitsPerSample"),
    TIFF_COMPRESSION("tiff:Compression"),
    TIFF_DATE_TIME("tiff:DateTime"),
    TIFF_IMAGE_LENGTH("tiff:ImageLength"),
    TIFF_IMAGE_WIDTH("tiff:ImageWidth"),
    TIFF_MAKE("tiff:Make"),
    TIFF_MODEL("tiff:Model"),
    TIFF_ORIENTATION("tiff:Orientation"),
    TIFF_PHOTOMETRIC_INTERPRETATION("tiff:PhotometricInterpretation"),
    TIFF_PLANAR_CONFIGURATION("tiff:PlanarConfiguration"),
    TIFF_PRIMARY_CHROMATICITIES("tiff:PrimaryChromaticities"),
    TIFF_REFERENCE_BLACK_WHITE("tiff:ReferenceBlackWhite"),
    TIFF_RESOLUTION_UNIT("tiff:ResolutionUnit"),
    TIFF_SAMPLES_PER_PIXEL("tiff:SamplesPerPixel"),
    TIFF_SOFTWARE("tiff:Software"),
    TIFF_TRANSFER_FUNCTION("tiff:TransferFunction"),
    TIFF_WHITE_POINT("tiff:WhitePoint"),
    TIFF_X_RESOLUTION("tiff:XResolution"),
    TIFF_Y_RESOLUTION("tiff:YResolution"),
    TIFF_YCBCR_COEFFICIENTS("tiff:YCbCrCoefficients"),
    TIFF_YCBCR_POSITIONING("tiff:YCbCrPositioning"),
    TIFF_YCBCR_SUBSAMPLING("tiff:YCbCrSubSampling");

    private final String str;

    Exif(String str) {
        this.str = str;
    }

    public final String getStr() {
        return this.str;
    }
}
