package com.android.systemui.navigationbar.bandaid;

import kotlin.enums.EnumEntriesKt;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: qb/97869455 e70885ee4e20e40425471e4b47759369a50273352e1b7033cea52247075b3cbb */
/* loaded from: classes2.dex */
public final class BandAid {
    public static final /* synthetic */ BandAid[] $VALUES;
    public static final BandAid COLOR_PACK_ON_UPDATE_REGION_SAMPLING_LISTENER;
    public static final BandAid COLOR_PACK_REEVALUATE_NAVBAR;
    public static final BandAid CONFIG_PACK_ACTION_SOFT_RESET;
    public static final BandAid CONFIG_PACK_CONFIG_CHANGED;
    public static final BandAid CONFIG_PACK_GET_DEADZONE_SIZE;
    public static final BandAid CONFIG_PACK_KEY_ORDER_CHANGED;
    public static final BandAid CONFIG_PACK_KEY_POSITION_CHANGED;
    public static final BandAid CONFIG_PACK_NAVBAR_ICON_MARQUEE;
    public static final BandAid CONFIG_PACK_OPEN_THEME_CHANGED;
    public static final BandAid CONFIG_PACK_THEME_DEFAULT_CHANGED;
    public static final BandAid COVER_SCREEN_PACK_COVER_WINDOW_STATE;
    public static final BandAid COVER_SCREEN_PACK_FOLD_STATE_CHANGED;
    public static final BandAid COVER_SCREEN_PACK_GET_DEADZONE_SIZE;
    public static final BandAid COVER_SCREEN_PACK_GET_NAVBAR_PADDING;
    public static final BandAid COVER_SCREEN_PACK_NAVBAR_ATTACHED_TO_WINDOW;
    public static final BandAid COVER_SCREEN_PACK_NAVBAR_DETACHED_TO_WINDOW;
    public static final BandAid COVER_SCREEN_PACK_NAVBAR_VISIBILITY_CHANGED;
    public static final BandAid COVER_SCREEN_PACK_ROTATION_CHANGED;
    public static final BandAid GESTURE_PACK_BOTTOM_SENSITIVITY_CHANGED;
    public static final BandAid GESTURE_PACK_EDGE_BACK_GESTURE_DISABLE_BY_POLICY;
    public static final BandAid GESTURE_PACK_KNOX_HARD_KEY_INTENT_POLICY;
    public static final BandAid GESTURE_PACK_MOVE_HINT_VI;
    public static final BandAid GESTURE_PACK_RECALCULATE_INSET_SCALE;
    public static final BandAid GESTURE_PACK_RESET_HINT_VI;
    public static final BandAid GESTURE_PACK_SET_HINT_GROUP;
    public static final BandAid GESTURE_PACK_SET_HINT_VISIBILITY;
    public static final BandAid GESTURE_PACK_SHOW_FLOATING_GAMETOOLS_ICON;
    public static final BandAid GESTURE_PACK_START_HINT_VI;
    public static final BandAid GESTURE_PACK_UPDATE_ACTIVE_INDICATOR_SPRING_PARAMS;
    public static final BandAid GESTURE_PACK_UPDATE_GAMETOOLS_VISIBILITY;
    public static final BandAid GESTURE_PACK_UPDATE_ONEHAND_MODE_INFO;
    public static final BandAid GESTURE_PACK_UPDATE_REGION_SAMPLING_RECT;
    public static final BandAid GESTURE_PACK_UPDATE_SYSTEMUI_STATE_FLAG;
    public static final BandAid MISC_PACK_CONTROL_NAVBAR_IN_DEX_STANDALONE;
    public static final BandAid MISC_PACK_SHOW_A11Y_SWIPE_UP_TIP_POPUP;
    public static final BandAid MISC_PACK_UPDATE_A11Y_STATE_ON_USER_SWITCHED;
    public static final BandAid PLUGIN_PACK_RUN_PLUGIN_ACTIONS;
    public static final BandAid REMOTE_VIEW_PACK_INIT_REMOTE_VIEW_MANAGER;
    public static final BandAid REMOTE_VIEW_PACK_PACKAGE_REMOVED;
    public static final BandAid REMOTE_VIEW_PACK_SET_NAVBAR_SHORTCUT_TO_MANAGER;
    public static final BandAid REMOTE_VIEW_PACK_SET_REMOTEVIEW_CONTAINER;
    public static final BandAid REMOTE_VIEW_PACK_UPDATE_DARK_INTENSITY;
    public static final BandAid SETUPWIZARD_PACK_SET_NAVBAR_ICON_HINT;
    public static final BandAid SETUPWIZARD_PACK_SET_NAVBAR_STYLE;
    public static final BandAid SETUPWIZARD_PACK_UPDATE_A11Y_SERVICE;
    public static final BandAid SETUPWIZARD_PACK_UPDATE_DARK_INTENSITY;
    public static final BandAid SETUPWIZARD_PACK_UPDATE_DISABLE_FLAGS;
    public static final BandAid STABLE_LAYOUT_PACK_BAR_LAYOUT_PARAMS_CHANGED;
    public static final BandAid STABLE_LAYOUT_PACK_BUTTON_TO_HIDE_KEYBOARD_CHANGED;
    public static final BandAid STABLE_LAYOUT_PACK_GET_BAR_LAYOUT_PARAMS;
    public static final BandAid STABLE_LAYOUT_PACK_GET_DEFAULT_LAYOUT;
    public static final BandAid STABLE_LAYOUT_PACK_GET_IME_INSETS;
    public static final BandAid STABLE_LAYOUT_PACK_GET_INFLATE_LAYOUT_ID;
    public static final BandAid STABLE_LAYOUT_PACK_GET_MANDATORY_INSETS;
    public static final BandAid STABLE_LAYOUT_PACK_GET_NAVBAR_INSETS;
    public static final BandAid STABLE_LAYOUT_PACK_INFLATE_NAVBAR;
    public static final BandAid STABLE_LAYOUT_PACK_INFLATE_NAVBAR_SIDE_PADDING;
    public static final BandAid STABLE_LAYOUT_PACK_NAVBAR_ATTACHED_TO_WINDOW;
    public static final BandAid STABLE_LAYOUT_PACK_NAVBAR_CONFIG_CHANGED;
    public static final BandAid TASKBAR_PACK_ATTACHED_TO_WINDOW;
    public static final BandAid TASKBAR_PACK_CONFIG_CHANGED;
    public static final BandAid TASKBAR_PACK_DETACHED_FROM_WINDOW;
    public static final BandAid TASKBAR_PACK_OPEN_THEME_CHANGED;
    public static final BandAid TASKBAR_PACK_PACKAGE_REMOVED;
    public static final BandAid TASKBAR_PACK_ROTATION_LOCKED_CHANGED;
    public static final BandAid TASKBAR_PACK_SET_REMOTEVIEW;
    public static final BandAid TASKBAR_PACK_UPDATE_A11Y_STATE_ON_USER_SWITCHED;
    public static final BandAid TASKBAR_PACK_UPDATE_SIDE_BACK_INSETS;
    public static final BandAid TASKBAR_PACK_UPDATE_TASKBAR_AVAILABLE;
    public static final BandAid TASKBAR_PACK_UPDATE_VISIBILITY_BY_KNOX;
    public static final BandAid VIS_PACK_REEVAULATE_NAVBAR;
    public static final BandAid VIS_PACK_UPDATE_NAVBAR_VISIBILITY;
    public static final BandAid VIS_PACK_UPDATE_NAVBAR_VISIBILITY_BY_KNOX;
    public static final BandAid VIS_PACK_UPDATE_SYSTEMUI_STATE_FLAG;
    private final boolean enabled;

    static {
        BandAid bandAid = new BandAid("VIS_PACK_UPDATE_NAVBAR_VISIBILITY_BY_KNOX", 0, true);
        VIS_PACK_UPDATE_NAVBAR_VISIBILITY_BY_KNOX = bandAid;
        BandAid bandAid2 = new BandAid("VIS_PACK_UPDATE_NAVBAR_VISIBILITY", 1, true);
        VIS_PACK_UPDATE_NAVBAR_VISIBILITY = bandAid2;
        BandAid bandAid3 = new BandAid("VIS_PACK_UPDATE_SYSTEMUI_STATE_FLAG", 2, true);
        VIS_PACK_UPDATE_SYSTEMUI_STATE_FLAG = bandAid3;
        BandAid bandAid4 = new BandAid("VIS_PACK_REEVAULATE_NAVBAR", 3, true);
        VIS_PACK_REEVAULATE_NAVBAR = bandAid4;
        BandAid bandAid5 = new BandAid("CONFIG_PACK_CONFIG_CHANGED", 4, true);
        CONFIG_PACK_CONFIG_CHANGED = bandAid5;
        BandAid bandAid6 = new BandAid("CONFIG_PACK_NAVBAR_ICON_MARQUEE", 5, true);
        CONFIG_PACK_NAVBAR_ICON_MARQUEE = bandAid6;
        BandAid bandAid7 = new BandAid("CONFIG_PACK_OPEN_THEME_CHANGED", 6, true);
        CONFIG_PACK_OPEN_THEME_CHANGED = bandAid7;
        BandAid bandAid8 = new BandAid("CONFIG_PACK_KEY_ORDER_CHANGED", 7, true);
        CONFIG_PACK_KEY_ORDER_CHANGED = bandAid8;
        BandAid bandAid9 = new BandAid("CONFIG_PACK_KEY_POSITION_CHANGED", 8, true);
        CONFIG_PACK_KEY_POSITION_CHANGED = bandAid9;
        BandAid bandAid10 = new BandAid("CONFIG_PACK_GET_DEADZONE_SIZE", 9, true);
        CONFIG_PACK_GET_DEADZONE_SIZE = bandAid10;
        BandAid bandAid11 = new BandAid("CONFIG_PACK_THEME_DEFAULT_CHANGED", 10, true);
        CONFIG_PACK_THEME_DEFAULT_CHANGED = bandAid11;
        BandAid bandAid12 = new BandAid("CONFIG_PACK_ACTION_SOFT_RESET", 11, true);
        CONFIG_PACK_ACTION_SOFT_RESET = bandAid12;
        BandAid bandAid13 = new BandAid("SETUPWIZARD_PACK_SET_NAVBAR_STYLE", 12, true);
        SETUPWIZARD_PACK_SET_NAVBAR_STYLE = bandAid13;
        BandAid bandAid14 = new BandAid("SETUPWIZARD_PACK_SET_NAVBAR_ICON_HINT", 13, true);
        SETUPWIZARD_PACK_SET_NAVBAR_ICON_HINT = bandAid14;
        BandAid bandAid15 = new BandAid("SETUPWIZARD_PACK_UPDATE_DARK_INTENSITY", 14, true);
        SETUPWIZARD_PACK_UPDATE_DARK_INTENSITY = bandAid15;
        BandAid bandAid16 = new BandAid("SETUPWIZARD_PACK_UPDATE_DISABLE_FLAGS", 15, true);
        SETUPWIZARD_PACK_UPDATE_DISABLE_FLAGS = bandAid16;
        BandAid bandAid17 = new BandAid("SETUPWIZARD_PACK_UPDATE_A11Y_SERVICE", 16, true);
        SETUPWIZARD_PACK_UPDATE_A11Y_SERVICE = bandAid17;
        BandAid bandAid18 = new BandAid("MISC_PACK_SHOW_A11Y_SWIPE_UP_TIP_POPUP", 17, true);
        MISC_PACK_SHOW_A11Y_SWIPE_UP_TIP_POPUP = bandAid18;
        BandAid bandAid19 = new BandAid("MISC_PACK_CONTROL_NAVBAR_IN_DEX_STANDALONE", 18, true);
        MISC_PACK_CONTROL_NAVBAR_IN_DEX_STANDALONE = bandAid19;
        BandAid bandAid20 = new BandAid("MISC_PACK_UPDATE_A11Y_STATE_ON_USER_SWITCHED", 19, true);
        MISC_PACK_UPDATE_A11Y_STATE_ON_USER_SWITCHED = bandAid20;
        BandAid bandAid21 = new BandAid("COLOR_PACK_REEVALUATE_NAVBAR", 20, true);
        COLOR_PACK_REEVALUATE_NAVBAR = bandAid21;
        BandAid bandAid22 = new BandAid("COLOR_PACK_ON_UPDATE_REGION_SAMPLING_LISTENER", 21, true);
        COLOR_PACK_ON_UPDATE_REGION_SAMPLING_LISTENER = bandAid22;
        BandAid bandAid23 = new BandAid("STABLE_LAYOUT_PACK_INFLATE_NAVBAR", 22, true);
        STABLE_LAYOUT_PACK_INFLATE_NAVBAR = bandAid23;
        BandAid bandAid24 = new BandAid("STABLE_LAYOUT_PACK_INFLATE_NAVBAR_SIDE_PADDING", 23, true);
        STABLE_LAYOUT_PACK_INFLATE_NAVBAR_SIDE_PADDING = bandAid24;
        BandAid bandAid25 = new BandAid("STABLE_LAYOUT_PACK_GET_DEFAULT_LAYOUT", 24, true);
        STABLE_LAYOUT_PACK_GET_DEFAULT_LAYOUT = bandAid25;
        BandAid bandAid26 = new BandAid("STABLE_LAYOUT_PACK_GET_INFLATE_LAYOUT_ID", 25, true);
        STABLE_LAYOUT_PACK_GET_INFLATE_LAYOUT_ID = bandAid26;
        BandAid bandAid27 = new BandAid("STABLE_LAYOUT_PACK_NAVBAR_CONFIG_CHANGED", 26, true);
        STABLE_LAYOUT_PACK_NAVBAR_CONFIG_CHANGED = bandAid27;
        BandAid bandAid28 = new BandAid("STABLE_LAYOUT_PACK_GET_BAR_LAYOUT_PARAMS", 27, true);
        STABLE_LAYOUT_PACK_GET_BAR_LAYOUT_PARAMS = bandAid28;
        BandAid bandAid29 = new BandAid("STABLE_LAYOUT_PACK_BAR_LAYOUT_PARAMS_CHANGED", 28, true);
        STABLE_LAYOUT_PACK_BAR_LAYOUT_PARAMS_CHANGED = bandAid29;
        BandAid bandAid30 = new BandAid("STABLE_LAYOUT_PACK_NAVBAR_ATTACHED_TO_WINDOW", 29, true);
        STABLE_LAYOUT_PACK_NAVBAR_ATTACHED_TO_WINDOW = bandAid30;
        BandAid bandAid31 = new BandAid("STABLE_LAYOUT_PACK_BUTTON_TO_HIDE_KEYBOARD_CHANGED", 30, true);
        STABLE_LAYOUT_PACK_BUTTON_TO_HIDE_KEYBOARD_CHANGED = bandAid31;
        BandAid bandAid32 = new BandAid("STABLE_LAYOUT_PACK_GET_NAVBAR_INSETS", 31, true);
        STABLE_LAYOUT_PACK_GET_NAVBAR_INSETS = bandAid32;
        BandAid bandAid33 = new BandAid("STABLE_LAYOUT_PACK_GET_IME_INSETS", 32, true);
        STABLE_LAYOUT_PACK_GET_IME_INSETS = bandAid33;
        BandAid bandAid34 = new BandAid("STABLE_LAYOUT_PACK_GET_MANDATORY_INSETS", 33, true);
        STABLE_LAYOUT_PACK_GET_MANDATORY_INSETS = bandAid34;
        BandAid bandAid35 = new BandAid("REMOTE_VIEW_PACK_INIT_REMOTE_VIEW_MANAGER", 34, true);
        REMOTE_VIEW_PACK_INIT_REMOTE_VIEW_MANAGER = bandAid35;
        BandAid bandAid36 = new BandAid("REMOTE_VIEW_PACK_UPDATE_DARK_INTENSITY", 35, true);
        REMOTE_VIEW_PACK_UPDATE_DARK_INTENSITY = bandAid36;
        BandAid bandAid37 = new BandAid("REMOTE_VIEW_PACK_SET_NAVBAR_SHORTCUT_TO_MANAGER", 36, true);
        REMOTE_VIEW_PACK_SET_NAVBAR_SHORTCUT_TO_MANAGER = bandAid37;
        BandAid bandAid38 = new BandAid("REMOTE_VIEW_PACK_SET_REMOTEVIEW_CONTAINER", 37, true);
        REMOTE_VIEW_PACK_SET_REMOTEVIEW_CONTAINER = bandAid38;
        BandAid bandAid39 = new BandAid("REMOTE_VIEW_PACK_PACKAGE_REMOVED", 38, true);
        REMOTE_VIEW_PACK_PACKAGE_REMOVED = bandAid39;
        BandAid bandAid40 = new BandAid("GESTURE_PACK_SET_HINT_GROUP", 39, true);
        GESTURE_PACK_SET_HINT_GROUP = bandAid40;
        BandAid bandAid41 = new BandAid("GESTURE_PACK_START_HINT_VI", 40, true);
        GESTURE_PACK_START_HINT_VI = bandAid41;
        BandAid bandAid42 = new BandAid("GESTURE_PACK_MOVE_HINT_VI", 41, true);
        GESTURE_PACK_MOVE_HINT_VI = bandAid42;
        BandAid bandAid43 = new BandAid("GESTURE_PACK_RESET_HINT_VI", 42, true);
        GESTURE_PACK_RESET_HINT_VI = bandAid43;
        BandAid bandAid44 = new BandAid("GESTURE_PACK_SET_HINT_VISIBILITY", 43, true);
        GESTURE_PACK_SET_HINT_VISIBILITY = bandAid44;
        BandAid bandAid45 = new BandAid("GESTURE_PACK_EDGE_BACK_GESTURE_DISABLE_BY_POLICY", 44, true);
        GESTURE_PACK_EDGE_BACK_GESTURE_DISABLE_BY_POLICY = bandAid45;
        BandAid bandAid46 = new BandAid("GESTURE_PACK_KNOX_HARD_KEY_INTENT_POLICY", 45, true);
        GESTURE_PACK_KNOX_HARD_KEY_INTENT_POLICY = bandAid46;
        BandAid bandAid47 = new BandAid("GESTURE_PACK_UPDATE_GAMETOOLS_VISIBILITY", 46, true);
        GESTURE_PACK_UPDATE_GAMETOOLS_VISIBILITY = bandAid47;
        BandAid bandAid48 = new BandAid("GESTURE_PACK_SHOW_FLOATING_GAMETOOLS_ICON", 47, true);
        GESTURE_PACK_SHOW_FLOATING_GAMETOOLS_ICON = bandAid48;
        BandAid bandAid49 = new BandAid("GESTURE_PACK_UPDATE_SYSTEMUI_STATE_FLAG", 48, true);
        GESTURE_PACK_UPDATE_SYSTEMUI_STATE_FLAG = bandAid49;
        BandAid bandAid50 = new BandAid("GESTURE_PACK_UPDATE_ONEHAND_MODE_INFO", 49, true);
        GESTURE_PACK_UPDATE_ONEHAND_MODE_INFO = bandAid50;
        BandAid bandAid51 = new BandAid("GESTURE_PACK_UPDATE_REGION_SAMPLING_RECT", 50, true);
        GESTURE_PACK_UPDATE_REGION_SAMPLING_RECT = bandAid51;
        BandAid bandAid52 = new BandAid("GESTURE_PACK_RECALCULATE_INSET_SCALE", 51, true);
        GESTURE_PACK_RECALCULATE_INSET_SCALE = bandAid52;
        BandAid bandAid53 = new BandAid("GESTURE_PACK_BOTTOM_SENSITIVITY_CHANGED", 52, true);
        GESTURE_PACK_BOTTOM_SENSITIVITY_CHANGED = bandAid53;
        BandAid bandAid54 = new BandAid("GESTURE_PACK_UPDATE_ACTIVE_INDICATOR_SPRING_PARAMS", 53, true);
        GESTURE_PACK_UPDATE_ACTIVE_INDICATOR_SPRING_PARAMS = bandAid54;
        BandAid bandAid55 = new BandAid("PLUGIN_PACK_RUN_PLUGIN_ACTIONS", 54, true);
        PLUGIN_PACK_RUN_PLUGIN_ACTIONS = bandAid55;
        BandAid bandAid56 = new BandAid("TASKBAR_PACK_OPEN_THEME_CHANGED", 55, true);
        TASKBAR_PACK_OPEN_THEME_CHANGED = bandAid56;
        BandAid bandAid57 = new BandAid("TASKBAR_PACK_ROTATION_LOCKED_CHANGED", 56, true);
        TASKBAR_PACK_ROTATION_LOCKED_CHANGED = bandAid57;
        BandAid bandAid58 = new BandAid("TASKBAR_PACK_SET_REMOTEVIEW", 57, true);
        TASKBAR_PACK_SET_REMOTEVIEW = bandAid58;
        BandAid bandAid59 = new BandAid("TASKBAR_PACK_UPDATE_VISIBILITY_BY_KNOX", 58, true);
        TASKBAR_PACK_UPDATE_VISIBILITY_BY_KNOX = bandAid59;
        BandAid bandAid60 = new BandAid("TASKBAR_PACK_ATTACHED_TO_WINDOW", 59, true);
        TASKBAR_PACK_ATTACHED_TO_WINDOW = bandAid60;
        BandAid bandAid61 = new BandAid("TASKBAR_PACK_DETACHED_FROM_WINDOW", 60, true);
        TASKBAR_PACK_DETACHED_FROM_WINDOW = bandAid61;
        BandAid bandAid62 = new BandAid("TASKBAR_PACK_PACKAGE_REMOVED", 61, true);
        TASKBAR_PACK_PACKAGE_REMOVED = bandAid62;
        BandAid bandAid63 = new BandAid("TASKBAR_PACK_CONFIG_CHANGED", 62, true);
        TASKBAR_PACK_CONFIG_CHANGED = bandAid63;
        BandAid bandAid64 = new BandAid("TASKBAR_PACK_UPDATE_SIDE_BACK_INSETS", 63, true);
        TASKBAR_PACK_UPDATE_SIDE_BACK_INSETS = bandAid64;
        BandAid bandAid65 = new BandAid("TASKBAR_PACK_UPDATE_TASKBAR_AVAILABLE", 64, true);
        TASKBAR_PACK_UPDATE_TASKBAR_AVAILABLE = bandAid65;
        BandAid bandAid66 = new BandAid("TASKBAR_PACK_UPDATE_A11Y_STATE_ON_USER_SWITCHED", 65, true);
        TASKBAR_PACK_UPDATE_A11Y_STATE_ON_USER_SWITCHED = bandAid66;
        BandAid bandAid67 = new BandAid("COVER_SCREEN_PACK_NAVBAR_VISIBILITY_CHANGED", 66, true);
        COVER_SCREEN_PACK_NAVBAR_VISIBILITY_CHANGED = bandAid67;
        BandAid bandAid68 = new BandAid("COVER_SCREEN_PACK_NAVBAR_ATTACHED_TO_WINDOW", 67, true);
        COVER_SCREEN_PACK_NAVBAR_ATTACHED_TO_WINDOW = bandAid68;
        BandAid bandAid69 = new BandAid("COVER_SCREEN_PACK_NAVBAR_DETACHED_TO_WINDOW", 68, true);
        COVER_SCREEN_PACK_NAVBAR_DETACHED_TO_WINDOW = bandAid69;
        BandAid bandAid70 = new BandAid("COVER_SCREEN_PACK_GET_NAVBAR_PADDING", 69, true);
        COVER_SCREEN_PACK_GET_NAVBAR_PADDING = bandAid70;
        BandAid bandAid71 = new BandAid("COVER_SCREEN_PACK_FOLD_STATE_CHANGED", 70, true);
        COVER_SCREEN_PACK_FOLD_STATE_CHANGED = bandAid71;
        BandAid bandAid72 = new BandAid("COVER_SCREEN_PACK_GET_DEADZONE_SIZE", 71, true);
        COVER_SCREEN_PACK_GET_DEADZONE_SIZE = bandAid72;
        BandAid bandAid73 = new BandAid("COVER_SCREEN_PACK_COVER_WINDOW_STATE", 72, true);
        COVER_SCREEN_PACK_COVER_WINDOW_STATE = bandAid73;
        BandAid bandAid74 = new BandAid("COVER_SCREEN_PACK_ROTATION_CHANGED", 73, true);
        COVER_SCREEN_PACK_ROTATION_CHANGED = bandAid74;
        BandAid[] bandAidArr = {bandAid, bandAid2, bandAid3, bandAid4, bandAid5, bandAid6, bandAid7, bandAid8, bandAid9, bandAid10, bandAid11, bandAid12, bandAid13, bandAid14, bandAid15, bandAid16, bandAid17, bandAid18, bandAid19, bandAid20, bandAid21, bandAid22, bandAid23, bandAid24, bandAid25, bandAid26, bandAid27, bandAid28, bandAid29, bandAid30, bandAid31, bandAid32, bandAid33, bandAid34, bandAid35, bandAid36, bandAid37, bandAid38, bandAid39, bandAid40, bandAid41, bandAid42, bandAid43, bandAid44, bandAid45, bandAid46, bandAid47, bandAid48, bandAid49, bandAid50, bandAid51, bandAid52, bandAid53, bandAid54, bandAid55, bandAid56, bandAid57, bandAid58, bandAid59, bandAid60, bandAid61, bandAid62, bandAid63, bandAid64, bandAid65, bandAid66, bandAid67, bandAid68, bandAid69, bandAid70, bandAid71, bandAid72, bandAid73, bandAid74};
        $VALUES = bandAidArr;
        EnumEntriesKt.enumEntries(bandAidArr);
    }

    private BandAid(String str, int i, boolean z) {
        this.enabled = z;
    }

    public static BandAid valueOf(String str) {
        return (BandAid) Enum.valueOf(BandAid.class, str);
    }

    public static BandAid[] values() {
        return (BandAid[]) $VALUES.clone();
    }

    public final boolean getEnabled() {
        return this.enabled;
    }
}
