package com.android.systemui.shade;

import android.view.accessibility.AccessibilityManager;
import com.android.internal.logging.MetricsLogger;
import com.android.internal.statusbar.IStatusBarService;
import com.android.internal.util.LatencyTracker;
import com.android.keyguard.EmergencyButtonController;
import com.android.keyguard.KeyguardUpdateMonitor;
import com.android.keyguard.SecLockIconViewController;
import com.android.keyguard.dagger.KeyguardStatusBarViewComponent;
import com.android.keyguard.punchhole.KeyguardPunchHoleVIViewController;
import com.android.systemui.bouncer.domain.interactor.AlternateBouncerInteractor;
import com.android.systemui.classifier.FalsingCollector;
import com.android.systemui.common.domain.interactor.SysUIStateDisplaysInteractor;
import com.android.systemui.dagger.DaggerReferenceGlobalRootComponent;
import com.android.systemui.deviceentry.domain.interactor.DeviceEntryFaceAuthInteractor;
import com.android.systemui.doze.DozeLog;
import com.android.systemui.dump.DumpManager;
import com.android.systemui.fragments.FragmentService;
import com.android.systemui.keyguard.KeyguardClickController;
import com.android.systemui.keyguard.KeyguardEditModeController;
import com.android.systemui.keyguard.KeyguardUnlockAnimationController;
import com.android.systemui.keyguard.animator.KeyguardTouchAnimator;
import com.android.systemui.keyguard.domain.interactor.KeyguardClockInteractor;
import com.android.systemui.keyguard.domain.interactor.KeyguardInteractor;
import com.android.systemui.keyguard.domain.interactor.KeyguardTransitionInteractor;
import com.android.systemui.keyguard.ui.transitions.BlurConfig;
import com.android.systemui.keyguard.ui.viewmodel.DreamingToLockscreenTransitionViewModel;
import com.android.systemui.keyguard.ui.viewmodel.KeyguardTouchHandlingViewModel;
import com.android.systemui.keyguardimage.WallpaperImageInjectCreator;
import com.android.systemui.media.controls.domain.pipeline.MediaDataManager;
import com.android.systemui.media.controls.ui.controller.KeyguardMediaController;
import com.android.systemui.media.controls.ui.controller.MediaHierarchyManager;
import com.android.systemui.model.SysUiState;
import com.android.systemui.navigationbar.NavigationBarController;
import com.android.systemui.navigationbar.NavigationModeController;
import com.android.systemui.pluginlock.PluginLockData;
import com.android.systemui.pluginlock.PluginLockMediator;
import com.android.systemui.plugins.ActivityStarter;
import com.android.systemui.plugins.FalsingManager;
import com.android.systemui.plugins.statusbar.StatusBarStateController;
import com.android.systemui.power.domain.interactor.PowerInteractor;
import com.android.systemui.privacy.PrivacyDialogController;
import com.android.systemui.samsung.quicksetting.SecQSPanelComposeAdapter;
import com.android.systemui.settings.brightness.data.repository.BrightnessMirrorShowingRepository;
import com.android.systemui.shade.data.repository.ShadeRepository;
import com.android.systemui.shade.domain.interactor.SecHideNotificationShadeInMirrorInteractor;
import com.android.systemui.shade.domain.interactor.SecQuickSettingsAffordanceInteractor;
import com.android.systemui.shade.domain.interactor.ShadeAnimationInteractor;
import com.android.systemui.statusbar.CommandQueue;
import com.android.systemui.statusbar.KeyguardIndicationController;
import com.android.systemui.statusbar.LockscreenNotificationManager;
import com.android.systemui.statusbar.LockscreenShadeTransitionController;
import com.android.systemui.statusbar.NotificationShadeDepthController;
import com.android.systemui.statusbar.NotificationShadeWindowController;
import com.android.systemui.statusbar.NotificationShelfManager;
import com.android.systemui.statusbar.PulseExpansionHandler;
import com.android.systemui.statusbar.VibratorHelper;
import com.android.systemui.statusbar.iconsOnly.LockscreenNotificationIconsOnlyController;
import com.android.systemui.statusbar.notification.ConversationNotificationManager;
import com.android.systemui.statusbar.notification.DynamicPrivacyController;
import com.android.systemui.statusbar.notification.NotificationWakeUpCoordinator;
import com.android.systemui.statusbar.notification.domain.interactor.ActiveNotificationsInteractor;
import com.android.systemui.statusbar.notification.row.NotificationGutsManager;
import com.android.systemui.statusbar.notification.stack.AmbientState;
import com.android.systemui.statusbar.notification.stack.NotificationListContainer;
import com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayoutController;
import com.android.systemui.statusbar.notification.stack.domain.interactor.SharedNotificationContainerInteractor;
import com.android.systemui.statusbar.phone.DcmMascotViewContainer;
import com.android.systemui.statusbar.phone.DozeParameters;
import com.android.systemui.statusbar.phone.KeyguardBypassController;
import com.android.systemui.statusbar.phone.KeyguardClockPositionAlgorithm;
import com.android.systemui.statusbar.phone.LockscreenGestureLogger;
import com.android.systemui.statusbar.phone.ScreenOffAnimationController;
import com.android.systemui.statusbar.phone.ScrimController;
import com.android.systemui.statusbar.phone.ShadeTouchableRegionManager;
import com.android.systemui.statusbar.phone.StatusBarKeyguardViewManager;
import com.android.systemui.statusbar.phone.TapAgainViewController;
import com.android.systemui.statusbar.phone.UnlockedScreenOffAnimationController;
import com.android.systemui.statusbar.policy.ConfigurationController;
import com.android.systemui.statusbar.policy.KeyguardStateController;
import com.android.systemui.statusbar.policy.SplitShadeStateController;
import com.android.systemui.user.domain.interactor.SelectedUserInteractor;
import com.android.systemui.util.QsStatusEventLog;
import com.android.systemui.util.SecQsUiDisplayModeInteractor;
import com.android.systemui.util.time.SystemClock;
import com.android.systemui.wallpaper.KeyguardWallpaperController;
import com.android.systemui.wallpapers.ui.viewmodel.WallpaperFocalAreaViewModel;
import com.google.android.msdl.domain.MSDLPlayer;
import dagger.Lazy;
import dagger.internal.DoubleCheck;
import dagger.internal.Provider;
import java.util.Optional;
import kotlinx.coroutines.CoroutineDispatcher;

/* loaded from: classes3.dex */
public final class NotificationPanelViewController_Factory implements Provider {
    public final Provider accessibilityManagerProvider;
    public final Provider activeNotificationsInteractorProvider;
    public final Provider activityStarterProvider;
    public final Provider alternateBouncerInteractorProvider;
    public final Provider ambientStateProvider;
    public final Provider blurConfigProvider;
    public final Provider brightnessMirrorShowingRepositoryProvider;
    public final Provider bypassControllerProvider;
    public final Provider commandQueueProvider;
    public final Provider configurationControllerProvider;
    public final Provider conversationNotificationManagerProvider;
    public final Provider coordinatorProvider;
    public final Provider dataUsageLabelManagerLazyProvider;
    public final Provider deviceEntryFaceAuthInteractorProvider;
    public final Provider displayIdProvider;
    public final Provider dozeLogProvider;
    public final Provider dozeParametersProvider;
    public final Provider dreamingToLockscreenTransitionViewModelProvider;
    public final Provider dumpManagerProvider;
    public final Provider dynamicPrivacyControllerProvider;
    public final Provider editModeControllerProvider;
    public final Provider emergencyButtonControllerFactoryProvider;
    public final Provider falsingCollectorProvider;
    public final Provider falsingManagerProvider;
    public final Provider flingAnimationUtilsBuilderProvider;
    public final Provider fragmentServiceProvider;
    public final Provider gutsManagerProvider;
    public final Provider hideNotificationShadeInMirrorInteractorProvider;
    public final Provider keyguardClickControllerProvider;
    public final Provider keyguardClockInteractorProvider;
    public final Provider keyguardClockPositionAlgorithmProvider;
    public final Provider keyguardIndicationControllerProvider;
    public final Provider keyguardInteractorProvider;
    public final Provider keyguardMediaControllerProvider;
    public final Provider keyguardSecBottomAreaViewControllerProvider;
    public final Provider keyguardStateControllerProvider;
    public final Provider keyguardStatusBarViewComponentFactoryProvider;
    public final Provider keyguardTouchAnimatorProvider;
    public final Provider keyguardTouchHandlingViewModelProvider;
    public final Provider keyguardTransitionInteractorProvider;
    public final Provider keyguardUnlockAnimationControllerProvider;
    public final Provider keyguardUpdateMonitorProvider;
    public final Provider keyguardWallpaperControllerProvider;
    public final Provider latencyTrackerProvider;
    public final Provider lockIconViewControllerProvider;
    public final Provider lockscreenGestureLoggerProvider;
    public final Provider lockscreenNotificationIconsOnlyControllerProvider;
    public final Provider lockscreenNotificationManagerProvider;
    public final Provider lockscreenShadeTransitionControllerProvider;
    public final Provider mBioUnlockControllerLazyProvider;
    public final Provider mainDispatcherProvider;
    public final Provider mascotViewContainerProvider;
    public final Provider mediaDataManagerProvider;
    public final Provider mediaHierarchyManagerProvider;
    public final Provider metricsLoggerProvider;
    public final Provider msdlPlayerProvider;
    public final Provider navigationBarControllerProvider;
    public final Provider navigationModeControllerProvider;
    public final Provider notificationListContainerProvider;
    public final Provider notificationShadeDepthControllerProvider;
    public final Provider notificationShadeWindowControllerProvider;
    public final Provider notificationShelfManagerProvider;
    public final Provider notificationStackScrollLayoutControllerProvider;
    public final Provider notificationsQSContainerControllerProvider;
    public final Provider panelPopOverManagerProvider;
    public final Provider pluginAODManagerLazyProvider;
    public final Provider pluginLockDataProvider;
    public final Provider pluginLockMediatorProvider;
    public final Provider pluginLockStarManagerLazyProvider;
    public final Provider powerInteractorProvider;
    public final Provider privacyDialogControllerProvider;
    public final Provider pulseExpansionHandlerProvider;
    public final Provider punchHoleVIViewControllerFactoryProvider;
    public final Provider qsPanelComposeProvider;
    public final Provider qsStatusEventLogProvider;
    public final Provider quickSettingsControllerProvider;
    public final Provider samsungBarExtProvider;
    public final Provider screenOffAnimationControllerProvider;
    public final Provider scrimControllerProvider;
    public final Provider secQsUiDisplayModeInteractorProvider;
    public final Provider secQuickSettingsAffordanceInteractorProvider;
    public final Provider selectedUserInteractorProvider;
    public final Provider shadeAnimationInteractorProvider;
    public final Provider shadeDisplaysRepositoryProvider;
    public final Provider shadeExpansionStateManagerProvider;
    public final Provider shadeHeaderControllerProvider;
    public final Provider shadeLoggerProvider;
    public final Provider shadeRepositoryProvider;
    public final Provider shadeTouchableRegionManagerProvider;
    public final Provider sharedNotificationContainerInteractorProvider;
    public final Provider splitShadeStateControllerProvider;
    public final Provider statusBarKeyguardViewManagerProvider;
    public final Provider statusBarServiceProvider;
    public final Provider statusBarStateControllerProvider;
    public final Provider sysUIStateDisplaysInteractorProvider;
    public final Provider sysUiStateProvider;
    public final Provider systemClockProvider;
    public final Provider tapAgainViewControllerProvider;
    public final Provider unfoldComponentProvider;
    public final Provider unlockedScreenOffAnimationControllerProvider;
    public final Provider vibratorHelperProvider;
    public final Provider viewProvider;
    public final Provider wallpaperFocalAreaViewModelProvider;
    public final Provider wallpaperImageCreatorProvider;

    public NotificationPanelViewController_Factory(Provider provider, Provider provider2, Provider provider3, Provider provider4, Provider provider5, Provider provider6, Provider provider7, Provider provider8, Provider provider9, Provider provider10, Provider provider11, Provider provider12, Provider provider13, Provider provider14, Provider provider15, Provider provider16, Provider provider17, Provider provider18, Provider provider19, Provider provider20, Provider provider21, Provider provider22, Provider provider23, Provider provider24, Provider provider25, Provider provider26, Provider provider27, Provider provider28, Provider provider29, Provider provider30, Provider provider31, Provider provider32, Provider provider33, Provider provider34, Provider provider35, Provider provider36, Provider provider37, Provider provider38, Provider provider39, Provider provider40, Provider provider41, Provider provider42, Provider provider43, Provider provider44, Provider provider45, Provider provider46, Provider provider47, Provider provider48, Provider provider49, Provider provider50, Provider provider51, Provider provider52, Provider provider53, Provider provider54, Provider provider55, Provider provider56, Provider provider57, Provider provider58, Provider provider59, Provider provider60, Provider provider61, Provider provider62, Provider provider63, Provider provider64, Provider provider65, Provider provider66, Provider provider67, Provider provider68, Provider provider69, Provider provider70, Provider provider71, Provider provider72, Provider provider73, Provider provider74, Provider provider75, Provider provider76, Provider provider77, Provider provider78, Provider provider79, Provider provider80, Provider provider81, Provider provider82, Provider provider83, Provider provider84, Provider provider85, Provider provider86, Provider provider87, Provider provider88, Provider provider89, Provider provider90, Provider provider91, Provider provider92, Provider provider93, Provider provider94, Provider provider95, Provider provider96, Provider provider97, Provider provider98, Provider provider99, Provider provider100, Provider provider101, Provider provider102, Provider provider103, Provider provider104) {
        this.mascotViewContainerProvider = provider;
        this.pluginLockMediatorProvider = provider2;
        this.viewProvider = provider3;
        this.keyguardTouchAnimatorProvider = provider4;
        this.pluginAODManagerLazyProvider = provider5;
        this.coordinatorProvider = provider6;
        this.pulseExpansionHandlerProvider = provider7;
        this.dynamicPrivacyControllerProvider = provider8;
        this.bypassControllerProvider = provider9;
        this.falsingManagerProvider = provider10;
        this.falsingCollectorProvider = provider11;
        this.keyguardStateControllerProvider = provider12;
        this.statusBarStateControllerProvider = provider13;
        this.notificationShadeWindowControllerProvider = provider14;
        this.dozeLogProvider = provider15;
        this.dozeParametersProvider = provider16;
        this.commandQueueProvider = provider17;
        this.vibratorHelperProvider = provider18;
        this.latencyTrackerProvider = provider19;
        this.accessibilityManagerProvider = provider20;
        this.displayIdProvider = provider21;
        this.keyguardUpdateMonitorProvider = provider22;
        this.metricsLoggerProvider = provider23;
        this.shadeLoggerProvider = provider24;
        this.configurationControllerProvider = provider25;
        this.flingAnimationUtilsBuilderProvider = provider26;
        this.shadeTouchableRegionManagerProvider = provider27;
        this.conversationNotificationManagerProvider = provider28;
        this.mediaHierarchyManagerProvider = provider29;
        this.statusBarKeyguardViewManagerProvider = provider30;
        this.gutsManagerProvider = provider31;
        this.notificationsQSContainerControllerProvider = provider32;
        this.notificationStackScrollLayoutControllerProvider = provider33;
        this.keyguardStatusBarViewComponentFactoryProvider = provider34;
        this.lockscreenShadeTransitionControllerProvider = provider35;
        this.scrimControllerProvider = provider36;
        this.mediaDataManagerProvider = provider37;
        this.notificationShadeDepthControllerProvider = provider38;
        this.ambientStateProvider = provider39;
        this.lockIconViewControllerProvider = provider40;
        this.keyguardMediaControllerProvider = provider41;
        this.tapAgainViewControllerProvider = provider42;
        this.navigationModeControllerProvider = provider43;
        this.navigationBarControllerProvider = provider44;
        this.quickSettingsControllerProvider = provider45;
        this.fragmentServiceProvider = provider46;
        this.statusBarServiceProvider = provider47;
        this.shadeHeaderControllerProvider = provider48;
        this.screenOffAnimationControllerProvider = provider49;
        this.lockscreenGestureLoggerProvider = provider50;
        this.shadeExpansionStateManagerProvider = provider51;
        this.shadeRepositoryProvider = provider52;
        this.unfoldComponentProvider = provider53;
        this.sysUiStateProvider = provider54;
        this.sysUIStateDisplaysInteractorProvider = provider55;
        this.keyguardSecBottomAreaViewControllerProvider = provider56;
        this.keyguardWallpaperControllerProvider = provider57;
        this.wallpaperImageCreatorProvider = provider58;
        this.emergencyButtonControllerFactoryProvider = provider59;
        this.keyguardUnlockAnimationControllerProvider = provider60;
        this.keyguardIndicationControllerProvider = provider61;
        this.notificationListContainerProvider = provider62;
        this.unlockedScreenOffAnimationControllerProvider = provider63;
        this.systemClockProvider = provider64;
        this.keyguardClockInteractorProvider = provider65;
        this.alternateBouncerInteractorProvider = provider66;
        this.dreamingToLockscreenTransitionViewModelProvider = provider67;
        this.mainDispatcherProvider = provider68;
        this.keyguardTransitionInteractorProvider = provider69;
        this.dumpManagerProvider = provider70;
        this.keyguardTouchHandlingViewModelProvider = provider71;
        this.wallpaperFocalAreaViewModelProvider = provider72;
        this.keyguardInteractorProvider = provider73;
        this.activityStarterProvider = provider74;
        this.sharedNotificationContainerInteractorProvider = provider75;
        this.activeNotificationsInteractorProvider = provider76;
        this.shadeAnimationInteractorProvider = provider77;
        this.deviceEntryFaceAuthInteractorProvider = provider78;
        this.splitShadeStateControllerProvider = provider79;
        this.powerInteractorProvider = provider80;
        this.keyguardClockPositionAlgorithmProvider = provider81;
        this.msdlPlayerProvider = provider82;
        this.brightnessMirrorShowingRepositoryProvider = provider83;
        this.blurConfigProvider = provider84;
        this.shadeDisplaysRepositoryProvider = provider85;
        this.privacyDialogControllerProvider = provider86;
        this.punchHoleVIViewControllerFactoryProvider = provider87;
        this.notificationShelfManagerProvider = provider88;
        this.editModeControllerProvider = provider89;
        this.keyguardClickControllerProvider = provider90;
        this.pluginLockDataProvider = provider91;
        this.pluginLockStarManagerLazyProvider = provider92;
        this.samsungBarExtProvider = provider93;
        this.lockscreenNotificationManagerProvider = provider94;
        this.lockscreenNotificationIconsOnlyControllerProvider = provider95;
        this.dataUsageLabelManagerLazyProvider = provider96;
        this.qsStatusEventLogProvider = provider97;
        this.selectedUserInteractorProvider = provider98;
        this.secQuickSettingsAffordanceInteractorProvider = provider99;
        this.qsPanelComposeProvider = provider100;
        this.hideNotificationShadeInMirrorInteractorProvider = provider101;
        this.panelPopOverManagerProvider = provider102;
        this.secQsUiDisplayModeInteractorProvider = provider103;
        this.mBioUnlockControllerLazyProvider = provider104;
    }

    public static NotificationPanelViewController newInstance(DcmMascotViewContainer dcmMascotViewContainer, PluginLockMediator pluginLockMediator, NotificationPanelView notificationPanelView, KeyguardTouchAnimator keyguardTouchAnimator, Lazy lazy, NotificationWakeUpCoordinator notificationWakeUpCoordinator, PulseExpansionHandler pulseExpansionHandler, DynamicPrivacyController dynamicPrivacyController, KeyguardBypassController keyguardBypassController, FalsingManager falsingManager, FalsingCollector falsingCollector, KeyguardStateController keyguardStateController, StatusBarStateController statusBarStateController, NotificationShadeWindowController notificationShadeWindowController, DozeLog dozeLog, DozeParameters dozeParameters, CommandQueue commandQueue, VibratorHelper vibratorHelper, LatencyTracker latencyTracker, AccessibilityManager accessibilityManager, int i, KeyguardUpdateMonitor keyguardUpdateMonitor, MetricsLogger metricsLogger, ShadeLogger shadeLogger, ConfigurationController configurationController, Provider provider, ShadeTouchableRegionManager shadeTouchableRegionManager, ConversationNotificationManager conversationNotificationManager, MediaHierarchyManager mediaHierarchyManager, StatusBarKeyguardViewManager statusBarKeyguardViewManager, NotificationGutsManager notificationGutsManager, NotificationsQSContainerController notificationsQSContainerController, NotificationStackScrollLayoutController notificationStackScrollLayoutController, DaggerReferenceGlobalRootComponent.KeyguardStatusBarViewComponentFactory keyguardStatusBarViewComponentFactory, LockscreenShadeTransitionController lockscreenShadeTransitionController, ScrimController scrimController, MediaDataManager mediaDataManager, NotificationShadeDepthController notificationShadeDepthController, AmbientState ambientState, SecLockIconViewController secLockIconViewController, KeyguardMediaController keyguardMediaController, TapAgainViewController tapAgainViewController, NavigationModeController navigationModeController, NavigationBarController navigationBarController, QuickSettingsControllerImpl quickSettingsControllerImpl, FragmentService fragmentService, IStatusBarService iStatusBarService, ShadeHeaderController shadeHeaderController, ScreenOffAnimationController screenOffAnimationController, LockscreenGestureLogger lockscreenGestureLogger, ShadeExpansionStateManager shadeExpansionStateManager, ShadeRepository shadeRepository, Optional optional, SysUiState sysUiState, SysUIStateDisplaysInteractor sysUIStateDisplaysInteractor, Provider provider2, KeyguardWallpaperController keyguardWallpaperController, WallpaperImageInjectCreator wallpaperImageInjectCreator, EmergencyButtonController.Factory factory, KeyguardUnlockAnimationController keyguardUnlockAnimationController, KeyguardIndicationController keyguardIndicationController, NotificationListContainer notificationListContainer, UnlockedScreenOffAnimationController unlockedScreenOffAnimationController, SystemClock systemClock, KeyguardClockInteractor keyguardClockInteractor, AlternateBouncerInteractor alternateBouncerInteractor, DreamingToLockscreenTransitionViewModel dreamingToLockscreenTransitionViewModel, CoroutineDispatcher coroutineDispatcher, KeyguardTransitionInteractor keyguardTransitionInteractor, DumpManager dumpManager, KeyguardTouchHandlingViewModel keyguardTouchHandlingViewModel, WallpaperFocalAreaViewModel wallpaperFocalAreaViewModel, KeyguardInteractor keyguardInteractor, ActivityStarter activityStarter, SharedNotificationContainerInteractor sharedNotificationContainerInteractor, ActiveNotificationsInteractor activeNotificationsInteractor, ShadeAnimationInteractor shadeAnimationInteractor, DeviceEntryFaceAuthInteractor deviceEntryFaceAuthInteractor, SplitShadeStateController splitShadeStateController, PowerInteractor powerInteractor, KeyguardClockPositionAlgorithm keyguardClockPositionAlgorithm, MSDLPlayer mSDLPlayer, BrightnessMirrorShowingRepository brightnessMirrorShowingRepository, BlurConfig blurConfig, Lazy lazy2, PrivacyDialogController privacyDialogController, KeyguardPunchHoleVIViewController.Factory factory2, NotificationShelfManager notificationShelfManager, KeyguardEditModeController keyguardEditModeController, KeyguardClickController keyguardClickController, PluginLockData pluginLockData, Lazy lazy3, Lazy lazy4, LockscreenNotificationManager lockscreenNotificationManager, LockscreenNotificationIconsOnlyController lockscreenNotificationIconsOnlyController, Lazy lazy5, QsStatusEventLog qsStatusEventLog, SelectedUserInteractor selectedUserInteractor, SecQuickSettingsAffordanceInteractor secQuickSettingsAffordanceInteractor, SecQSPanelComposeAdapter secQSPanelComposeAdapter, SecHideNotificationShadeInMirrorInteractor secHideNotificationShadeInMirrorInteractor, PanelPopOverManager panelPopOverManager, SecQsUiDisplayModeInteractor secQsUiDisplayModeInteractor) {
        return new NotificationPanelViewController(dcmMascotViewContainer, pluginLockMediator, notificationPanelView, keyguardTouchAnimator, lazy, notificationWakeUpCoordinator, pulseExpansionHandler, dynamicPrivacyController, keyguardBypassController, falsingManager, falsingCollector, keyguardStateController, statusBarStateController, notificationShadeWindowController, dozeLog, dozeParameters, commandQueue, vibratorHelper, latencyTracker, accessibilityManager, i, keyguardUpdateMonitor, metricsLogger, shadeLogger, configurationController, provider, shadeTouchableRegionManager, conversationNotificationManager, mediaHierarchyManager, statusBarKeyguardViewManager, notificationGutsManager, notificationsQSContainerController, notificationStackScrollLayoutController, keyguardStatusBarViewComponentFactory, lockscreenShadeTransitionController, scrimController, mediaDataManager, notificationShadeDepthController, ambientState, secLockIconViewController, keyguardMediaController, tapAgainViewController, navigationModeController, navigationBarController, quickSettingsControllerImpl, fragmentService, iStatusBarService, shadeHeaderController, screenOffAnimationController, lockscreenGestureLogger, shadeExpansionStateManager, shadeRepository, optional, sysUiState, sysUIStateDisplaysInteractor, provider2, keyguardWallpaperController, wallpaperImageInjectCreator, factory, keyguardUnlockAnimationController, keyguardIndicationController, notificationListContainer, unlockedScreenOffAnimationController, systemClock, keyguardClockInteractor, alternateBouncerInteractor, dreamingToLockscreenTransitionViewModel, coroutineDispatcher, keyguardTransitionInteractor, dumpManager, keyguardTouchHandlingViewModel, wallpaperFocalAreaViewModel, keyguardInteractor, activityStarter, sharedNotificationContainerInteractor, activeNotificationsInteractor, shadeAnimationInteractor, deviceEntryFaceAuthInteractor, splitShadeStateController, powerInteractor, keyguardClockPositionAlgorithm, mSDLPlayer, brightnessMirrorShowingRepository, blurConfig, lazy2, privacyDialogController, factory2, notificationShelfManager, keyguardEditModeController, keyguardClickController, pluginLockData, lazy3, lazy4, lockscreenNotificationManager, lockscreenNotificationIconsOnlyController, lazy5, qsStatusEventLog, selectedUserInteractor, secQuickSettingsAffordanceInteractor, secQSPanelComposeAdapter, secHideNotificationShadeInMirrorInteractor, panelPopOverManager, secQsUiDisplayModeInteractor);
    }

    @Override // javax.inject.Provider
    public final Object get() {
        NotificationPanelViewController notificationPanelViewController = new NotificationPanelViewController((DcmMascotViewContainer) this.mascotViewContainerProvider.get(), (PluginLockMediator) this.pluginLockMediatorProvider.get(), (NotificationPanelView) this.viewProvider.get(), (KeyguardTouchAnimator) this.keyguardTouchAnimatorProvider.get(), DoubleCheck.lazy(this.pluginAODManagerLazyProvider), (NotificationWakeUpCoordinator) this.coordinatorProvider.get(), (PulseExpansionHandler) this.pulseExpansionHandlerProvider.get(), (DynamicPrivacyController) this.dynamicPrivacyControllerProvider.get(), (KeyguardBypassController) this.bypassControllerProvider.get(), (FalsingManager) this.falsingManagerProvider.get(), (FalsingCollector) this.falsingCollectorProvider.get(), (KeyguardStateController) this.keyguardStateControllerProvider.get(), (StatusBarStateController) this.statusBarStateControllerProvider.get(), (NotificationShadeWindowController) this.notificationShadeWindowControllerProvider.get(), (DozeLog) this.dozeLogProvider.get(), (DozeParameters) this.dozeParametersProvider.get(), (CommandQueue) this.commandQueueProvider.get(), (VibratorHelper) this.vibratorHelperProvider.get(), (LatencyTracker) this.latencyTrackerProvider.get(), (AccessibilityManager) this.accessibilityManagerProvider.get(), ((Integer) this.displayIdProvider.get()).intValue(), (KeyguardUpdateMonitor) this.keyguardUpdateMonitorProvider.get(), (MetricsLogger) this.metricsLoggerProvider.get(), (ShadeLogger) this.shadeLoggerProvider.get(), (ConfigurationController) this.configurationControllerProvider.get(), this.flingAnimationUtilsBuilderProvider, (ShadeTouchableRegionManager) this.shadeTouchableRegionManagerProvider.get(), (ConversationNotificationManager) this.conversationNotificationManagerProvider.get(), (MediaHierarchyManager) this.mediaHierarchyManagerProvider.get(), (StatusBarKeyguardViewManager) this.statusBarKeyguardViewManagerProvider.get(), (NotificationGutsManager) this.gutsManagerProvider.get(), (NotificationsQSContainerController) this.notificationsQSContainerControllerProvider.get(), (NotificationStackScrollLayoutController) this.notificationStackScrollLayoutControllerProvider.get(), (KeyguardStatusBarViewComponent.Factory) this.keyguardStatusBarViewComponentFactoryProvider.get(), (LockscreenShadeTransitionController) this.lockscreenShadeTransitionControllerProvider.get(), (ScrimController) this.scrimControllerProvider.get(), (MediaDataManager) this.mediaDataManagerProvider.get(), (NotificationShadeDepthController) this.notificationShadeDepthControllerProvider.get(), (AmbientState) this.ambientStateProvider.get(), (SecLockIconViewController) this.lockIconViewControllerProvider.get(), (KeyguardMediaController) this.keyguardMediaControllerProvider.get(), (TapAgainViewController) this.tapAgainViewControllerProvider.get(), (NavigationModeController) this.navigationModeControllerProvider.get(), (NavigationBarController) this.navigationBarControllerProvider.get(), (QuickSettingsControllerImpl) this.quickSettingsControllerProvider.get(), (FragmentService) this.fragmentServiceProvider.get(), (IStatusBarService) this.statusBarServiceProvider.get(), (ShadeHeaderController) this.shadeHeaderControllerProvider.get(), (ScreenOffAnimationController) this.screenOffAnimationControllerProvider.get(), (LockscreenGestureLogger) this.lockscreenGestureLoggerProvider.get(), (ShadeExpansionStateManager) this.shadeExpansionStateManagerProvider.get(), (ShadeRepository) this.shadeRepositoryProvider.get(), (Optional) this.unfoldComponentProvider.get(), (SysUiState) this.sysUiStateProvider.get(), (SysUIStateDisplaysInteractor) this.sysUIStateDisplaysInteractorProvider.get(), this.keyguardSecBottomAreaViewControllerProvider, (KeyguardWallpaperController) this.keyguardWallpaperControllerProvider.get(), (WallpaperImageInjectCreator) this.wallpaperImageCreatorProvider.get(), (EmergencyButtonController.Factory) this.emergencyButtonControllerFactoryProvider.get(), (KeyguardUnlockAnimationController) this.keyguardUnlockAnimationControllerProvider.get(), (KeyguardIndicationController) this.keyguardIndicationControllerProvider.get(), (NotificationListContainer) this.notificationListContainerProvider.get(), (UnlockedScreenOffAnimationController) this.unlockedScreenOffAnimationControllerProvider.get(), (SystemClock) this.systemClockProvider.get(), (KeyguardClockInteractor) this.keyguardClockInteractorProvider.get(), (AlternateBouncerInteractor) this.alternateBouncerInteractorProvider.get(), (DreamingToLockscreenTransitionViewModel) this.dreamingToLockscreenTransitionViewModelProvider.get(), (CoroutineDispatcher) this.mainDispatcherProvider.get(), (KeyguardTransitionInteractor) this.keyguardTransitionInteractorProvider.get(), (DumpManager) this.dumpManagerProvider.get(), (KeyguardTouchHandlingViewModel) this.keyguardTouchHandlingViewModelProvider.get(), (WallpaperFocalAreaViewModel) this.wallpaperFocalAreaViewModelProvider.get(), (KeyguardInteractor) this.keyguardInteractorProvider.get(), (ActivityStarter) this.activityStarterProvider.get(), (SharedNotificationContainerInteractor) this.sharedNotificationContainerInteractorProvider.get(), (ActiveNotificationsInteractor) this.activeNotificationsInteractorProvider.get(), (ShadeAnimationInteractor) this.shadeAnimationInteractorProvider.get(), (DeviceEntryFaceAuthInteractor) this.deviceEntryFaceAuthInteractorProvider.get(), (SplitShadeStateController) this.splitShadeStateControllerProvider.get(), (PowerInteractor) this.powerInteractorProvider.get(), (KeyguardClockPositionAlgorithm) this.keyguardClockPositionAlgorithmProvider.get(), (MSDLPlayer) this.msdlPlayerProvider.get(), (BrightnessMirrorShowingRepository) this.brightnessMirrorShowingRepositoryProvider.get(), (BlurConfig) this.blurConfigProvider.get(), DoubleCheck.lazy(this.shadeDisplaysRepositoryProvider), (PrivacyDialogController) this.privacyDialogControllerProvider.get(), (KeyguardPunchHoleVIViewController.Factory) this.punchHoleVIViewControllerFactoryProvider.get(), (NotificationShelfManager) this.notificationShelfManagerProvider.get(), (KeyguardEditModeController) this.editModeControllerProvider.get(), (KeyguardClickController) this.keyguardClickControllerProvider.get(), (PluginLockData) this.pluginLockDataProvider.get(), DoubleCheck.lazy(this.pluginLockStarManagerLazyProvider), DoubleCheck.lazy(this.samsungBarExtProvider), (LockscreenNotificationManager) this.lockscreenNotificationManagerProvider.get(), (LockscreenNotificationIconsOnlyController) this.lockscreenNotificationIconsOnlyControllerProvider.get(), DoubleCheck.lazy(this.dataUsageLabelManagerLazyProvider), (QsStatusEventLog) this.qsStatusEventLogProvider.get(), (SelectedUserInteractor) this.selectedUserInteractorProvider.get(), (SecQuickSettingsAffordanceInteractor) this.secQuickSettingsAffordanceInteractorProvider.get(), (SecQSPanelComposeAdapter) this.qsPanelComposeProvider.get(), (SecHideNotificationShadeInMirrorInteractor) this.hideNotificationShadeInMirrorInteractorProvider.get(), (PanelPopOverManager) this.panelPopOverManagerProvider.get(), (SecQsUiDisplayModeInteractor) this.secQsUiDisplayModeInteractorProvider.get());
        notificationPanelViewController.mBioUnlockControllerLazy = DoubleCheck.lazy(this.mBioUnlockControllerLazyProvider);
        return notificationPanelViewController;
    }
}
