package com.android.systemui.statusbar.phone;

import android.app.WallpaperManager;
import android.content.Context;
import android.hardware.devicestate.DeviceStateManager;
import android.os.Handler;
import android.os.PowerManager;
import android.service.dreams.IDreamManager;
import android.util.DisplayMetrics;
import android.view.WindowManager;
import com.android.internal.logging.MetricsLogger;
import com.android.keyguard.KeyguardUpdateMonitor;
import com.android.keyguard.ViewMediatorCallback;
import com.android.systemui.InitController;
import com.android.systemui.accessibility.floatingmenu.AccessibilityFloatingMenuController;
import com.android.systemui.aiagent.AiAgentEffect;
import com.android.systemui.animation.ActivityTransitionAnimator;
import com.android.systemui.back.domain.interactor.BackActionInteractor;
import com.android.systemui.biometrics.AuthRippleController;
import com.android.systemui.bixby2.SystemUICommandActionHandler;
import com.android.systemui.blur.SecQpBlurController;
import com.android.systemui.bouncer.domain.interactor.AlternateBouncerInteractor;
import com.android.systemui.broadcast.BroadcastDispatcher;
import com.android.systemui.charging.WiredChargingRippleController;
import com.android.systemui.classifier.FalsingCollector;
import com.android.systemui.colorextraction.SysuiColorExtractor;
import com.android.systemui.communal.domain.interactor.CommunalInteractor;
import com.android.systemui.demomode.DemoModeController;
import com.android.systemui.emergency.EmergencyGestureModule;
import com.android.systemui.emergency.EmergencyGestureModule$emergencyGestureIntentFactory$1;
import com.android.systemui.flags.FeatureFlags;
import com.android.systemui.fragments.FragmentService;
import com.android.systemui.keyguard.DisplayLifecycle;
import com.android.systemui.keyguard.KeyguardFastBioUnlockController;
import com.android.systemui.keyguard.KeyguardFoldController;
import com.android.systemui.keyguard.KeyguardUnlockAnimationController;
import com.android.systemui.keyguard.KeyguardViewMediator;
import com.android.systemui.keyguard.ScreenLifecycle;
import com.android.systemui.keyguard.WakefulnessLifecycle;
import com.android.systemui.mdm.MdmOverlayContainer;
import com.android.systemui.media.NotificationMediaManager;
import com.android.systemui.navigationbar.NavigationBarController;
import com.android.systemui.plugins.ActivityStarter;
import com.android.systemui.plugins.FalsingManager;
import com.android.systemui.plugins.PluginDependencyProvider;
import com.android.systemui.plugins.PluginManager;
import com.android.systemui.power.domain.interactor.PowerInteractor;
import com.android.systemui.scene.domain.interactor.WindowRootViewVisibilityInteractor;
import com.android.systemui.settings.UserTracker;
import com.android.systemui.settings.brightness.BrightnessSliderController;
import com.android.systemui.settings.brightness.data.repository.BrightnessMirrorShowingRepository;
import com.android.systemui.shade.GlanceableHubContainerController;
import com.android.systemui.shade.QuickSettingsController;
import com.android.systemui.shade.ShadeController;
import com.android.systemui.shade.ShadeExpansionStateManager;
import com.android.systemui.shade.ShadeLogger;
import com.android.systemui.shade.ShadeSurface;
import com.android.systemui.statusbar.CommandQueue;
import com.android.systemui.statusbar.KeyguardIndicationController;
import com.android.systemui.statusbar.LightRevealScrim;
import com.android.systemui.statusbar.LockscreenShadeTransitionController;
import com.android.systemui.statusbar.NotificationLockscreenUserManager;
import com.android.systemui.statusbar.NotificationRemoteInputManager;
import com.android.systemui.statusbar.NotificationShadeWindowController;
import com.android.systemui.statusbar.PulseExpansionHandler;
import com.android.systemui.statusbar.SecLightRevealScrimHelper;
import com.android.systemui.statusbar.SysuiStatusBarStateController;
import com.android.systemui.statusbar.core.StatusBarInitializer;
import com.android.systemui.statusbar.data.repository.StatusBarModeRepositoryStore;
import com.android.systemui.statusbar.notification.NotificationLaunchAnimatorControllerProvider;
import com.android.systemui.statusbar.notification.NotificationWakeUpCoordinator;
import com.android.systemui.statusbar.notification.collection.notifcollection.CommonNotifCollection;
import com.android.systemui.statusbar.notification.headsup.HeadsUpManager;
import com.android.systemui.statusbar.notification.init.NotificationsController;
import com.android.systemui.statusbar.notification.row.NotifRemoteViewCache;
import com.android.systemui.statusbar.notification.row.NotificationGutsManager;
import com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayoutController;
import com.android.systemui.statusbar.phone.ongoingactivity.OngoingActivityController;
import com.android.systemui.statusbar.policy.BatteryController;
import com.android.systemui.statusbar.policy.ConfigurationController;
import com.android.systemui.statusbar.policy.DeviceProvisionedController;
import com.android.systemui.statusbar.policy.ExtensionController;
import com.android.systemui.statusbar.policy.KeyguardStateController;
import com.android.systemui.statusbar.policy.UserInfoControllerImpl;
import com.android.systemui.statusbar.window.StatusBarWindowControllerStore;
import com.android.systemui.statusbar.window.StatusBarWindowStateController;
import com.android.systemui.subscreen.SubScreenManager;
import com.android.systemui.util.WallpaperController;
import com.android.systemui.util.concurrency.DelayableExecutor;
import com.android.systemui.util.concurrency.MessageRouter;
import com.android.systemui.util.kotlin.JavaAdapter;
import com.android.systemui.utils.windowmanager.WindowManagerProvider;
import com.android.systemui.volume.VolumeComponent;
import com.android.systemui.wallet.controller.QuickAccessWalletController;
import dagger.Lazy;
import dagger.internal.DoubleCheck;
import dagger.internal.Provider;
import java.util.Optional;
import java.util.concurrent.Executor;

/* loaded from: classes3.dex */
public final class CentralSurfacesImpl_Factory implements Provider {
    public final Provider accessibilityFloatingMenuControllerProvider;
    public final Provider activityStarterProvider;
    public final Provider activityTransitionAnimatorProvider;
    public final Provider aiAgentEffectProvider;
    public final Provider alternateBouncerInteractorProvider;
    public final Provider assistManagerLazyProvider;
    public final Provider authRippleControllerProvider;
    public final Provider autoHideControllerProvider;
    public final Provider backActionInteractorProvider;
    public final Provider batteryControllerProvider;
    public final Provider biometricUnlockControllerLazyProvider;
    public final Provider blurControllerProvider;
    public final Provider brightnessMirrorShowingRepositoryProvider;
    public final Provider brightnessSliderFactoryProvider;
    public final Provider broadcastDispatcherProvider;
    public final Provider bubblesOptionalProvider;
    public final Provider cameraLauncherLazyProvider;
    public final Provider colorExtractorProvider;
    public final Provider commandQueueCallbacksLazyProvider;
    public final Provider commandQueueProvider;
    public final Provider communalInteractorProvider;
    public final Provider configurationControllerProvider;
    public final Provider contextProvider;
    public final Provider coverHostLazyProvider;
    public final Provider delayableExecutorProvider;
    public final Provider demoModeControllerProvider;
    public final Provider deviceProvisionedControllerProvider;
    public final Provider deviceStateManagerProvider;
    public final Provider displayLifecycleProvider;
    public final Provider displayMetricsProvider;
    public final Provider dozeParametersProvider;
    public final Provider dozeScrimControllerProvider;
    public final Provider dozeServiceHostProvider;
    public final Provider dreamManagerProvider;
    public final Provider emergencyGestureIntentFactoryProvider;
    public final Provider extensionControllerProvider;
    public final Provider falsingCollectorProvider;
    public final Provider falsingManagerProvider;
    public final Provider featureFlagsProvider;
    public final Provider fragmentServiceProvider;
    public final Provider glanceableHubContainerControllerProvider;
    public final Provider headsUpManagerProvider;
    public final Provider initControllerProvider;
    public final Provider javaAdapterProvider;
    public final Provider keyguardBypassControllerProvider;
    public final Provider keyguardFoldControllerProvider;
    public final Provider keyguardIndicationControllerProvider;
    public final Provider keyguardStateControllerProvider;
    public final Provider keyguardUnlockAnimationControllerProvider;
    public final Provider keyguardUpdateMonitorProvider;
    public final Provider keyguardViewMediatorProvider;
    public final Provider lightBarControllerProvider;
    public final Provider lightRevealScrimProvider;
    public final Provider lightRevealScrimViewModelLazyProvider;
    public final Provider lockScreenUserManagerProvider;
    public final Provider lockscreenShadeTransitionControllerProvider;
    public final Provider mKeyguardFastBioUnlockControllerProvider;
    public final Provider mSecLightRevealScrimHelperProvider;
    public final Provider mainHandlerProvider;
    public final Provider mdmOverlayContainerProvider;
    public final Provider messageRouterProvider;
    public final Provider metricsLoggerProvider;
    public final Provider navBarHelperLazyProvider;
    public final Provider navigationBarControllerProvider;
    public final Provider noteTaskControllerLazyProvider;
    public final Provider notifCollectionProvider;
    public final Provider notifRemoteViewCacheProvider;
    public final Provider notifTransitionAnimatorControllerProvider;
    public final Provider notificationActivityStarterLazyProvider;
    public final Provider notificationGutsManagerProvider;
    public final Provider notificationIconAreaControllerProvider;
    public final Provider notificationMediaManagerProvider;
    public final Provider notificationPresenterLazyProvider;
    public final Provider notificationShadeDepthControllerLazyProvider;
    public final Provider notificationShadeWindowControllerProvider;
    public final Provider notificationShadeWindowViewControllerLazyProvider;
    public final Provider notificationStackScrollLayoutControllerProvider;
    public final Provider notificationWakeUpCoordinatorProvider;
    public final Provider notificationsControllerProvider;
    public final Provider ongoingActivityControllerProvider;
    public final Provider phoneStatusBarPolicyProvider;
    public final Provider pluginDependencyProvider;
    public final Provider pluginManagerProvider;
    public final Provider powerInteractorProvider;
    public final Provider powerManagerProvider;
    public final Provider pulseExpansionHandlerProvider;
    public final Provider quickSettingsControllerProvider;
    public final Provider remoteInputManagerProvider;
    public final Provider screenLifecycleProvider;
    public final Provider screenOffAnimationControllerProvider;
    public final Provider scrimControllerProvider;
    public final Provider shadeControllerProvider;
    public final Provider shadeExpansionStateManagerProvider;
    public final Provider shadeLoggerProvider;
    public final Provider shadeSurfaceProvider;
    public final Provider startingSurfaceOptionalProvider;
    public final Provider statusBarHideIconsForBouncerManagerProvider;
    public final Provider statusBarInitializerProvider;
    public final Provider statusBarKeyguardViewManagerProvider;
    public final Provider statusBarModeRepositoryProvider;
    public final Provider statusBarSignalPolicyProvider;
    public final Provider statusBarStateControllerProvider;
    public final Provider statusBarTouchableRegionManagerProvider;
    public final Provider statusBarWindowControllerStoreProvider;
    public final Provider statusBarWindowStateControllerProvider;
    public final Provider subScreenManagerProvider;
    public final Provider swBlueLightFilterTileLazyProvider;
    public final Provider systemUICommandActionHandlerProvider;
    public final Provider timeTickHandlerProvider;
    public final Provider uiBgExecutorProvider;
    public final Provider userInfoControllerImplProvider;
    public final Provider userTrackerProvider;
    public final Provider viewMediatorCallbackProvider;
    public final Provider volumeComponentProvider;
    public final Provider wakefulnessLifecycleProvider;
    public final Provider walletControllerProvider;
    public final Provider wallpaperControllerProvider;
    public final Provider wallpaperManagerProvider;
    public final Provider windowManagerProvider;
    public final Provider windowManagerProvider2;
    public final Provider windowRootViewVisibilityInteractorProvider;
    public final Provider wiredChargingRippleControllerProvider;

    public CentralSurfacesImpl_Factory(Provider provider, Provider provider2, Provider provider3, Provider provider4, Provider provider5, Provider provider6, Provider provider7, Provider provider8, Provider provider9, Provider provider10, Provider provider11, Provider provider12, Provider provider13, Provider provider14, Provider provider15, Provider provider16, Provider provider17, Provider provider18, Provider provider19, Provider provider20, Provider provider21, Provider provider22, Provider provider23, Provider provider24, Provider provider25, Provider provider26, Provider provider27, Provider provider28, Provider provider29, Provider provider30, Provider provider31, Provider provider32, Provider provider33, Provider provider34, Provider provider35, Provider provider36, Provider provider37, Provider provider38, Provider provider39, Provider provider40, Provider provider41, Provider provider42, Provider provider43, Provider provider44, Provider provider45, Provider provider46, Provider provider47, Provider provider48, Provider provider49, Provider provider50, Provider provider51, Provider provider52, Provider provider53, Provider provider54, Provider provider55, Provider provider56, Provider provider57, Provider provider58, Provider provider59, Provider provider60, Provider provider61, Provider provider62, Provider provider63, Provider provider64, Provider provider65, Provider provider66, Provider provider67, Provider provider68, Provider provider69, Provider provider70, Provider provider71, Provider provider72, Provider provider73, Provider provider74, Provider provider75, Provider provider76, Provider provider77, Provider provider78, Provider provider79, Provider provider80, Provider provider81, Provider provider82, Provider provider83, Provider provider84, Provider provider85, Provider provider86, Provider provider87, Provider provider88, Provider provider89, Provider provider90, Provider provider91, Provider provider92, Provider provider93, Provider provider94, Provider provider95, Provider provider96, Provider provider97, Provider provider98, Provider provider99, Provider provider100, Provider provider101, Provider provider102, Provider provider103, Provider provider104, Provider provider105, Provider provider106, Provider provider107, Provider provider108, Provider provider109, Provider provider110, Provider provider111, Provider provider112, Provider provider113, Provider provider114, Provider provider115, Provider provider116, Provider provider117, Provider provider118, Provider provider119, Provider provider120, Provider provider121, Provider provider122) {
        this.mdmOverlayContainerProvider = provider;
        this.coverHostLazyProvider = provider2;
        this.systemUICommandActionHandlerProvider = provider3;
        this.displayLifecycleProvider = provider4;
        this.subScreenManagerProvider = provider5;
        this.contextProvider = provider6;
        this.notificationsControllerProvider = provider7;
        this.fragmentServiceProvider = provider8;
        this.lightBarControllerProvider = provider9;
        this.autoHideControllerProvider = provider10;
        this.statusBarInitializerProvider = provider11;
        this.statusBarWindowControllerStoreProvider = provider12;
        this.statusBarWindowStateControllerProvider = provider13;
        this.statusBarModeRepositoryProvider = provider14;
        this.keyguardUpdateMonitorProvider = provider15;
        this.statusBarSignalPolicyProvider = provider16;
        this.pulseExpansionHandlerProvider = provider17;
        this.notificationWakeUpCoordinatorProvider = provider18;
        this.keyguardBypassControllerProvider = provider19;
        this.keyguardStateControllerProvider = provider20;
        this.headsUpManagerProvider = provider21;
        this.falsingManagerProvider = provider22;
        this.falsingCollectorProvider = provider23;
        this.broadcastDispatcherProvider = provider24;
        this.notificationGutsManagerProvider = provider25;
        this.shadeExpansionStateManagerProvider = provider26;
        this.keyguardViewMediatorProvider = provider27;
        this.displayMetricsProvider = provider28;
        this.metricsLoggerProvider = provider29;
        this.shadeLoggerProvider = provider30;
        this.javaAdapterProvider = provider31;
        this.uiBgExecutorProvider = provider32;
        this.shadeSurfaceProvider = provider33;
        this.notificationMediaManagerProvider = provider34;
        this.lockScreenUserManagerProvider = provider35;
        this.remoteInputManagerProvider = provider36;
        this.quickSettingsControllerProvider = provider37;
        this.batteryControllerProvider = provider38;
        this.colorExtractorProvider = provider39;
        this.screenLifecycleProvider = provider40;
        this.wakefulnessLifecycleProvider = provider41;
        this.powerInteractorProvider = provider42;
        this.communalInteractorProvider = provider43;
        this.statusBarStateControllerProvider = provider44;
        this.bubblesOptionalProvider = provider45;
        this.noteTaskControllerLazyProvider = provider46;
        this.deviceProvisionedControllerProvider = provider47;
        this.navigationBarControllerProvider = provider48;
        this.accessibilityFloatingMenuControllerProvider = provider49;
        this.assistManagerLazyProvider = provider50;
        this.configurationControllerProvider = provider51;
        this.notificationShadeWindowControllerProvider = provider52;
        this.notificationShadeWindowViewControllerLazyProvider = provider53;
        this.notificationStackScrollLayoutControllerProvider = provider54;
        this.notificationPresenterLazyProvider = provider55;
        this.notificationActivityStarterLazyProvider = provider56;
        this.notifTransitionAnimatorControllerProvider = provider57;
        this.dozeParametersProvider = provider58;
        this.scrimControllerProvider = provider59;
        this.biometricUnlockControllerLazyProvider = provider60;
        this.authRippleControllerProvider = provider61;
        this.dozeServiceHostProvider = provider62;
        this.backActionInteractorProvider = provider63;
        this.powerManagerProvider = provider64;
        this.dozeScrimControllerProvider = provider65;
        this.volumeComponentProvider = provider66;
        this.commandQueueProvider = provider67;
        this.commandQueueCallbacksLazyProvider = provider68;
        this.pluginManagerProvider = provider69;
        this.shadeControllerProvider = provider70;
        this.windowRootViewVisibilityInteractorProvider = provider71;
        this.statusBarKeyguardViewManagerProvider = provider72;
        this.viewMediatorCallbackProvider = provider73;
        this.initControllerProvider = provider74;
        this.timeTickHandlerProvider = provider75;
        this.pluginDependencyProvider = provider76;
        this.extensionControllerProvider = provider77;
        this.userInfoControllerImplProvider = provider78;
        this.phoneStatusBarPolicyProvider = provider79;
        this.keyguardIndicationControllerProvider = provider80;
        this.demoModeControllerProvider = provider81;
        this.notificationShadeDepthControllerLazyProvider = provider82;
        this.statusBarTouchableRegionManagerProvider = provider83;
        this.notificationIconAreaControllerProvider = provider84;
        this.brightnessSliderFactoryProvider = provider85;
        this.screenOffAnimationControllerProvider = provider86;
        this.wallpaperControllerProvider = provider87;
        this.ongoingActivityControllerProvider = provider88;
        this.statusBarHideIconsForBouncerManagerProvider = provider89;
        this.lockscreenShadeTransitionControllerProvider = provider90;
        this.featureFlagsProvider = provider91;
        this.keyguardUnlockAnimationControllerProvider = provider92;
        this.delayableExecutorProvider = provider93;
        this.messageRouterProvider = provider94;
        this.wallpaperManagerProvider = provider95;
        this.startingSurfaceOptionalProvider = provider96;
        this.activityTransitionAnimatorProvider = provider97;
        this.deviceStateManagerProvider = provider98;
        this.wiredChargingRippleControllerProvider = provider99;
        this.dreamManagerProvider = provider100;
        this.cameraLauncherLazyProvider = provider101;
        this.lightRevealScrimViewModelLazyProvider = provider102;
        this.lightRevealScrimProvider = provider103;
        this.alternateBouncerInteractorProvider = provider104;
        this.userTrackerProvider = provider105;
        this.activityStarterProvider = provider106;
        this.brightnessMirrorShowingRepositoryProvider = provider107;
        this.glanceableHubContainerControllerProvider = provider108;
        this.emergencyGestureIntentFactoryProvider = provider109;
        this.walletControllerProvider = provider110;
        this.windowManagerProvider = provider111;
        this.windowManagerProvider2 = provider112;
        this.blurControllerProvider = provider113;
        this.navBarHelperLazyProvider = provider114;
        this.mainHandlerProvider = provider115;
        this.notifRemoteViewCacheProvider = provider116;
        this.notifCollectionProvider = provider117;
        this.keyguardFoldControllerProvider = provider118;
        this.swBlueLightFilterTileLazyProvider = provider119;
        this.aiAgentEffectProvider = provider120;
        this.mSecLightRevealScrimHelperProvider = provider121;
        this.mKeyguardFastBioUnlockControllerProvider = provider122;
    }

    public static CentralSurfacesImpl newInstance(MdmOverlayContainer mdmOverlayContainer, Lazy lazy, SystemUICommandActionHandler systemUICommandActionHandler, DisplayLifecycle displayLifecycle, SubScreenManager subScreenManager, Context context, NotificationsController notificationsController, FragmentService fragmentService, LightBarController lightBarController, AutoHideController autoHideController, StatusBarInitializer statusBarInitializer, StatusBarWindowControllerStore statusBarWindowControllerStore, StatusBarWindowStateController statusBarWindowStateController, StatusBarModeRepositoryStore statusBarModeRepositoryStore, KeyguardUpdateMonitor keyguardUpdateMonitor, StatusBarSignalPolicy statusBarSignalPolicy, PulseExpansionHandler pulseExpansionHandler, NotificationWakeUpCoordinator notificationWakeUpCoordinator, KeyguardBypassController keyguardBypassController, KeyguardStateController keyguardStateController, HeadsUpManager headsUpManager, FalsingManager falsingManager, FalsingCollector falsingCollector, BroadcastDispatcher broadcastDispatcher, NotificationGutsManager notificationGutsManager, ShadeExpansionStateManager shadeExpansionStateManager, KeyguardViewMediator keyguardViewMediator, DisplayMetrics displayMetrics, MetricsLogger metricsLogger, ShadeLogger shadeLogger, JavaAdapter javaAdapter, Executor executor, ShadeSurface shadeSurface, NotificationMediaManager notificationMediaManager, NotificationLockscreenUserManager notificationLockscreenUserManager, NotificationRemoteInputManager notificationRemoteInputManager, QuickSettingsController quickSettingsController, BatteryController batteryController, SysuiColorExtractor sysuiColorExtractor, ScreenLifecycle screenLifecycle, WakefulnessLifecycle wakefulnessLifecycle, PowerInteractor powerInteractor, CommunalInteractor communalInteractor, SysuiStatusBarStateController sysuiStatusBarStateController, Optional optional, Lazy lazy2, DeviceProvisionedController deviceProvisionedController, NavigationBarController navigationBarController, AccessibilityFloatingMenuController accessibilityFloatingMenuController, Lazy lazy3, ConfigurationController configurationController, NotificationShadeWindowController notificationShadeWindowController, Lazy lazy4, NotificationStackScrollLayoutController notificationStackScrollLayoutController, Lazy lazy5, Lazy lazy6, NotificationLaunchAnimatorControllerProvider notificationLaunchAnimatorControllerProvider, DozeParameters dozeParameters, ScrimController scrimController, Lazy lazy7, AuthRippleController authRippleController, DozeServiceHost dozeServiceHost, BackActionInteractor backActionInteractor, PowerManager powerManager, DozeScrimController dozeScrimController, VolumeComponent volumeComponent, CommandQueue commandQueue, Lazy lazy8, PluginManager pluginManager, ShadeController shadeController, WindowRootViewVisibilityInteractor windowRootViewVisibilityInteractor, StatusBarKeyguardViewManager statusBarKeyguardViewManager, ViewMediatorCallback viewMediatorCallback, InitController initController, Handler handler, PluginDependencyProvider pluginDependencyProvider, ExtensionController extensionController, UserInfoControllerImpl userInfoControllerImpl, PhoneStatusBarPolicy phoneStatusBarPolicy, KeyguardIndicationController keyguardIndicationController, DemoModeController demoModeController, Lazy lazy9, ShadeTouchableRegionManager shadeTouchableRegionManager, NotificationIconAreaController notificationIconAreaController, BrightnessSliderController.BrightnessSliderControllerFactory brightnessSliderControllerFactory, ScreenOffAnimationController screenOffAnimationController, WallpaperController wallpaperController, OngoingActivityController ongoingActivityController, StatusBarHideIconsForBouncerManager statusBarHideIconsForBouncerManager, LockscreenShadeTransitionController lockscreenShadeTransitionController, FeatureFlags featureFlags, KeyguardUnlockAnimationController keyguardUnlockAnimationController, DelayableExecutor delayableExecutor, MessageRouter messageRouter, WallpaperManager wallpaperManager, Optional optional2, ActivityTransitionAnimator activityTransitionAnimator, DeviceStateManager deviceStateManager, WiredChargingRippleController wiredChargingRippleController, IDreamManager iDreamManager, Lazy lazy10, Lazy lazy11, LightRevealScrim lightRevealScrim, AlternateBouncerInteractor alternateBouncerInteractor, UserTracker userTracker, ActivityStarter activityStarter, BrightnessMirrorShowingRepository brightnessMirrorShowingRepository, GlanceableHubContainerController glanceableHubContainerController, EmergencyGestureModule$emergencyGestureIntentFactory$1 emergencyGestureModule$emergencyGestureIntentFactory$1, QuickAccessWalletController quickAccessWalletController, WindowManager windowManager, WindowManagerProvider windowManagerProvider, SecQpBlurController secQpBlurController, Lazy lazy12, Handler handler2, NotifRemoteViewCache notifRemoteViewCache, CommonNotifCollection commonNotifCollection, KeyguardFoldController keyguardFoldController, Lazy lazy13, AiAgentEffect aiAgentEffect) {
        return new CentralSurfacesImpl(mdmOverlayContainer, lazy, systemUICommandActionHandler, displayLifecycle, subScreenManager, context, notificationsController, fragmentService, lightBarController, autoHideController, statusBarInitializer, statusBarWindowControllerStore, statusBarWindowStateController, statusBarModeRepositoryStore, keyguardUpdateMonitor, statusBarSignalPolicy, pulseExpansionHandler, notificationWakeUpCoordinator, keyguardBypassController, keyguardStateController, headsUpManager, falsingManager, falsingCollector, broadcastDispatcher, notificationGutsManager, shadeExpansionStateManager, keyguardViewMediator, displayMetrics, metricsLogger, shadeLogger, javaAdapter, executor, shadeSurface, notificationMediaManager, notificationLockscreenUserManager, notificationRemoteInputManager, quickSettingsController, batteryController, sysuiColorExtractor, screenLifecycle, wakefulnessLifecycle, powerInteractor, communalInteractor, sysuiStatusBarStateController, optional, lazy2, deviceProvisionedController, navigationBarController, accessibilityFloatingMenuController, lazy3, configurationController, notificationShadeWindowController, lazy4, notificationStackScrollLayoutController, lazy5, lazy6, notificationLaunchAnimatorControllerProvider, dozeParameters, scrimController, lazy7, authRippleController, dozeServiceHost, backActionInteractor, powerManager, dozeScrimController, volumeComponent, commandQueue, lazy8, pluginManager, shadeController, windowRootViewVisibilityInteractor, statusBarKeyguardViewManager, viewMediatorCallback, initController, handler, pluginDependencyProvider, extensionController, userInfoControllerImpl, phoneStatusBarPolicy, keyguardIndicationController, demoModeController, lazy9, shadeTouchableRegionManager, notificationIconAreaController, brightnessSliderControllerFactory, screenOffAnimationController, wallpaperController, ongoingActivityController, statusBarHideIconsForBouncerManager, lockscreenShadeTransitionController, featureFlags, keyguardUnlockAnimationController, delayableExecutor, messageRouter, wallpaperManager, optional2, activityTransitionAnimator, deviceStateManager, wiredChargingRippleController, iDreamManager, lazy10, lazy11, lightRevealScrim, alternateBouncerInteractor, userTracker, activityStarter, brightnessMirrorShowingRepository, glanceableHubContainerController, emergencyGestureModule$emergencyGestureIntentFactory$1, quickAccessWalletController, windowManager, windowManagerProvider, secQpBlurController, lazy12, handler2, notifRemoteViewCache, commonNotifCollection, keyguardFoldController, lazy13, aiAgentEffect);
    }

    @Override // javax.inject.Provider
    public final Object get() {
        CentralSurfacesImpl centralSurfacesImpl = new CentralSurfacesImpl((MdmOverlayContainer) this.mdmOverlayContainerProvider.get(), DoubleCheck.lazy(this.coverHostLazyProvider), (SystemUICommandActionHandler) this.systemUICommandActionHandlerProvider.get(), (DisplayLifecycle) this.displayLifecycleProvider.get(), (SubScreenManager) this.subScreenManagerProvider.get(), (Context) this.contextProvider.get(), (NotificationsController) this.notificationsControllerProvider.get(), (FragmentService) this.fragmentServiceProvider.get(), (LightBarController) this.lightBarControllerProvider.get(), (AutoHideController) this.autoHideControllerProvider.get(), (StatusBarInitializer) this.statusBarInitializerProvider.get(), (StatusBarWindowControllerStore) this.statusBarWindowControllerStoreProvider.get(), (StatusBarWindowStateController) this.statusBarWindowStateControllerProvider.get(), (StatusBarModeRepositoryStore) this.statusBarModeRepositoryProvider.get(), (KeyguardUpdateMonitor) this.keyguardUpdateMonitorProvider.get(), (StatusBarSignalPolicy) this.statusBarSignalPolicyProvider.get(), (PulseExpansionHandler) this.pulseExpansionHandlerProvider.get(), (NotificationWakeUpCoordinator) this.notificationWakeUpCoordinatorProvider.get(), (KeyguardBypassController) this.keyguardBypassControllerProvider.get(), (KeyguardStateController) this.keyguardStateControllerProvider.get(), (HeadsUpManager) this.headsUpManagerProvider.get(), (FalsingManager) this.falsingManagerProvider.get(), (FalsingCollector) this.falsingCollectorProvider.get(), (BroadcastDispatcher) this.broadcastDispatcherProvider.get(), (NotificationGutsManager) this.notificationGutsManagerProvider.get(), (ShadeExpansionStateManager) this.shadeExpansionStateManagerProvider.get(), (KeyguardViewMediator) this.keyguardViewMediatorProvider.get(), (DisplayMetrics) this.displayMetricsProvider.get(), (MetricsLogger) this.metricsLoggerProvider.get(), (ShadeLogger) this.shadeLoggerProvider.get(), (JavaAdapter) this.javaAdapterProvider.get(), (Executor) this.uiBgExecutorProvider.get(), (ShadeSurface) this.shadeSurfaceProvider.get(), (NotificationMediaManager) this.notificationMediaManagerProvider.get(), (NotificationLockscreenUserManager) this.lockScreenUserManagerProvider.get(), (NotificationRemoteInputManager) this.remoteInputManagerProvider.get(), (QuickSettingsController) this.quickSettingsControllerProvider.get(), (BatteryController) this.batteryControllerProvider.get(), (SysuiColorExtractor) this.colorExtractorProvider.get(), (ScreenLifecycle) this.screenLifecycleProvider.get(), (WakefulnessLifecycle) this.wakefulnessLifecycleProvider.get(), (PowerInteractor) this.powerInteractorProvider.get(), (CommunalInteractor) this.communalInteractorProvider.get(), (SysuiStatusBarStateController) this.statusBarStateControllerProvider.get(), (Optional) this.bubblesOptionalProvider.get(), DoubleCheck.lazy(this.noteTaskControllerLazyProvider), (DeviceProvisionedController) this.deviceProvisionedControllerProvider.get(), (NavigationBarController) this.navigationBarControllerProvider.get(), (AccessibilityFloatingMenuController) this.accessibilityFloatingMenuControllerProvider.get(), DoubleCheck.lazy(this.assistManagerLazyProvider), (ConfigurationController) this.configurationControllerProvider.get(), (NotificationShadeWindowController) this.notificationShadeWindowControllerProvider.get(), DoubleCheck.lazy(this.notificationShadeWindowViewControllerLazyProvider), (NotificationStackScrollLayoutController) this.notificationStackScrollLayoutControllerProvider.get(), DoubleCheck.lazy(this.notificationPresenterLazyProvider), DoubleCheck.lazy(this.notificationActivityStarterLazyProvider), (NotificationLaunchAnimatorControllerProvider) this.notifTransitionAnimatorControllerProvider.get(), (DozeParameters) this.dozeParametersProvider.get(), (ScrimController) this.scrimControllerProvider.get(), DoubleCheck.lazy(this.biometricUnlockControllerLazyProvider), (AuthRippleController) this.authRippleControllerProvider.get(), (DozeServiceHost) this.dozeServiceHostProvider.get(), (BackActionInteractor) this.backActionInteractorProvider.get(), (PowerManager) this.powerManagerProvider.get(), (DozeScrimController) this.dozeScrimControllerProvider.get(), (VolumeComponent) this.volumeComponentProvider.get(), (CommandQueue) this.commandQueueProvider.get(), DoubleCheck.lazy(this.commandQueueCallbacksLazyProvider), (PluginManager) this.pluginManagerProvider.get(), (ShadeController) this.shadeControllerProvider.get(), (WindowRootViewVisibilityInteractor) this.windowRootViewVisibilityInteractorProvider.get(), (StatusBarKeyguardViewManager) this.statusBarKeyguardViewManagerProvider.get(), (ViewMediatorCallback) this.viewMediatorCallbackProvider.get(), (InitController) this.initControllerProvider.get(), (Handler) this.timeTickHandlerProvider.get(), (PluginDependencyProvider) this.pluginDependencyProvider.get(), (ExtensionController) this.extensionControllerProvider.get(), (UserInfoControllerImpl) this.userInfoControllerImplProvider.get(), (PhoneStatusBarPolicy) this.phoneStatusBarPolicyProvider.get(), (KeyguardIndicationController) this.keyguardIndicationControllerProvider.get(), (DemoModeController) this.demoModeControllerProvider.get(), DoubleCheck.lazy(this.notificationShadeDepthControllerLazyProvider), (ShadeTouchableRegionManager) this.statusBarTouchableRegionManagerProvider.get(), (NotificationIconAreaController) this.notificationIconAreaControllerProvider.get(), (BrightnessSliderController.Factory) this.brightnessSliderFactoryProvider.get(), (ScreenOffAnimationController) this.screenOffAnimationControllerProvider.get(), (WallpaperController) this.wallpaperControllerProvider.get(), (OngoingActivityController) this.ongoingActivityControllerProvider.get(), (StatusBarHideIconsForBouncerManager) this.statusBarHideIconsForBouncerManagerProvider.get(), (LockscreenShadeTransitionController) this.lockscreenShadeTransitionControllerProvider.get(), (FeatureFlags) this.featureFlagsProvider.get(), (KeyguardUnlockAnimationController) this.keyguardUnlockAnimationControllerProvider.get(), (DelayableExecutor) this.delayableExecutorProvider.get(), (MessageRouter) this.messageRouterProvider.get(), (WallpaperManager) this.wallpaperManagerProvider.get(), (Optional) this.startingSurfaceOptionalProvider.get(), (ActivityTransitionAnimator) this.activityTransitionAnimatorProvider.get(), (DeviceStateManager) this.deviceStateManagerProvider.get(), (WiredChargingRippleController) this.wiredChargingRippleControllerProvider.get(), (IDreamManager) this.dreamManagerProvider.get(), DoubleCheck.lazy(this.cameraLauncherLazyProvider), DoubleCheck.lazy(this.lightRevealScrimViewModelLazyProvider), (LightRevealScrim) this.lightRevealScrimProvider.get(), (AlternateBouncerInteractor) this.alternateBouncerInteractorProvider.get(), (UserTracker) this.userTrackerProvider.get(), (ActivityStarter) this.activityStarterProvider.get(), (BrightnessMirrorShowingRepository) this.brightnessMirrorShowingRepositoryProvider.get(), (GlanceableHubContainerController) this.glanceableHubContainerControllerProvider.get(), (EmergencyGestureModule.EmergencyGestureIntentFactory) this.emergencyGestureIntentFactoryProvider.get(), (QuickAccessWalletController) this.walletControllerProvider.get(), (WindowManager) this.windowManagerProvider.get(), (WindowManagerProvider) this.windowManagerProvider2.get(), (SecQpBlurController) this.blurControllerProvider.get(), DoubleCheck.lazy(this.navBarHelperLazyProvider), (Handler) this.mainHandlerProvider.get(), (NotifRemoteViewCache) this.notifRemoteViewCacheProvider.get(), (CommonNotifCollection) this.notifCollectionProvider.get(), (KeyguardFoldController) this.keyguardFoldControllerProvider.get(), DoubleCheck.lazy(this.swBlueLightFilterTileLazyProvider), (AiAgentEffect) this.aiAgentEffectProvider.get());
        centralSurfacesImpl.mSecLightRevealScrimHelper = (SecLightRevealScrimHelper) this.mSecLightRevealScrimHelperProvider.get();
        centralSurfacesImpl.mKeyguardFastBioUnlockController = (KeyguardFastBioUnlockController) this.mKeyguardFastBioUnlockControllerProvider.get();
        return centralSurfacesImpl;
    }
}
