package com.android.keyguard;

public enum KeyguardConstants$KeyguardDismissActionType {
    KEYGUARD_DISMISS_ACTION_DEFAULT,
    KEYGUARD_DISMISS_ACTION_SHUTDOWN,
    KEYGUARD_DISMISS_ACTION_REBOOT,
    KEYGUARD_DISMISS_ACTION_FINGERPRINT_ERROR
}
