package com.android.systemui;

import android.app.INotificationManager;
import android.content.Context;
import android.content.pm.LauncherApps;
import android.content.res.Resources;
import android.hardware.SensorPrivacyManager;
import android.os.Handler;
import android.os.HandlerThread;
import android.util.ArrayMap;
import android.util.Log;
import com.android.internal.logging.MetricsLogger;
import com.android.internal.logging.UiEventLogger;
import com.android.keyguard.KeyguardUpdateMonitor;
import com.android.keyguard.SecRotationWatcher;
import com.android.systemui.aibrief.AiBriefManager;
import com.android.systemui.animation.DialogTransitionAnimator;
import com.android.systemui.assist.AssistManager;
import com.android.systemui.audio.soundcraft.interfaces.volume.VolumeManager;
import com.android.systemui.basic.util.CoverUtilWrapper;
import com.android.systemui.blur.SecQpBlurController;
import com.android.systemui.broadcast.BroadcastDispatcher;
import com.android.systemui.cover.CoverScreenManager;
import com.android.systemui.dagger.DaggerReferenceGlobalRootComponent;
import com.android.systemui.dagger.GlobalRootComponent;
import com.android.systemui.dagger.ReferenceGlobalRootComponent;
import com.android.systemui.dagger.ReferenceSysUIComponent;
import com.android.systemui.dagger.SysUIComponent;
import com.android.systemui.doze.PluginAODManager;
import com.android.systemui.facewidget.plugin.ExternalClockProvider;
import com.android.systemui.facewidget.plugin.FaceWidgetPluginControllerImpl;
import com.android.systemui.facewidget.plugin.PluginFaceWidgetManager;
import com.android.systemui.flags.FeatureFlags;
import com.android.systemui.fragments.FragmentService;
import com.android.systemui.globalactions.GlobalActionsComponent;
import com.android.systemui.indexsearch.SystemUIIndexMediator;
import com.android.systemui.keyguard.DisplayLifecycle;
import com.android.systemui.keyguard.KeyguardFastBioUnlockController;
import com.android.systemui.keyguard.KeyguardFoldController;
import com.android.systemui.keyguard.KeyguardVisibilityMonitor;
import com.android.systemui.keyguard.WakefulnessLifecycle;
import com.android.systemui.knox.KnoxStateMonitor;
import com.android.systemui.lockstar.PluginLockStarManager;
import com.android.systemui.log.QuickPanelExternalLogger;
import com.android.systemui.logging.NotiCinemaLogger;
import com.android.systemui.logging.PanelScreenShotBufferLogger;
import com.android.systemui.media.NotificationMediaManager;
import com.android.systemui.media.SecMediaHost;
import com.android.systemui.media.SubscreenMusicWidgetController;
import com.android.systemui.model.SysUiState;
import com.android.systemui.navigationbar.NavigationBarController;
import com.android.systemui.navigationbar.NavigationModeController;
import com.android.systemui.navigationbar.TaskbarDelegate;
import com.android.systemui.navigationbar.store.NavBarStore;
import com.android.systemui.notification.FullExpansionPanelNotiAlphaController;
import com.android.systemui.notification.NotificationBackupRestoreManager;
import com.android.systemui.people.widget.PeopleSpaceWidgetManager;
import com.android.systemui.pluginlock.PluginLockManager;
import com.android.systemui.pluginlock.PluginWallpaperManager;
import com.android.systemui.plugins.ActivityStarter;
import com.android.systemui.plugins.DarkIconDispatcher;
import com.android.systemui.plugins.FalsingManager;
import com.android.systemui.plugins.PluginManager;
import com.android.systemui.plugins.VolumeDialogController;
import com.android.systemui.plugins.statusbar.StatusBarStateController;
import com.android.systemui.privacy.PrivacyDialogController;
import com.android.systemui.qp.SubscreenQsPanelController;
import com.android.systemui.qp.util.SubscreenUtil;
import com.android.systemui.qs.QSBackupRestoreManager;
import com.android.systemui.qs.SecQSCoverResourcePicker;
import com.android.systemui.qs.SecQSDetailController;
import com.android.systemui.qs.SecQSPanelResourcePicker;
import com.android.systemui.qs.SecSTQuickControlRequestReceiver;
import com.android.systemui.qs.bar.ColoredBGHelper;
import com.android.systemui.recents.LauncherProxyService;
import com.android.systemui.searcle.SearcleManager;
import com.android.systemui.settings.UserContextProvider;
import com.android.systemui.settings.UserTracker;
import com.android.systemui.settings.multisim.MultiSIMController;
import com.android.systemui.shade.QuickSettingsController;
import com.android.systemui.shade.SecPanelSplitHelper;
import com.android.systemui.shade.SecPanelTouchBlockHelper;
import com.android.systemui.shade.ShadeController;
import com.android.systemui.shade.ShadeHeaderController;
import com.android.systemui.shade.SplitStateInteractor;
import com.android.systemui.shade.data.repository.ShadeRepository;
import com.android.systemui.shade.domain.interactor.SecNotificationShadeWindowStateInteractor;
import com.android.systemui.shade.domain.interactor.SecPanelExpansionStateInteractor;
import com.android.systemui.shade.domain.interactor.SecPanelSAStatusLogInteractor;
import com.android.systemui.shade.domain.interactor.SecPanelTouchProximityInteractor;
import com.android.systemui.shade.domain.interactor.SecQSExpansionStateInteractor;
import com.android.systemui.shade.domain.interactor.SecQuickSettingsAffordanceInteractor;
import com.android.systemui.statusbar.CommandQueue;
import com.android.systemui.statusbar.KeyguardShortcutManager;
import com.android.systemui.statusbar.NotificationLockscreenUserManager;
import com.android.systemui.statusbar.NotificationShelfManager;
import com.android.systemui.statusbar.VibratorHelper;
import com.android.systemui.statusbar.connectivity.NetworkController;
import com.android.systemui.statusbar.domain.interactor.SecStatusBarWindowViewTouchedInteractor;
import com.android.systemui.statusbar.notification.AllowedOngoingActivityListManager;
import com.android.systemui.statusbar.notification.AssistantFeedbackController;
import com.android.systemui.statusbar.notification.SubscreenNotificationController;
import com.android.systemui.statusbar.notification.collection.NotifCollection;
import com.android.systemui.statusbar.notification.collection.NotifLiveDataStore;
import com.android.systemui.statusbar.notification.collection.provider.HighPriorityProvider;
import com.android.systemui.statusbar.notification.collection.render.GroupExpansionManager;
import com.android.systemui.statusbar.notification.collection.render.GroupMembershipManager;
import com.android.systemui.statusbar.notification.headsup.HeadsUpManager;
import com.android.systemui.statusbar.notification.row.ChannelEditorDialogController;
import com.android.systemui.statusbar.notification.row.NotificationGutsManager;
import com.android.systemui.statusbar.notification.row.OnUserInteractionCallback;
import com.android.systemui.statusbar.notification.stack.AmbientState;
import com.android.systemui.statusbar.notification.stack.NotificationSectionsManager;
import com.android.systemui.statusbar.phone.CentralSurfaces;
import com.android.systemui.statusbar.phone.LightBarController;
import com.android.systemui.statusbar.phone.QSScrimViewSwitch;
import com.android.systemui.statusbar.phone.ScreenOffAnimationController;
import com.android.systemui.statusbar.phone.SecUnlockedScreenOffAnimationHelper;
import com.android.systemui.statusbar.phone.SystemUIDialogManager;
import com.android.systemui.statusbar.phone.nio.KeyguardStatusBarNioLayoutRepository;
import com.android.systemui.statusbar.phone.ui.StatusBarIconController;
import com.android.systemui.statusbar.policy.AppLockNotificationController;
import com.android.systemui.statusbar.policy.BluetoothController;
import com.android.systemui.statusbar.policy.ConfigurationController;
import com.android.systemui.statusbar.policy.DeviceProvisionedController;
import com.android.systemui.statusbar.policy.FlashlightController;
import com.android.systemui.statusbar.policy.KeyguardStateController;
import com.android.systemui.statusbar.policy.QSClockBellTower;
import com.android.systemui.statusbar.policy.RotationLockController;
import com.android.systemui.statusbar.policy.SensitiveNotificationProtectionController;
import com.android.systemui.statusbar.policy.UserInfoController;
import com.android.systemui.statusbar.policy.UserSwitcherController;
import com.android.systemui.statusbar.window.StatusBarWindowControllerStore;
import com.android.systemui.subscreen.SubScreenManager;
import com.android.systemui.tuner.TunerService;
import com.android.systemui.uithreadmonitor.LooperSlowLogController;
import com.android.systemui.user.domain.interactor.SelectedUserInteractor;
import com.android.systemui.user.domain.interactor.UserSwitcherInteractor;
import com.android.systemui.util.DesktopManager;
import com.android.systemui.util.InitializationChecker;
import com.android.systemui.util.QsResetSettingsManager;
import com.android.systemui.util.SecQsUiDisplayModeInteractor;
import com.android.systemui.util.SettingsHelper;
import com.android.systemui.wallpaper.PluginWallpaperController;
import com.android.systemui.wallpaper.WallpaperChangeNotifier;
import com.android.systemui.wallpaper.WallpaperEventNotifier;
import com.android.wm.shell.appzoomout.AppZoomOutController;
import com.android.wm.shell.back.BackAnimationController;
import com.android.wm.shell.bubbles.Bubbles;
import com.android.wm.shell.common.DisplayController;
import com.android.wm.shell.compatui.coverlauncher.CoverLauncherAppCompatStartController;
import com.android.wm.shell.dagger.WMComponent;
import com.android.wm.shell.dagger.WMShellConcurrencyModule;
import com.android.wm.shell.desktopmode.DesktopMode;
import com.android.wm.shell.keyguard.KeyguardTransitions;
import com.android.wm.shell.onehanded.OneHanded;
import com.android.wm.shell.pip.Pip;
import com.android.wm.shell.recents.RecentTasks;
import com.android.wm.shell.shared.ShellTransitions;
import com.android.wm.shell.splitscreen.EnterSplitGestureHandler;
import com.android.wm.shell.splitscreen.SplitScreen;
import com.android.wm.shell.splitscreen.SplitScreenController;
import com.android.wm.shell.startingsurface.StartingWindowController;
import com.android.wm.shell.sysui.ShellInterface;
import com.android.wm.shell.taskview.TaskViewFactoryController;
import com.samsung.systemui.splugins.SPluginDependencyProvider;
import com.samsung.systemui.splugins.SPluginManager;
import dagger.Lazy;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.ExecutionException;
import noticolorpicker.NotificationColorPicker;

/* loaded from: classes.dex */
public abstract class SystemUIInitializer {
    private static final String TAG = "SystemUIFactory";
    private final Context mContext;
    private InitializationChecker mInitializationChecker;
    private GlobalRootComponent mRootComponent;
    private SysUIComponent mSysUIComponent;
    private WMComponent mWMComponent;

    public static void $r8$lambda$QYvDnW0XyzgDh_C_u5znA3aE5Nk(SystemUIInitializer systemUIInitializer, WMComponent.Builder builder, HandlerThread handlerThread) {
        DaggerReferenceGlobalRootComponent.WMComponentBuilder wMComponentBuilder = (DaggerReferenceGlobalRootComponent.WMComponentBuilder) builder;
        wMComponentBuilder.setShellMainThread = handlerThread;
        systemUIInitializer.mWMComponent = wMComponentBuilder.build();
    }

    public SystemUIInitializer(Context context) {
        this.mContext = context;
    }

    public abstract GlobalRootComponent.Builder getGlobalRootComponentBuilder();

    public GlobalRootComponent getRootComponent() {
        return this.mRootComponent;
    }

    public SysUIComponent getSysUIComponent() {
        return this.mSysUIComponent;
    }

    public String getVendorComponent(Resources resources) {
        return resources.getString(R.string.config_systemUIVendorServiceComponent);
    }

    public WMComponent getWMComponent() {
        return this.mWMComponent;
    }

    public void init(boolean z) throws ExecutionException, InterruptedException {
        DaggerReferenceGlobalRootComponent.ReferenceSysUIComponentBuilder referenceSysUIComponentBuilder;
        GlobalRootComponent.Builder globalRootComponentBuilder = getGlobalRootComponentBuilder();
        Context context = this.mContext;
        DaggerReferenceGlobalRootComponent.Builder builder = (DaggerReferenceGlobalRootComponent.Builder) globalRootComponentBuilder;
        builder.getClass();
        context.getClass();
        builder.context = context;
        builder.instrumentationTest = Boolean.valueOf(z);
        ReferenceGlobalRootComponent referenceGlobalRootComponentBuild = builder.build();
        this.mRootComponent = referenceGlobalRootComponentBuild;
        InitializationChecker initializationChecker = ((DaggerReferenceGlobalRootComponent.ReferenceGlobalRootComponentImpl) referenceGlobalRootComponentBuild).getInitializationChecker();
        this.mInitializationChecker = initializationChecker;
        boolean zInitializeComponents = initializationChecker.initializeComponents();
        Context context2 = this.mContext;
        final WMComponent.Builder wMComponentBuilder = this.mRootComponent.getWMComponentBuilder();
        if (this.mInitializationChecker.initializeComponents() && context2.getResources().getBoolean(R.bool.config_enableShellMainThread)) {
            final HandlerThread handlerThreadCreateShellMainThread = WMShellConcurrencyModule.createShellMainThread();
            handlerThreadCreateShellMainThread.start();
            if (!Handler.createAsync(handlerThreadCreateShellMainThread.getLooper()).runWithScissors(new Runnable() { // from class: com.android.systemui.SystemUIInitializer$$ExternalSyntheticLambda0
                @Override // java.lang.Runnable
                public final void run() {
                    SystemUIInitializer.$r8$lambda$QYvDnW0XyzgDh_C_u5znA3aE5Nk(this.f$0, wMComponentBuilder, handlerThreadCreateShellMainThread);
                }
            }, 5000L)) {
                Log.w(TAG, "Failed to initialize WMComponent");
                throw new RuntimeException();
            }
        } else {
            this.mWMComponent = ((DaggerReferenceGlobalRootComponent.WMComponentBuilder) wMComponentBuilder).build();
        }
        ReferenceSysUIComponent.Builder sysUIComponent = ((DaggerReferenceGlobalRootComponent.ReferenceGlobalRootComponentImpl) this.mRootComponent).getSysUIComponent();
        if (zInitializeComponents) {
            SysUIComponent.Builder builderPrepareSysUIComponentBuilder = prepareSysUIComponentBuilder(sysUIComponent, this.mWMComponent);
            ShellInterface shell = this.mWMComponent.getShell();
            referenceSysUIComponentBuilder = (DaggerReferenceGlobalRootComponent.ReferenceSysUIComponentBuilder) builderPrepareSysUIComponentBuilder;
            referenceSysUIComponentBuilder.getClass();
            shell.getClass();
            referenceSysUIComponentBuilder.setShell = shell;
            Optional<Pip> pip = this.mWMComponent.getPip();
            pip.getClass();
            referenceSysUIComponentBuilder.setPip = pip;
            Optional<SplitScreen> splitScreen = this.mWMComponent.getSplitScreen();
            splitScreen.getClass();
            referenceSysUIComponentBuilder.setSplitScreen = splitScreen;
            Optional<OneHanded> oneHanded = this.mWMComponent.getOneHanded();
            oneHanded.getClass();
            referenceSysUIComponentBuilder.setOneHanded = oneHanded;
            Optional<Bubbles> bubbles = this.mWMComponent.getBubbles();
            bubbles.getClass();
            referenceSysUIComponentBuilder.setBubbles = bubbles;
            Optional<TaskViewFactoryController.TaskViewFactoryImpl> taskViewFactory = this.mWMComponent.getTaskViewFactory();
            taskViewFactory.getClass();
            referenceSysUIComponentBuilder.setTaskViewFactory = taskViewFactory;
            ShellTransitions shellTransitions = this.mWMComponent.getShellTransitions();
            shellTransitions.getClass();
            referenceSysUIComponentBuilder.setShellTransitions = shellTransitions;
            KeyguardTransitions keyguardTransitions = this.mWMComponent.getKeyguardTransitions();
            keyguardTransitions.getClass();
            referenceSysUIComponentBuilder.setKeyguardTransitions = keyguardTransitions;
            Optional<StartingWindowController.StartingSurfaceImpl> startingSurface = this.mWMComponent.getStartingSurface();
            startingSurface.getClass();
            referenceSysUIComponentBuilder.setStartingSurface = startingSurface;
            Optional<Object> displayAreaHelper = this.mWMComponent.getDisplayAreaHelper();
            displayAreaHelper.getClass();
            referenceSysUIComponentBuilder.setDisplayAreaHelper = displayAreaHelper;
            Optional<RecentTasks> recentTasks = this.mWMComponent.getRecentTasks();
            recentTasks.getClass();
            referenceSysUIComponentBuilder.setRecentTasks = recentTasks;
            Optional<BackAnimationController.BackAnimationImpl> backAnimation = this.mWMComponent.getBackAnimation();
            backAnimation.getClass();
            referenceSysUIComponentBuilder.setBackAnimation = backAnimation;
            Optional<DesktopMode> desktopMode = this.mWMComponent.getDesktopMode();
            desktopMode.getClass();
            referenceSysUIComponentBuilder.setDesktopMode = desktopMode;
            Optional<AppZoomOutController.AppZoomOutImpl> appZoomOut = this.mWMComponent.getAppZoomOut();
            appZoomOut.getClass();
            referenceSysUIComponentBuilder.setAppZoomOut = appZoomOut;
            Optional<EnterSplitGestureHandler> enterSplitGestureHandler = this.mWMComponent.getEnterSplitGestureHandler();
            enterSplitGestureHandler.getClass();
            referenceSysUIComponentBuilder.setEnterSplitGestureHandler = enterSplitGestureHandler;
            Optional<SplitScreenController> splitScreenController = this.mWMComponent.getSplitScreenController();
            splitScreenController.getClass();
            referenceSysUIComponentBuilder.setSplitScreenController = splitScreenController;
            Optional<CoverLauncherAppCompatStartController> coverLauncherAppCompatStartController = this.mWMComponent.getCoverLauncherAppCompatStartController();
            coverLauncherAppCompatStartController.getClass();
            referenceSysUIComponentBuilder.setCoverLauncherAppCompatStartController = coverLauncherAppCompatStartController;
            Optional<DisplayController> displayController = this.mWMComponent.getDisplayController();
            displayController.getClass();
            referenceSysUIComponentBuilder.setDisplayController = displayController;
            this.mWMComponent.init();
        } else {
            SysUIComponent.Builder builderPrepareSysUIComponentBuilder2 = prepareSysUIComponentBuilder(sysUIComponent, this.mWMComponent);
            ShellInterface shellInterface = new ShellInterface(this) { // from class: com.android.systemui.SystemUIInitializer.3
            };
            referenceSysUIComponentBuilder = (DaggerReferenceGlobalRootComponent.ReferenceSysUIComponentBuilder) builderPrepareSysUIComponentBuilder2;
            referenceSysUIComponentBuilder.getClass();
            referenceSysUIComponentBuilder.setShell = shellInterface;
            Optional<Pip> optionalOfNullable = Optional.ofNullable(null);
            optionalOfNullable.getClass();
            referenceSysUIComponentBuilder.setPip = optionalOfNullable;
            Optional<SplitScreen> optionalOfNullable2 = Optional.ofNullable(null);
            optionalOfNullable2.getClass();
            referenceSysUIComponentBuilder.setSplitScreen = optionalOfNullable2;
            Optional<OneHanded> optionalOfNullable3 = Optional.ofNullable(null);
            optionalOfNullable3.getClass();
            referenceSysUIComponentBuilder.setOneHanded = optionalOfNullable3;
            Optional<Bubbles> optionalOfNullable4 = Optional.ofNullable(null);
            optionalOfNullable4.getClass();
            referenceSysUIComponentBuilder.setBubbles = optionalOfNullable4;
            Optional<TaskViewFactoryController.TaskViewFactoryImpl> optionalOfNullable5 = Optional.ofNullable(null);
            optionalOfNullable5.getClass();
            referenceSysUIComponentBuilder.setTaskViewFactory = optionalOfNullable5;
            referenceSysUIComponentBuilder.setShellTransitions = new ShellTransitions(this) { // from class: com.android.systemui.SystemUIInitializer.2
            };
            referenceSysUIComponentBuilder.setKeyguardTransitions = new KeyguardTransitions(this) { // from class: com.android.systemui.SystemUIInitializer.1
            };
            Optional<Object> optionalOfNullable6 = Optional.ofNullable(null);
            optionalOfNullable6.getClass();
            referenceSysUIComponentBuilder.setDisplayAreaHelper = optionalOfNullable6;
            Optional<StartingWindowController.StartingSurfaceImpl> optionalOfNullable7 = Optional.ofNullable(null);
            optionalOfNullable7.getClass();
            referenceSysUIComponentBuilder.setStartingSurface = optionalOfNullable7;
            Optional<RecentTasks> optionalOfNullable8 = Optional.ofNullable(null);
            optionalOfNullable8.getClass();
            referenceSysUIComponentBuilder.setRecentTasks = optionalOfNullable8;
            Optional<BackAnimationController.BackAnimationImpl> optionalOfNullable9 = Optional.ofNullable(null);
            optionalOfNullable9.getClass();
            referenceSysUIComponentBuilder.setBackAnimation = optionalOfNullable9;
            Optional<DesktopMode> optionalOfNullable10 = Optional.ofNullable(null);
            optionalOfNullable10.getClass();
            referenceSysUIComponentBuilder.setDesktopMode = optionalOfNullable10;
            Optional<AppZoomOutController.AppZoomOutImpl> optionalOfNullable11 = Optional.ofNullable(null);
            optionalOfNullable11.getClass();
            referenceSysUIComponentBuilder.setAppZoomOut = optionalOfNullable11;
            Optional<EnterSplitGestureHandler> optionalOfNullable12 = Optional.ofNullable(null);
            optionalOfNullable12.getClass();
            referenceSysUIComponentBuilder.setEnterSplitGestureHandler = optionalOfNullable12;
            Optional<SplitScreenController> optionalOfNullable13 = Optional.ofNullable(null);
            optionalOfNullable13.getClass();
            referenceSysUIComponentBuilder.setSplitScreenController = optionalOfNullable13;
            Optional<CoverLauncherAppCompatStartController> optionalOfNullable14 = Optional.ofNullable(null);
            optionalOfNullable14.getClass();
            referenceSysUIComponentBuilder.setCoverLauncherAppCompatStartController = optionalOfNullable14;
            Optional<DisplayController> displayController2 = this.mWMComponent.getDisplayController();
            displayController2.getClass();
            referenceSysUIComponentBuilder.setDisplayController = displayController2;
        }
        ReferenceSysUIComponent referenceSysUIComponentBuild = referenceSysUIComponentBuilder.build();
        this.mSysUIComponent = referenceSysUIComponentBuild;
        Dependency dependencyCreateDependency = ((DaggerReferenceGlobalRootComponent.ReferenceSysUIComponentImpl) referenceSysUIComponentBuild).createDependency();
        ArrayMap arrayMap = dependencyCreateDependency.mProviders;
        Lazy lazy = dependencyCreateDependency.mTimeTickHandler;
        Objects.requireNonNull(lazy);
        arrayMap.put(Dependency.TIME_TICK_HANDLER, new Dependency$$ExternalSyntheticLambda0(lazy));
        ArrayMap arrayMap2 = dependencyCreateDependency.mProviders;
        Lazy lazy2 = dependencyCreateDependency.mMainHandler;
        Objects.requireNonNull(lazy2);
        arrayMap2.put(Dependency.MAIN_HANDLER, new Dependency$$ExternalSyntheticLambda0(lazy2));
        ArrayMap arrayMap3 = dependencyCreateDependency.mProviders;
        Lazy lazy3 = dependencyCreateDependency.mBgLooper;
        Objects.requireNonNull(lazy3);
        arrayMap3.put(Dependency.BG_LOOPER, new Dependency$$ExternalSyntheticLambda0(lazy3));
        ArrayMap arrayMap4 = dependencyCreateDependency.mProviders;
        Lazy lazy4 = dependencyCreateDependency.mBroadcastDispatcher;
        Objects.requireNonNull(lazy4);
        arrayMap4.put(BroadcastDispatcher.class, new Dependency$$ExternalSyntheticLambda0(lazy4));
        ArrayMap arrayMap5 = dependencyCreateDependency.mProviders;
        Lazy lazy5 = dependencyCreateDependency.mBluetoothController;
        Objects.requireNonNull(lazy5);
        arrayMap5.put(BluetoothController.class, new Dependency$$ExternalSyntheticLambda0(lazy5));
        ArrayMap arrayMap6 = dependencyCreateDependency.mProviders;
        Lazy lazy6 = dependencyCreateDependency.mKeyguardUpdateMonitor;
        Objects.requireNonNull(lazy6);
        arrayMap6.put(KeyguardUpdateMonitor.class, new Dependency$$ExternalSyntheticLambda0(lazy6));
        ArrayMap arrayMap7 = dependencyCreateDependency.mProviders;
        Lazy lazy7 = dependencyCreateDependency.mDeviceProvisionedController;
        Objects.requireNonNull(lazy7);
        arrayMap7.put(DeviceProvisionedController.class, new Dependency$$ExternalSyntheticLambda0(lazy7));
        ArrayMap arrayMap8 = dependencyCreateDependency.mProviders;
        Lazy lazy8 = dependencyCreateDependency.mPluginManager;
        Objects.requireNonNull(lazy8);
        arrayMap8.put(PluginManager.class, new Dependency$$ExternalSyntheticLambda0(lazy8));
        ArrayMap arrayMap9 = dependencyCreateDependency.mProviders;
        Lazy lazy9 = dependencyCreateDependency.mAssistManager;
        Objects.requireNonNull(lazy9);
        arrayMap9.put(AssistManager.class, new Dependency$$ExternalSyntheticLambda0(lazy9));
        ArrayMap arrayMap10 = dependencyCreateDependency.mProviders;
        Lazy lazy10 = dependencyCreateDependency.mTunerService;
        Objects.requireNonNull(lazy10);
        arrayMap10.put(TunerService.class, new Dependency$$ExternalSyntheticLambda0(lazy10));
        ArrayMap arrayMap11 = dependencyCreateDependency.mProviders;
        Lazy lazy11 = dependencyCreateDependency.mDarkIconDispatcher;
        Objects.requireNonNull(lazy11);
        arrayMap11.put(DarkIconDispatcher.class, new Dependency$$ExternalSyntheticLambda0(lazy11));
        ArrayMap arrayMap12 = dependencyCreateDependency.mProviders;
        Lazy lazy12 = dependencyCreateDependency.mFragmentService;
        Objects.requireNonNull(lazy12);
        arrayMap12.put(FragmentService.class, new Dependency$$ExternalSyntheticLambda0(lazy12));
        ArrayMap arrayMap13 = dependencyCreateDependency.mProviders;
        Lazy lazy13 = dependencyCreateDependency.mVolumeDialogController;
        Objects.requireNonNull(lazy13);
        arrayMap13.put(VolumeDialogController.class, new Dependency$$ExternalSyntheticLambda0(lazy13));
        ArrayMap arrayMap14 = dependencyCreateDependency.mProviders;
        Lazy lazy14 = dependencyCreateDependency.mVolumeManager;
        Objects.requireNonNull(lazy14);
        arrayMap14.put(VolumeManager.class, new Dependency$$ExternalSyntheticLambda0(lazy14));
        ArrayMap arrayMap15 = dependencyCreateDependency.mProviders;
        Lazy lazy15 = dependencyCreateDependency.mMetricsLogger;
        Objects.requireNonNull(lazy15);
        arrayMap15.put(MetricsLogger.class, new Dependency$$ExternalSyntheticLambda0(lazy15));
        ArrayMap arrayMap16 = dependencyCreateDependency.mProviders;
        Lazy lazy16 = dependencyCreateDependency.mUiOffloadThread;
        Objects.requireNonNull(lazy16);
        arrayMap16.put(UiOffloadThread.class, new Dependency$$ExternalSyntheticLambda0(lazy16));
        ArrayMap arrayMap17 = dependencyCreateDependency.mProviders;
        Lazy lazy17 = dependencyCreateDependency.mLightBarController;
        Objects.requireNonNull(lazy17);
        arrayMap17.put(LightBarController.class, new Dependency$$ExternalSyntheticLambda0(lazy17));
        ArrayMap arrayMap18 = dependencyCreateDependency.mProviders;
        Lazy lazy18 = dependencyCreateDependency.mLauncherProxyService;
        Objects.requireNonNull(lazy18);
        arrayMap18.put(LauncherProxyService.class, new Dependency$$ExternalSyntheticLambda0(lazy18));
        ArrayMap arrayMap19 = dependencyCreateDependency.mProviders;
        Lazy lazy19 = dependencyCreateDependency.mNavBarModeController;
        Objects.requireNonNull(lazy19);
        arrayMap19.put(NavigationModeController.class, new Dependency$$ExternalSyntheticLambda0(lazy19));
        ArrayMap arrayMap20 = dependencyCreateDependency.mProviders;
        Lazy lazy20 = dependencyCreateDependency.mNavigationBarController;
        Objects.requireNonNull(lazy20);
        arrayMap20.put(NavigationBarController.class, new Dependency$$ExternalSyntheticLambda0(lazy20));
        ArrayMap arrayMap21 = dependencyCreateDependency.mProviders;
        Lazy lazy21 = dependencyCreateDependency.mStatusBarStateController;
        Objects.requireNonNull(lazy21);
        arrayMap21.put(StatusBarStateController.class, new Dependency$$ExternalSyntheticLambda0(lazy21));
        ArrayMap arrayMap22 = dependencyCreateDependency.mProviders;
        Lazy lazy22 = dependencyCreateDependency.mNotificationLockscreenUserManager;
        Objects.requireNonNull(lazy22);
        arrayMap22.put(NotificationLockscreenUserManager.class, new Dependency$$ExternalSyntheticLambda0(lazy22));
        ArrayMap arrayMap23 = dependencyCreateDependency.mProviders;
        Lazy lazy23 = dependencyCreateDependency.mNotificationMediaManager;
        Objects.requireNonNull(lazy23);
        arrayMap23.put(NotificationMediaManager.class, new Dependency$$ExternalSyntheticLambda0(lazy23));
        ArrayMap arrayMap24 = dependencyCreateDependency.mProviders;
        Lazy lazy24 = dependencyCreateDependency.mSysUiStateFlagsContainer;
        Objects.requireNonNull(lazy24);
        arrayMap24.put(SysUiState.class, new Dependency$$ExternalSyntheticLambda0(lazy24));
        ArrayMap arrayMap25 = dependencyCreateDependency.mProviders;
        Lazy lazy25 = dependencyCreateDependency.mCommandQueue;
        Objects.requireNonNull(lazy25);
        arrayMap25.put(CommandQueue.class, new Dependency$$ExternalSyntheticLambda0(lazy25));
        ArrayMap arrayMap26 = dependencyCreateDependency.mProviders;
        Lazy lazy26 = dependencyCreateDependency.mUiEventLogger;
        Objects.requireNonNull(lazy26);
        arrayMap26.put(UiEventLogger.class, new Dependency$$ExternalSyntheticLambda0(lazy26));
        ArrayMap arrayMap27 = dependencyCreateDependency.mProviders;
        Lazy lazy27 = dependencyCreateDependency.mFeatureFlagsLazy;
        Objects.requireNonNull(lazy27);
        arrayMap27.put(FeatureFlags.class, new Dependency$$ExternalSyntheticLambda0(lazy27));
        ArrayMap arrayMap28 = dependencyCreateDependency.mProviders;
        Lazy lazy28 = dependencyCreateDependency.mNotificationSectionsManagerLazy;
        Objects.requireNonNull(lazy28);
        arrayMap28.put(NotificationSectionsManager.class, new Dependency$$ExternalSyntheticLambda0(lazy28));
        ArrayMap arrayMap29 = dependencyCreateDependency.mProviders;
        Lazy lazy29 = dependencyCreateDependency.mScreenOffAnimationController;
        Objects.requireNonNull(lazy29);
        arrayMap29.put(ScreenOffAnimationController.class, new Dependency$$ExternalSyntheticLambda0(lazy29));
        ArrayMap arrayMap30 = dependencyCreateDependency.mProviders;
        Lazy lazy30 = dependencyCreateDependency.mAmbientStateLazy;
        Objects.requireNonNull(lazy30);
        arrayMap30.put(AmbientState.class, new Dependency$$ExternalSyntheticLambda0(lazy30));
        ArrayMap arrayMap31 = dependencyCreateDependency.mProviders;
        Lazy lazy31 = dependencyCreateDependency.mGroupMembershipManagerLazy;
        Objects.requireNonNull(lazy31);
        arrayMap31.put(GroupMembershipManager.class, new Dependency$$ExternalSyntheticLambda0(lazy31));
        ArrayMap arrayMap32 = dependencyCreateDependency.mProviders;
        Lazy lazy32 = dependencyCreateDependency.mGroupExpansionManagerLazy;
        Objects.requireNonNull(lazy32);
        arrayMap32.put(GroupExpansionManager.class, new Dependency$$ExternalSyntheticLambda0(lazy32));
        ArrayMap arrayMap33 = dependencyCreateDependency.mProviders;
        Lazy lazy33 = dependencyCreateDependency.mSystemUIDialogManagerLazy;
        Objects.requireNonNull(lazy33);
        arrayMap33.put(SystemUIDialogManager.class, new Dependency$$ExternalSyntheticLambda0(lazy33));
        ArrayMap arrayMap34 = dependencyCreateDependency.mProviders;
        Lazy lazy34 = dependencyCreateDependency.mDialogTransitionAnimatorLazy;
        Objects.requireNonNull(lazy34);
        arrayMap34.put(DialogTransitionAnimator.class, new Dependency$$ExternalSyntheticLambda0(lazy34));
        ArrayMap arrayMap35 = dependencyCreateDependency.mProviders;
        Lazy lazy35 = dependencyCreateDependency.mUserTrackerLazy;
        Objects.requireNonNull(lazy35);
        arrayMap35.put(UserTracker.class, new Dependency$$ExternalSyntheticLambda0(lazy35));
        ArrayMap arrayMap36 = dependencyCreateDependency.mProviders;
        Lazy lazy36 = dependencyCreateDependency.mStatusBarWindowControllerStoreLazy;
        Objects.requireNonNull(lazy36);
        arrayMap36.put(StatusBarWindowControllerStore.class, new Dependency$$ExternalSyntheticLambda0(lazy36));
        ArrayMap arrayMap37 = dependencyCreateDependency.mProviders;
        Lazy lazy37 = dependencyCreateDependency.mSPluginManager;
        Objects.requireNonNull(lazy37);
        arrayMap37.put(SPluginManager.class, new Dependency$$ExternalSyntheticLambda0(lazy37));
        ArrayMap arrayMap38 = dependencyCreateDependency.mProviders;
        Lazy lazy38 = dependencyCreateDependency.mSPluginDependencyProvider;
        Objects.requireNonNull(lazy38);
        arrayMap38.put(SPluginDependencyProvider.class, new Dependency$$ExternalSyntheticLambda0(lazy38));
        ArrayMap arrayMap39 = dependencyCreateDependency.mProviders;
        Lazy lazy39 = dependencyCreateDependency.mLooperSlowLogController;
        Objects.requireNonNull(lazy39);
        arrayMap39.put(LooperSlowLogController.class, new Dependency$$ExternalSyntheticLambda0(lazy39));
        ArrayMap arrayMap40 = dependencyCreateDependency.mProviders;
        Lazy lazy40 = dependencyCreateDependency.mDesktopManager;
        Objects.requireNonNull(lazy40);
        arrayMap40.put(DesktopManager.class, new Dependency$$ExternalSyntheticLambda0(lazy40));
        ArrayMap arrayMap41 = dependencyCreateDependency.mProviders;
        Lazy lazy41 = dependencyCreateDependency.mSettingsHelper;
        Objects.requireNonNull(lazy41);
        arrayMap41.put(SettingsHelper.class, new Dependency$$ExternalSyntheticLambda0(lazy41));
        if (BasicRune.SEARCLE) {
            ArrayMap arrayMap42 = dependencyCreateDependency.mProviders;
            Lazy lazy42 = dependencyCreateDependency.mSearcleManager;
            Objects.requireNonNull(lazy42);
            arrayMap42.put(SearcleManager.class, new Dependency$$ExternalSyntheticLambda0(lazy42));
        }
        ArrayMap arrayMap43 = dependencyCreateDependency.mProviders;
        Lazy lazy43 = dependencyCreateDependency.mWallpaperEventNotifier;
        Objects.requireNonNull(lazy43);
        arrayMap43.put(WallpaperEventNotifier.class, new Dependency$$ExternalSyntheticLambda0(lazy43));
        ArrayMap arrayMap44 = dependencyCreateDependency.mProviders;
        Lazy lazy44 = dependencyCreateDependency.mWallpaperChangeNotifier;
        Objects.requireNonNull(lazy44);
        arrayMap44.put(WallpaperChangeNotifier.class, new Dependency$$ExternalSyntheticLambda0(lazy44));
        ArrayMap arrayMap45 = dependencyCreateDependency.mProviders;
        Lazy lazy45 = dependencyCreateDependency.mPluginLockManager;
        Objects.requireNonNull(lazy45);
        arrayMap45.put(PluginLockManager.class, new Dependency$$ExternalSyntheticLambda0(lazy45));
        ArrayMap arrayMap46 = dependencyCreateDependency.mProviders;
        Lazy lazy46 = dependencyCreateDependency.mPluginWallpaperManager;
        Objects.requireNonNull(lazy46);
        arrayMap46.put(PluginWallpaperManager.class, new Dependency$$ExternalSyntheticLambda0(lazy46));
        ArrayMap arrayMap47 = dependencyCreateDependency.mProviders;
        Lazy lazy47 = dependencyCreateDependency.mPluginWallController;
        Objects.requireNonNull(lazy47);
        arrayMap47.put(PluginWallpaperController.class, new Dependency$$ExternalSyntheticLambda0(lazy47));
        ArrayMap arrayMap48 = dependencyCreateDependency.mProviders;
        Lazy lazy48 = dependencyCreateDependency.mPluginLockStarManager;
        Objects.requireNonNull(lazy48);
        arrayMap48.put(PluginLockStarManager.class, new Dependency$$ExternalSyntheticLambda0(lazy48));
        ArrayMap arrayMap49 = dependencyCreateDependency.mProviders;
        Lazy lazy49 = dependencyCreateDependency.mQSClockBellTower;
        Objects.requireNonNull(lazy49);
        arrayMap49.put(QSClockBellTower.class, new Dependency$$ExternalSyntheticLambda0(lazy49));
        ArrayMap arrayMap50 = dependencyCreateDependency.mProviders;
        Lazy lazy50 = dependencyCreateDependency.mSecQuickSettingsAffordanceInteractor;
        Objects.requireNonNull(lazy50);
        arrayMap50.put(SecQuickSettingsAffordanceInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy50));
        ArrayMap arrayMap51 = dependencyCreateDependency.mProviders;
        Lazy lazy51 = dependencyCreateDependency.mSecQSPanelResourcePicker;
        Objects.requireNonNull(lazy51);
        arrayMap51.put(SecQSPanelResourcePicker.class, new Dependency$$ExternalSyntheticLambda0(lazy51));
        ArrayMap arrayMap52 = dependencyCreateDependency.mProviders;
        Lazy lazy52 = dependencyCreateDependency.mShadeHeaderController;
        Objects.requireNonNull(lazy52);
        arrayMap52.put(ShadeHeaderController.class, new Dependency$$ExternalSyntheticLambda0(lazy52));
        ArrayMap arrayMap53 = dependencyCreateDependency.mProviders;
        Lazy lazy53 = dependencyCreateDependency.mShadeRepository;
        Objects.requireNonNull(lazy53);
        arrayMap53.put(ShadeRepository.class, new Dependency$$ExternalSyntheticLambda0(lazy53));
        ArrayMap arrayMap54 = dependencyCreateDependency.mProviders;
        Lazy lazy54 = dependencyCreateDependency.mSecNotificationShadeWindowStateInteractor;
        Objects.requireNonNull(lazy54);
        arrayMap54.put(SecNotificationShadeWindowStateInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy54));
        ArrayMap arrayMap55 = dependencyCreateDependency.mProviders;
        Lazy lazy55 = dependencyCreateDependency.mColoredBGHelper;
        Objects.requireNonNull(lazy55);
        arrayMap55.put(ColoredBGHelper.class, new Dependency$$ExternalSyntheticLambda0(lazy55));
        ArrayMap arrayMap56 = dependencyCreateDependency.mProviders;
        Lazy lazy56 = dependencyCreateDependency.mShadeController;
        Objects.requireNonNull(lazy56);
        arrayMap56.put(ShadeController.class, new Dependency$$ExternalSyntheticLambda0(lazy56));
        ArrayMap arrayMap57 = dependencyCreateDependency.mProviders;
        Lazy lazy57 = dependencyCreateDependency.mSecQpBlurController;
        Objects.requireNonNull(lazy57);
        arrayMap57.put(SecQpBlurController.class, new Dependency$$ExternalSyntheticLambda0(lazy57));
        ArrayMap arrayMap58 = dependencyCreateDependency.mProviders;
        Lazy lazy58 = dependencyCreateDependency.mActivityStarter;
        Objects.requireNonNull(lazy58);
        arrayMap58.put(ActivityStarter.class, new Dependency$$ExternalSyntheticLambda0(lazy58));
        ArrayMap arrayMap59 = dependencyCreateDependency.mProviders;
        Lazy lazy59 = dependencyCreateDependency.mSecPanelExpansionStateInteractor;
        Objects.requireNonNull(lazy59);
        arrayMap59.put(SecPanelExpansionStateInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy59));
        ArrayMap arrayMap60 = dependencyCreateDependency.mProviders;
        Lazy lazy60 = dependencyCreateDependency.mQuickPanelExternalLogger;
        Objects.requireNonNull(lazy60);
        arrayMap60.put(QuickPanelExternalLogger.class, new Dependency$$ExternalSyntheticLambda0(lazy60));
        ArrayMap arrayMap61 = dependencyCreateDependency.mProviders;
        Lazy lazy61 = dependencyCreateDependency.mSecQSExpansionStateInteractor;
        Objects.requireNonNull(lazy61);
        arrayMap61.put(SecQSExpansionStateInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy61));
        ArrayMap arrayMap62 = dependencyCreateDependency.mProviders;
        Lazy lazy62 = dependencyCreateDependency.mPanelSplitHelper;
        Objects.requireNonNull(lazy62);
        arrayMap62.put(SecPanelSplitHelper.class, new Dependency$$ExternalSyntheticLambda0(lazy62));
        ArrayMap arrayMap63 = dependencyCreateDependency.mProviders;
        Lazy lazy63 = dependencyCreateDependency.mSecPanelTouchBlockHelper;
        Objects.requireNonNull(lazy63);
        arrayMap63.put(SecPanelTouchBlockHelper.class, new Dependency$$ExternalSyntheticLambda0(lazy63));
        ArrayMap arrayMap64 = dependencyCreateDependency.mProviders;
        Lazy lazy64 = dependencyCreateDependency.mSecPanelTouchProximityInteractor;
        Objects.requireNonNull(lazy64);
        arrayMap64.put(SecPanelTouchProximityInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy64));
        ArrayMap arrayMap65 = dependencyCreateDependency.mProviders;
        Lazy lazy65 = dependencyCreateDependency.mQSScrimViewSwitch;
        Objects.requireNonNull(lazy65);
        arrayMap65.put(QSScrimViewSwitch.class, new Dependency$$ExternalSyntheticLambda0(lazy65));
        ArrayMap arrayMap66 = dependencyCreateDependency.mProviders;
        Lazy lazy66 = dependencyCreateDependency.mSecPanelSAStatusLogInteractor;
        Objects.requireNonNull(lazy66);
        arrayMap66.put(SecPanelSAStatusLogInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy66));
        ArrayMap arrayMap67 = dependencyCreateDependency.mProviders;
        Lazy lazy67 = dependencyCreateDependency.mSecQSCoverResourcePicker;
        Objects.requireNonNull(lazy67);
        arrayMap67.put(SecQSCoverResourcePicker.class, new Dependency$$ExternalSyntheticLambda0(lazy67));
        ArrayMap arrayMap68 = dependencyCreateDependency.mProviders;
        Lazy lazy68 = dependencyCreateDependency.mSubscreenUtil;
        Objects.requireNonNull(lazy68);
        arrayMap68.put(SubscreenUtil.class, new Dependency$$ExternalSyntheticLambda0(lazy68));
        ArrayMap arrayMap69 = dependencyCreateDependency.mProviders;
        Lazy lazy69 = dependencyCreateDependency.msecMediaHost;
        Objects.requireNonNull(lazy69);
        arrayMap69.put(SecMediaHost.class, new Dependency$$ExternalSyntheticLambda0(lazy69));
        ArrayMap arrayMap70 = dependencyCreateDependency.mProviders;
        Lazy lazy70 = dependencyCreateDependency.mSubscreenMusicWidgetController;
        Objects.requireNonNull(lazy70);
        arrayMap70.put(SubscreenMusicWidgetController.class, new Dependency$$ExternalSyntheticLambda0(lazy70));
        ArrayMap arrayMap71 = dependencyCreateDependency.mProviders;
        Lazy lazy71 = dependencyCreateDependency.mPrivacyDialogController;
        Objects.requireNonNull(lazy71);
        arrayMap71.put(PrivacyDialogController.class, new Dependency$$ExternalSyntheticLambda0(lazy71));
        ArrayMap arrayMap72 = dependencyCreateDependency.mProviders;
        Lazy lazy72 = dependencyCreateDependency.mSecQSDetailController;
        Objects.requireNonNull(lazy72);
        arrayMap72.put(SecQSDetailController.class, new Dependency$$ExternalSyntheticLambda0(lazy72));
        ArrayMap arrayMap73 = dependencyCreateDependency.mProviders;
        Lazy lazy73 = dependencyCreateDependency.mFalsingManager;
        Objects.requireNonNull(lazy73);
        arrayMap73.put(FalsingManager.class, new Dependency$$ExternalSyntheticLambda0(lazy73));
        ArrayMap arrayMap74 = dependencyCreateDependency.mProviders;
        Lazy lazy74 = dependencyCreateDependency.mResetSettingsManager;
        Objects.requireNonNull(lazy74);
        arrayMap74.put(QsResetSettingsManager.class, new Dependency$$ExternalSyntheticLambda0(lazy74));
        ArrayMap arrayMap75 = dependencyCreateDependency.mProviders;
        Lazy lazy75 = dependencyCreateDependency.mQSBackupRestoreManager;
        Objects.requireNonNull(lazy75);
        arrayMap75.put(QSBackupRestoreManager.class, new Dependency$$ExternalSyntheticLambda0(lazy75));
        ArrayMap arrayMap76 = dependencyCreateDependency.mProviders;
        Lazy lazy76 = dependencyCreateDependency.mKnoxStateMonitor;
        Objects.requireNonNull(lazy76);
        arrayMap76.put(KnoxStateMonitor.class, new Dependency$$ExternalSyntheticLambda0(lazy76));
        ArrayMap arrayMap77 = dependencyCreateDependency.mProviders;
        Lazy lazy77 = dependencyCreateDependency.mSystemUIIndexMediator;
        Objects.requireNonNull(lazy77);
        arrayMap77.put(SystemUIIndexMediator.class, new Dependency$$ExternalSyntheticLambda0(lazy77));
        ArrayMap arrayMap78 = dependencyCreateDependency.mProviders;
        Lazy lazy78 = dependencyCreateDependency.mFullExpansionPanelNotiAlphaController;
        Objects.requireNonNull(lazy78);
        arrayMap78.put(FullExpansionPanelNotiAlphaController.class, new Dependency$$ExternalSyntheticLambda0(lazy78));
        if (BasicRune.NAVBAR_ENABLED) {
            ArrayMap arrayMap79 = dependencyCreateDependency.mProviders;
            Lazy lazy79 = dependencyCreateDependency.mNavBarStore;
            Objects.requireNonNull(lazy79);
            arrayMap79.put(NavBarStore.class, new Dependency$$ExternalSyntheticLambda0(lazy79));
            ArrayMap arrayMap80 = dependencyCreateDependency.mProviders;
            Lazy lazy80 = dependencyCreateDependency.mNavBarBgHandler;
            Objects.requireNonNull(lazy80);
            arrayMap80.put(Dependency.NAVBAR_BG_HANDLER, new Dependency$$ExternalSyntheticLambda0(lazy80));
            ArrayMap arrayMap81 = dependencyCreateDependency.mProviders;
            Lazy lazy81 = dependencyCreateDependency.mTaskbarDelegate;
            Objects.requireNonNull(lazy81);
            arrayMap81.put(TaskbarDelegate.class, new Dependency$$ExternalSyntheticLambda0(lazy81));
            ArrayMap arrayMap82 = dependencyCreateDependency.mProviders;
            Lazy lazy82 = dependencyCreateDependency.mRotationLockController;
            Objects.requireNonNull(lazy82);
            arrayMap82.put(RotationLockController.class, new Dependency$$ExternalSyntheticLambda0(lazy82));
            ArrayMap arrayMap83 = dependencyCreateDependency.mProviders;
            Lazy lazy83 = dependencyCreateDependency.mVibratorHelper;
            Objects.requireNonNull(lazy83);
            arrayMap83.put(VibratorHelper.class, new Dependency$$ExternalSyntheticLambda0(lazy83));
        }
        if (QpRune.QUICK_SUBSCREEN_SETTINGS) {
            ArrayMap arrayMap84 = dependencyCreateDependency.mProviders;
            Lazy lazy84 = dependencyCreateDependency.mNetworkController;
            Objects.requireNonNull(lazy84);
            arrayMap84.put(NetworkController.class, new Dependency$$ExternalSyntheticLambda0(lazy84));
        }
        if (NotiRune.NOTI_SUBSCREEN_NOTIFICATION_SECOND) {
            ArrayMap arrayMap85 = dependencyCreateDependency.mProviders;
            Lazy lazy85 = dependencyCreateDependency.mSubscreenQsPanelController;
            Objects.requireNonNull(lazy85);
            arrayMap85.put(SubscreenQsPanelController.class, new Dependency$$ExternalSyntheticLambda0(lazy85));
        }
        ArrayMap arrayMap86 = dependencyCreateDependency.mProviders;
        Lazy lazy86 = dependencyCreateDependency.mSecRotationWatcher;
        Objects.requireNonNull(lazy86);
        arrayMap86.put(SecRotationWatcher.class, new Dependency$$ExternalSyntheticLambda0(lazy86));
        ArrayMap arrayMap87 = dependencyCreateDependency.mProviders;
        Lazy lazy87 = dependencyCreateDependency.mUserInfoController;
        Objects.requireNonNull(lazy87);
        arrayMap87.put(UserInfoController.class, new Dependency$$ExternalSyntheticLambda0(lazy87));
        ArrayMap arrayMap88 = dependencyCreateDependency.mProviders;
        Lazy lazy88 = dependencyCreateDependency.mUserSwitcherController;
        Objects.requireNonNull(lazy88);
        arrayMap88.put(UserSwitcherController.class, new Dependency$$ExternalSyntheticLambda0(lazy88));
        ArrayMap arrayMap89 = dependencyCreateDependency.mProviders;
        Lazy lazy89 = dependencyCreateDependency.mUserSwitcherInteractor;
        Objects.requireNonNull(lazy89);
        arrayMap89.put(UserSwitcherInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy89));
        ArrayMap arrayMap90 = dependencyCreateDependency.mProviders;
        Lazy lazy90 = dependencyCreateDependency.mSelectedUserInteractor;
        Objects.requireNonNull(lazy90);
        arrayMap90.put(SelectedUserInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy90));
        ArrayMap arrayMap91 = dependencyCreateDependency.mProviders;
        Lazy lazy91 = dependencyCreateDependency.mPluginFaceWidgetManager;
        Objects.requireNonNull(lazy91);
        arrayMap91.put(PluginFaceWidgetManager.class, new Dependency$$ExternalSyntheticLambda0(lazy91));
        ArrayMap arrayMap92 = dependencyCreateDependency.mProviders;
        Lazy lazy92 = dependencyCreateDependency.mFaceWidgetController;
        Objects.requireNonNull(lazy92);
        arrayMap92.put(FaceWidgetPluginControllerImpl.class, new Dependency$$ExternalSyntheticLambda0(lazy92));
        ArrayMap arrayMap93 = dependencyCreateDependency.mProviders;
        Lazy lazy93 = dependencyCreateDependency.mExternalClockProvider;
        Objects.requireNonNull(lazy93);
        arrayMap93.put(ExternalClockProvider.class, new Dependency$$ExternalSyntheticLambda0(lazy93));
        ArrayMap arrayMap94 = dependencyCreateDependency.mProviders;
        Lazy lazy94 = dependencyCreateDependency.mPluginAODManager;
        Objects.requireNonNull(lazy94);
        arrayMap94.put(PluginAODManager.class, new Dependency$$ExternalSyntheticLambda0(lazy94));
        ArrayMap arrayMap95 = dependencyCreateDependency.mProviders;
        Lazy lazy95 = dependencyCreateDependency.mDisplayLifecycle;
        Objects.requireNonNull(lazy95);
        arrayMap95.put(DisplayLifecycle.class, new Dependency$$ExternalSyntheticLambda0(lazy95));
        ArrayMap arrayMap96 = dependencyCreateDependency.mProviders;
        Lazy lazy96 = dependencyCreateDependency.mCoverUtilWrapper;
        Objects.requireNonNull(lazy96);
        arrayMap96.put(CoverUtilWrapper.class, new Dependency$$ExternalSyntheticLambda0(lazy96));
        if (LsRune.SUBSCREEN_UI) {
            ArrayMap arrayMap97 = dependencyCreateDependency.mProviders;
            Lazy lazy97 = dependencyCreateDependency.mSubScreenManager;
            Objects.requireNonNull(lazy97);
            arrayMap97.put(SubScreenManager.class, new Dependency$$ExternalSyntheticLambda0(lazy97));
        }
        if (LsRune.COVER_SUPPORTED) {
            ArrayMap arrayMap98 = dependencyCreateDependency.mProviders;
            Lazy lazy98 = dependencyCreateDependency.mCoverScreenManager;
            Objects.requireNonNull(lazy98);
            arrayMap98.put(CoverScreenManager.class, new Dependency$$ExternalSyntheticLambda0(lazy98));
        }
        ArrayMap arrayMap99 = dependencyCreateDependency.mProviders;
        Lazy lazy99 = dependencyCreateDependency.mGlobalActionsComponent;
        Objects.requireNonNull(lazy99);
        arrayMap99.put(GlobalActionsComponent.class, new Dependency$$ExternalSyntheticLambda0(lazy99));
        ArrayMap arrayMap100 = dependencyCreateDependency.mProviders;
        Lazy lazy100 = dependencyCreateDependency.mSPluginManager;
        Objects.requireNonNull(lazy100);
        arrayMap100.put(SPluginManager.class, new Dependency$$ExternalSyntheticLambda0(lazy100));
        ArrayMap arrayMap101 = dependencyCreateDependency.mProviders;
        Lazy lazy101 = dependencyCreateDependency.mSPluginDependencyProvider;
        Objects.requireNonNull(lazy101);
        arrayMap101.put(SPluginDependencyProvider.class, new Dependency$$ExternalSyntheticLambda0(lazy101));
        ArrayMap arrayMap102 = dependencyCreateDependency.mProviders;
        Lazy lazy102 = dependencyCreateDependency.mOnUserInteractionCallback;
        Objects.requireNonNull(lazy102);
        arrayMap102.put(OnUserInteractionCallback.class, new Dependency$$ExternalSyntheticLambda0(lazy102));
        ArrayMap arrayMap103 = dependencyCreateDependency.mProviders;
        Lazy lazy103 = dependencyCreateDependency.mChannelEditorDialogController;
        Objects.requireNonNull(lazy103);
        arrayMap103.put(ChannelEditorDialogController.class, new Dependency$$ExternalSyntheticLambda0(lazy103));
        ArrayMap arrayMap104 = dependencyCreateDependency.mProviders;
        Lazy lazy104 = dependencyCreateDependency.mHighPriorityProvider;
        Objects.requireNonNull(lazy104);
        arrayMap104.put(HighPriorityProvider.class, new Dependency$$ExternalSyntheticLambda0(lazy104));
        ArrayMap arrayMap105 = dependencyCreateDependency.mProviders;
        Lazy lazy105 = dependencyCreateDependency.mAssistantFeedbackController;
        Objects.requireNonNull(lazy105);
        arrayMap105.put(AssistantFeedbackController.class, new Dependency$$ExternalSyntheticLambda0(lazy105));
        ArrayMap arrayMap106 = dependencyCreateDependency.mProviders;
        Lazy lazy106 = dependencyCreateDependency.mPeopleSpaceWidgetManager;
        Objects.requireNonNull(lazy106);
        arrayMap106.put(PeopleSpaceWidgetManager.class, new Dependency$$ExternalSyntheticLambda0(lazy106));
        ArrayMap arrayMap107 = dependencyCreateDependency.mProviders;
        Lazy lazy107 = dependencyCreateDependency.mUserContextProvider;
        Objects.requireNonNull(lazy107);
        arrayMap107.put(UserContextProvider.class, new Dependency$$ExternalSyntheticLambda0(lazy107));
        ArrayMap arrayMap108 = dependencyCreateDependency.mProviders;
        Lazy lazy108 = dependencyCreateDependency.mBubblesManagerOptional;
        Objects.requireNonNull(lazy108);
        arrayMap108.put(Dependency.BUBBLE_MANAGER, new Dependency$$ExternalSyntheticLambda0(lazy108));
        ArrayMap arrayMap109 = dependencyCreateDependency.mProviders;
        Lazy lazy109 = dependencyCreateDependency.mBgHandler;
        Objects.requireNonNull(lazy109);
        arrayMap109.put(Dependency.BG_HANDLER, new Dependency$$ExternalSyntheticLambda0(lazy109));
        ArrayMap arrayMap110 = dependencyCreateDependency.mProviders;
        Lazy lazy110 = dependencyCreateDependency.mLauncherApps;
        Objects.requireNonNull(lazy110);
        arrayMap110.put(LauncherApps.class, new Dependency$$ExternalSyntheticLambda0(lazy110));
        ArrayMap arrayMap111 = dependencyCreateDependency.mProviders;
        Lazy lazy111 = dependencyCreateDependency.mINotificationManager;
        Objects.requireNonNull(lazy111);
        arrayMap111.put(INotificationManager.class, new Dependency$$ExternalSyntheticLambda0(lazy111));
        if (NotiRune.NOTI_SUBSCREEN_ALL) {
            ArrayMap arrayMap112 = dependencyCreateDependency.mProviders;
            Lazy lazy112 = dependencyCreateDependency.mSubscreenNotificationController;
            Objects.requireNonNull(lazy112);
            arrayMap112.put(SubscreenNotificationController.class, new Dependency$$ExternalSyntheticLambda0(lazy112));
        }
        ArrayMap arrayMap113 = dependencyCreateDependency.mProviders;
        Lazy lazy113 = dependencyCreateDependency.mNotifCollection;
        Objects.requireNonNull(lazy113);
        arrayMap113.put(NotifCollection.class, new Dependency$$ExternalSyntheticLambda0(lazy113));
        ArrayMap arrayMap114 = dependencyCreateDependency.mProviders;
        Lazy lazy114 = dependencyCreateDependency.mKeyguardShortcutManager;
        Objects.requireNonNull(lazy114);
        arrayMap114.put(KeyguardShortcutManager.class, new Dependency$$ExternalSyntheticLambda0(lazy114));
        ArrayMap arrayMap115 = dependencyCreateDependency.mProviders;
        Lazy lazy115 = dependencyCreateDependency.mFlashlightController;
        Objects.requireNonNull(lazy115);
        arrayMap115.put(FlashlightController.class, new Dependency$$ExternalSyntheticLambda0(lazy115));
        ArrayMap arrayMap116 = dependencyCreateDependency.mProviders;
        Lazy lazy116 = dependencyCreateDependency.mKeyguardMonitor;
        Objects.requireNonNull(lazy116);
        arrayMap116.put(KeyguardStateController.class, new Dependency$$ExternalSyntheticLambda0(lazy116));
        ArrayMap arrayMap117 = dependencyCreateDependency.mProviders;
        Lazy lazy117 = dependencyCreateDependency.mWakefulnessLifecycle;
        Objects.requireNonNull(lazy117);
        arrayMap117.put(WakefulnessLifecycle.class, new Dependency$$ExternalSyntheticLambda0(lazy117));
        ArrayMap arrayMap118 = dependencyCreateDependency.mProviders;
        Lazy lazy118 = dependencyCreateDependency.mKeyguardVisibilityMonitor;
        Objects.requireNonNull(lazy118);
        arrayMap118.put(KeyguardVisibilityMonitor.class, new Dependency$$ExternalSyntheticLambda0(lazy118));
        ArrayMap arrayMap119 = dependencyCreateDependency.mProviders;
        Lazy lazy119 = dependencyCreateDependency.mNotificationShelfManager;
        Objects.requireNonNull(lazy119);
        arrayMap119.put(NotificationShelfManager.class, new Dependency$$ExternalSyntheticLambda0(lazy119));
        ArrayMap arrayMap120 = dependencyCreateDependency.mProviders;
        Lazy lazy120 = dependencyCreateDependency.mPanelScreenShotBufferLogger;
        Objects.requireNonNull(lazy120);
        arrayMap120.put(PanelScreenShotBufferLogger.class, new Dependency$$ExternalSyntheticLambda0(lazy120));
        ArrayMap arrayMap121 = dependencyCreateDependency.mProviders;
        Lazy lazy121 = dependencyCreateDependency.mNotiCinemaLogger;
        Objects.requireNonNull(lazy121);
        arrayMap121.put(NotiCinemaLogger.class, new Dependency$$ExternalSyntheticLambda0(lazy121));
        ArrayMap arrayMap122 = dependencyCreateDependency.mProviders;
        Lazy lazy122 = dependencyCreateDependency.mNotificationBackupRestoreManager;
        Objects.requireNonNull(lazy122);
        arrayMap122.put(NotificationBackupRestoreManager.class, new Dependency$$ExternalSyntheticLambda0(lazy122));
        ArrayMap arrayMap123 = dependencyCreateDependency.mProviders;
        Lazy lazy123 = dependencyCreateDependency.mShelfToolTipManager;
        Objects.requireNonNull(lazy123);
        arrayMap123.put(ShelfToolTipManager.class, new Dependency$$ExternalSyntheticLambda0(lazy123));
        ArrayMap arrayMap124 = dependencyCreateDependency.mProviders;
        Lazy lazy124 = dependencyCreateDependency.mNotificationGutsManager;
        Objects.requireNonNull(lazy124);
        arrayMap124.put(NotificationGutsManager.class, new Dependency$$ExternalSyntheticLambda0(lazy124));
        ArrayMap arrayMap125 = dependencyCreateDependency.mProviders;
        Lazy lazy125 = dependencyCreateDependency.mNotificationColorPicker;
        Objects.requireNonNull(lazy125);
        arrayMap125.put(NotificationColorPicker.class, new Dependency$$ExternalSyntheticLambda0(lazy125));
        ArrayMap arrayMap126 = dependencyCreateDependency.mProviders;
        Lazy lazy126 = dependencyCreateDependency.mNotifLiveDataStore;
        Objects.requireNonNull(lazy126);
        arrayMap126.put(NotifLiveDataStore.class, new Dependency$$ExternalSyntheticLambda0(lazy126));
        ArrayMap arrayMap127 = dependencyCreateDependency.mProviders;
        Lazy lazy127 = dependencyCreateDependency.mSensitiveNotificationProtectionController;
        Objects.requireNonNull(lazy127);
        arrayMap127.put(SensitiveNotificationProtectionController.class, new Dependency$$ExternalSyntheticLambda0(lazy127));
        ArrayMap arrayMap128 = dependencyCreateDependency.mProviders;
        Lazy lazy128 = dependencyCreateDependency.mHeadsUpManager;
        Objects.requireNonNull(lazy128);
        arrayMap128.put(HeadsUpManager.class, new Dependency$$ExternalSyntheticLambda0(lazy128));
        ArrayMap arrayMap129 = dependencyCreateDependency.mProviders;
        Lazy lazy129 = dependencyCreateDependency.mAllowedOngoingActivityListManager;
        Objects.requireNonNull(lazy129);
        arrayMap129.put(AllowedOngoingActivityListManager.class, new Dependency$$ExternalSyntheticLambda0(lazy129));
        ArrayMap arrayMap130 = dependencyCreateDependency.mProviders;
        Lazy lazy130 = dependencyCreateDependency.mFastUnlockController;
        Objects.requireNonNull(lazy130);
        arrayMap130.put(KeyguardFastBioUnlockController.class, new Dependency$$ExternalSyntheticLambda0(lazy130));
        ArrayMap arrayMap131 = dependencyCreateDependency.mProviders;
        Lazy lazy131 = dependencyCreateDependency.mCentralSurfaces;
        Objects.requireNonNull(lazy131);
        arrayMap131.put(CentralSurfaces.class, new Dependency$$ExternalSyntheticLambda0(lazy131));
        ArrayMap arrayMap132 = dependencyCreateDependency.mProviders;
        Lazy lazy132 = dependencyCreateDependency.mQuickSettingsController;
        Objects.requireNonNull(lazy132);
        arrayMap132.put(QuickSettingsController.class, new Dependency$$ExternalSyntheticLambda0(lazy132));
        ArrayMap arrayMap133 = dependencyCreateDependency.mProviders;
        Lazy lazy133 = dependencyCreateDependency.mConfigurationController;
        Objects.requireNonNull(lazy133);
        arrayMap133.put(ConfigurationController.class, new Dependency$$ExternalSyntheticLambda0(lazy133));
        ArrayMap arrayMap134 = dependencyCreateDependency.mProviders;
        Lazy lazy134 = dependencyCreateDependency.mFoldController;
        Objects.requireNonNull(lazy134);
        arrayMap134.put(KeyguardFoldController.class, new Dependency$$ExternalSyntheticLambda0(lazy134));
        if (LsRune.AOD_FULLSCREEN) {
            ArrayMap arrayMap135 = dependencyCreateDependency.mProviders;
            Lazy lazy135 = dependencyCreateDependency.mUnlockedScreenOffAnimationHelper;
            Objects.requireNonNull(lazy135);
            arrayMap135.put(SecUnlockedScreenOffAnimationHelper.class, new Dependency$$ExternalSyntheticLambda0(lazy135));
        }
        ArrayMap arrayMap136 = dependencyCreateDependency.mProviders;
        Lazy lazy136 = dependencyCreateDependency.mMultiSIMControllerLazy;
        Objects.requireNonNull(lazy136);
        arrayMap136.put(MultiSIMController.class, new Dependency$$ExternalSyntheticLambda0(lazy136));
        ArrayMap arrayMap137 = dependencyCreateDependency.mProviders;
        Lazy lazy137 = dependencyCreateDependency.mStatusBarIconControllerLazy;
        Objects.requireNonNull(lazy137);
        arrayMap137.put(StatusBarIconController.class, new Dependency$$ExternalSyntheticLambda0(lazy137));
        ArrayMap arrayMap138 = dependencyCreateDependency.mProviders;
        Lazy lazy138 = dependencyCreateDependency.mAiBriefManagerLazy;
        Objects.requireNonNull(lazy138);
        arrayMap138.put(AiBriefManager.class, new Dependency$$ExternalSyntheticLambda0(lazy138));
        ArrayMap arrayMap139 = dependencyCreateDependency.mProviders;
        Lazy lazy139 = dependencyCreateDependency.mSecSTQuickControlRequestReceiver;
        Objects.requireNonNull(lazy139);
        arrayMap139.put(SecSTQuickControlRequestReceiver.class, new Dependency$$ExternalSyntheticLambda0(lazy139));
        ArrayMap arrayMap140 = dependencyCreateDependency.mProviders;
        Lazy lazy140 = dependencyCreateDependency.mAppLockNotificationController;
        Objects.requireNonNull(lazy140);
        arrayMap140.put(AppLockNotificationController.class, new Dependency$$ExternalSyntheticLambda0(lazy140));
        ArrayMap arrayMap141 = dependencyCreateDependency.mProviders;
        Lazy lazy141 = dependencyCreateDependency.mKeyguardStatusBarNioLayoutRepository;
        Objects.requireNonNull(lazy141);
        arrayMap141.put(KeyguardStatusBarNioLayoutRepository.class, new Dependency$$ExternalSyntheticLambda0(lazy141));
        ArrayMap arrayMap142 = dependencyCreateDependency.mProviders;
        Lazy lazy142 = dependencyCreateDependency.mSecQsUiDisplayModeInteractor;
        Objects.requireNonNull(lazy142);
        arrayMap142.put(SecQsUiDisplayModeInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy142));
        ArrayMap arrayMap143 = dependencyCreateDependency.mProviders;
        Lazy lazy143 = dependencyCreateDependency.mSplitStateInteractor;
        Objects.requireNonNull(lazy143);
        arrayMap143.put(SplitStateInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy143));
        ArrayMap arrayMap144 = dependencyCreateDependency.mProviders;
        Lazy lazy144 = dependencyCreateDependency.mSecStatusBarWindowViewTouchedInteractor;
        Objects.requireNonNull(lazy144);
        arrayMap144.put(SecStatusBarWindowViewTouchedInteractor.class, new Dependency$$ExternalSyntheticLambda0(lazy144));
        if (BasicRune.NAVBAR_PREDICTIVE_BACK_THREE_BUTTON) {
            ArrayMap arrayMap145 = dependencyCreateDependency.mProviders;
            Lazy lazy145 = dependencyCreateDependency.mBackAnimation;
            Objects.requireNonNull(lazy145);
            arrayMap145.put(Dependency.BACK_ANIMATION, new Dependency$$ExternalSyntheticLambda0(lazy145));
        }
        ArrayMap arrayMap146 = dependencyCreateDependency.mProviders;
        Lazy lazy146 = dependencyCreateDependency.mSensorPrivacyManager;
        Objects.requireNonNull(lazy146);
        arrayMap146.put(SensorPrivacyManager.class, new Dependency$$ExternalSyntheticLambda0(lazy146));
        Dependency.setInstance(dependencyCreateDependency);
    }

    public SysUIComponent.Builder prepareSysUIComponentBuilder(SysUIComponent.Builder builder, WMComponent wMComponent) {
        return builder;
    }
}
