package androidx.compose.material3.tokens;

/* compiled from: qb/97869455 e70885ee4e20e40425471e4b47759369a50273352e1b7033cea52247075b3cbb */
/* loaded from: classes.dex */
public final class ColorLightTokens {
    public static final long Background;
    public static final long Error;
    public static final long ErrorContainer;
    public static final ColorLightTokens INSTANCE = new ColorLightTokens();
    public static final long InverseOnSurface;
    public static final long InversePrimary;
    public static final long InverseSurface;
    public static final long OnBackground;
    public static final long OnError;
    public static final long OnErrorContainer;
    public static final long OnPrimary;
    public static final long OnPrimaryContainer;
    public static final long OnSecondary;
    public static final long OnSecondaryContainer;
    public static final long OnSurface;
    public static final long OnSurfaceVariant;
    public static final long OnTertiary;
    public static final long OnTertiaryContainer;
    public static final long Outline;
    public static final long OutlineVariant;
    public static final long Primary;
    public static final long PrimaryContainer;
    public static final long Scrim;
    public static final long Secondary;
    public static final long SecondaryContainer;
    public static final long Surface;
    public static final long SurfaceBright;
    public static final long SurfaceContainer;
    public static final long SurfaceContainerHigh;
    public static final long SurfaceContainerHighest;
    public static final long SurfaceContainerLow;
    public static final long SurfaceContainerLowest;
    public static final long SurfaceDim;
    public static final long SurfaceVariant;
    public static final long Tertiary;
    public static final long TertiaryContainer;

    static {
        PaletteTokens paletteTokens = PaletteTokens.INSTANCE;
        paletteTokens.getClass();
        long j = PaletteTokens.Neutral98;
        Background = j;
        paletteTokens.getClass();
        Error = PaletteTokens.Error40;
        paletteTokens.getClass();
        ErrorContainer = PaletteTokens.Error90;
        paletteTokens.getClass();
        InverseOnSurface = PaletteTokens.Neutral95;
        paletteTokens.getClass();
        InversePrimary = PaletteTokens.Primary80;
        paletteTokens.getClass();
        InverseSurface = PaletteTokens.Neutral20;
        paletteTokens.getClass();
        long j2 = PaletteTokens.Neutral10;
        OnBackground = j2;
        paletteTokens.getClass();
        OnError = PaletteTokens.Error100;
        paletteTokens.getClass();
        OnErrorContainer = PaletteTokens.Error10;
        paletteTokens.getClass();
        OnPrimary = PaletteTokens.Primary100;
        paletteTokens.getClass();
        OnPrimaryContainer = PaletteTokens.Primary10;
        paletteTokens.getClass();
        paletteTokens.getClass();
        paletteTokens.getClass();
        OnSecondary = PaletteTokens.Secondary100;
        paletteTokens.getClass();
        OnSecondaryContainer = PaletteTokens.Secondary10;
        paletteTokens.getClass();
        paletteTokens.getClass();
        paletteTokens.getClass();
        OnSurface = j2;
        paletteTokens.getClass();
        OnSurfaceVariant = PaletteTokens.NeutralVariant30;
        paletteTokens.getClass();
        OnTertiary = PaletteTokens.Tertiary100;
        paletteTokens.getClass();
        OnTertiaryContainer = PaletteTokens.Tertiary10;
        paletteTokens.getClass();
        paletteTokens.getClass();
        paletteTokens.getClass();
        Outline = PaletteTokens.NeutralVariant50;
        paletteTokens.getClass();
        OutlineVariant = PaletteTokens.NeutralVariant80;
        paletteTokens.getClass();
        Primary = PaletteTokens.Primary40;
        paletteTokens.getClass();
        PrimaryContainer = PaletteTokens.Primary90;
        paletteTokens.getClass();
        paletteTokens.getClass();
        paletteTokens.getClass();
        Scrim = PaletteTokens.Neutral0;
        paletteTokens.getClass();
        Secondary = PaletteTokens.Secondary40;
        paletteTokens.getClass();
        SecondaryContainer = PaletteTokens.Secondary90;
        paletteTokens.getClass();
        paletteTokens.getClass();
        paletteTokens.getClass();
        Surface = j;
        paletteTokens.getClass();
        SurfaceBright = j;
        paletteTokens.getClass();
        SurfaceContainer = PaletteTokens.Neutral94;
        paletteTokens.getClass();
        SurfaceContainerHigh = PaletteTokens.Neutral92;
        paletteTokens.getClass();
        SurfaceContainerHighest = PaletteTokens.Neutral90;
        paletteTokens.getClass();
        SurfaceContainerLow = PaletteTokens.Neutral96;
        paletteTokens.getClass();
        SurfaceContainerLowest = PaletteTokens.Neutral100;
        paletteTokens.getClass();
        SurfaceDim = PaletteTokens.Neutral87;
        paletteTokens.getClass();
        SurfaceVariant = PaletteTokens.NeutralVariant90;
        paletteTokens.getClass();
        Tertiary = PaletteTokens.Tertiary40;
        paletteTokens.getClass();
        TertiaryContainer = PaletteTokens.Tertiary90;
        paletteTokens.getClass();
        paletteTokens.getClass();
    }

    private ColorLightTokens() {
    }
}
