package androidx.compose.material3.tokens;

import androidx.compose.ui.graphics.ColorKt;
import com.samsung.android.knox.custom.IKnoxCustomManager;

/* compiled from: qb/97869455 e70885ee4e20e40425471e4b47759369a50273352e1b7033cea52247075b3cbb */
/* loaded from: classes.dex */
public final class PaletteTokens {
    public static final long Error10;
    public static final long Error100;
    public static final long Error20;
    public static final long Error30;
    public static final long Error40;
    public static final long Error80;
    public static final long Error90;
    public static final PaletteTokens INSTANCE = new PaletteTokens();
    public static final long Neutral0;
    public static final long Neutral10;
    public static final long Neutral100;
    public static final long Neutral12;
    public static final long Neutral17;
    public static final long Neutral20;
    public static final long Neutral22;
    public static final long Neutral24;
    public static final long Neutral4;
    public static final long Neutral6;
    public static final long Neutral87;
    public static final long Neutral90;
    public static final long Neutral92;
    public static final long Neutral94;
    public static final long Neutral95;
    public static final long Neutral96;
    public static final long Neutral98;
    public static final long NeutralVariant30;
    public static final long NeutralVariant50;
    public static final long NeutralVariant60;
    public static final long NeutralVariant80;
    public static final long NeutralVariant90;
    public static final long Primary10;
    public static final long Primary100;
    public static final long Primary20;
    public static final long Primary30;
    public static final long Primary40;
    public static final long Primary80;
    public static final long Primary90;
    public static final long Secondary10;
    public static final long Secondary100;
    public static final long Secondary20;
    public static final long Secondary30;
    public static final long Secondary40;
    public static final long Secondary80;
    public static final long Secondary90;
    public static final long Tertiary10;
    public static final long Tertiary100;
    public static final long Tertiary20;
    public static final long Tertiary30;
    public static final long Tertiary40;
    public static final long Tertiary80;
    public static final long Tertiary90;

    static {
        ColorKt.Color$default(0, 0, 0);
        ColorKt.Color$default(0, 0, 0);
        Error10 = ColorKt.Color$default(65, 14, 11);
        Error100 = ColorKt.Color$default(255, 255, 255);
        Error20 = ColorKt.Color$default(96, 20, 16);
        Error30 = ColorKt.Color$default(140, 29, 24);
        Error40 = ColorKt.Color$default(179, 38, 30);
        ColorKt.Color$default(220, 54, 46);
        ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_getForceAutoShutDownState, 105, 98);
        ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_getAppsButtonState, 146, 142);
        Error80 = ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_getZeroPageState, 184, 181);
        Error90 = ColorKt.Color$default(249, 222, 220);
        ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_setDexForegroundModePackageList, IKnoxCustomManager.Stub.TRANSACTION_removeFavoriteApp, IKnoxCustomManager.Stub.TRANSACTION_removeFavoriteApp);
        ColorKt.Color$default(255, IKnoxCustomManager.Stub.TRANSACTION_removeDexURLShortcut, 249);
        Neutral0 = ColorKt.Color$default(0, 0, 0);
        Neutral10 = ColorKt.Color$default(29, 27, 32);
        Neutral100 = ColorKt.Color$default(255, 255, 255);
        Neutral12 = ColorKt.Color$default(33, 31, 38);
        Neutral17 = ColorKt.Color$default(43, 41, 48);
        Neutral20 = ColorKt.Color$default(50, 47, 53);
        Neutral22 = ColorKt.Color$default(54, 52, 59);
        Neutral24 = ColorKt.Color$default(59, 56, 62);
        ColorKt.Color$default(72, 70, 76);
        Neutral4 = ColorKt.Color$default(15, 13, 19);
        ColorKt.Color$default(96, 93, 100);
        ColorKt.Color$default(121, 118, 125);
        Neutral6 = ColorKt.Color$default(20, 18, 24);
        ColorKt.Color$default(147, 143, 150);
        ColorKt.Color$default(174, 169, 177);
        ColorKt.Color$default(202, 197, 205);
        Neutral87 = ColorKt.Color$default(222, IKnoxCustomManager.Stub.TRANSACTION_getAutoCallNumberAnswerMode, IKnoxCustomManager.Stub.TRANSACTION_getUsbConnectionType);
        Neutral90 = ColorKt.Color$default(230, IKnoxCustomManager.Stub.TRANSACTION_setUsbConnectionType, IKnoxCustomManager.Stub.TRANSACTION_removeWidget);
        Neutral92 = ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_getAppsButtonState, 230, IKnoxCustomManager.Stub.TRANSACTION_getFavoriteApp);
        Neutral94 = ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_setHardKeyIntentMode, IKnoxCustomManager.Stub.TRANSACTION_setFavoriteApp, IKnoxCustomManager.Stub.TRANSACTION_addDexShortcut);
        Neutral95 = ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_setHomeScreenMode, IKnoxCustomManager.Stub.TRANSACTION_getFavoriteAppsMaxCount, IKnoxCustomManager.Stub.TRANSACTION_addDexShortcut);
        Neutral96 = ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_addDexShortcut, IKnoxCustomManager.Stub.TRANSACTION_getZeroPageState, IKnoxCustomManager.Stub.TRANSACTION_addDexURLShortcutExtend);
        Neutral98 = ColorKt.Color$default(254, IKnoxCustomManager.Stub.TRANSACTION_addDexShortcut, 255);
        ColorKt.Color$default(255, IKnoxCustomManager.Stub.TRANSACTION_removeDexURLShortcut, 255);
        ColorKt.Color$default(0, 0, 0);
        ColorKt.Color$default(29, 26, 34);
        ColorKt.Color$default(255, 255, 255);
        ColorKt.Color$default(50, 47, 55);
        NeutralVariant30 = ColorKt.Color$default(73, 69, 79);
        ColorKt.Color$default(96, 93, 102);
        NeutralVariant50 = ColorKt.Color$default(121, 116, 126);
        NeutralVariant60 = ColorKt.Color$default(147, 143, 153);
        ColorKt.Color$default(174, 169, 180);
        NeutralVariant80 = ColorKt.Color$default(202, 196, 208);
        NeutralVariant90 = ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_removeShortcut, IKnoxCustomManager.Stub.TRANSACTION_setUsbConnectionType, IKnoxCustomManager.Stub.TRANSACTION_getAppsButtonState);
        ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_setHomeScreenMode, IKnoxCustomManager.Stub.TRANSACTION_removeFavoriteApp, IKnoxCustomManager.Stub.TRANSACTION_addDexURLShortcutExtend);
        ColorKt.Color$default(255, IKnoxCustomManager.Stub.TRANSACTION_removeDexURLShortcut, 254);
        ColorKt.Color$default(0, 0, 0);
        Primary10 = ColorKt.Color$default(33, 0, 93);
        Primary100 = ColorKt.Color$default(255, 255, 255);
        Primary20 = ColorKt.Color$default(56, 30, 114);
        Primary30 = ColorKt.Color$default(79, 55, 139);
        Primary40 = ColorKt.Color$default(103, 80, 164);
        ColorKt.Color$default(127, 103, 190);
        ColorKt.Color$default(154, 130, IKnoxCustomManager.Stub.TRANSACTION_getAutoCallPickupState);
        ColorKt.Color$default(182, 157, IKnoxCustomManager.Stub.TRANSACTION_removeDexShortcut);
        Primary80 = ColorKt.Color$default(208, 188, 255);
        Primary90 = ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_deleteHomeScreenPage, 221, 255);
        ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_getHomeScreenMode, IKnoxCustomManager.Stub.TRANSACTION_setFavoriteApp, 255);
        ColorKt.Color$default(255, IKnoxCustomManager.Stub.TRANSACTION_removeDexURLShortcut, 254);
        ColorKt.Color$default(0, 0, 0);
        Secondary10 = ColorKt.Color$default(29, 25, 43);
        Secondary100 = ColorKt.Color$default(255, 255, 255);
        Secondary20 = ColorKt.Color$default(51, 45, 65);
        Secondary30 = ColorKt.Color$default(74, 68, 88);
        Secondary40 = ColorKt.Color$default(98, 91, 113);
        ColorKt.Color$default(122, 114, 137);
        ColorKt.Color$default(149, 141, 165);
        ColorKt.Color$default(176, 167, 192);
        Secondary80 = ColorKt.Color$default(204, 194, 220);
        Secondary90 = ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_addWidget, 222, IKnoxCustomManager.Stub.TRANSACTION_removeDexShortcut);
        ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_getHomeScreenMode, IKnoxCustomManager.Stub.TRANSACTION_setFavoriteApp, 255);
        ColorKt.Color$default(255, IKnoxCustomManager.Stub.TRANSACTION_removeDexURLShortcut, 254);
        ColorKt.Color$default(0, 0, 0);
        Tertiary10 = ColorKt.Color$default(49, 17, 29);
        Tertiary100 = ColorKt.Color$default(255, 255, 255);
        Tertiary20 = ColorKt.Color$default(73, 37, 50);
        Tertiary30 = ColorKt.Color$default(99, 59, 72);
        Tertiary40 = ColorKt.Color$default(125, 82, 96);
        ColorKt.Color$default(152, 105, 119);
        ColorKt.Color$default(181, 131, 146);
        ColorKt.Color$default(210, 157, 172);
        Tertiary80 = ColorKt.Color$default(IKnoxCustomManager.Stub.TRANSACTION_getFavoriteAppsMaxCount, 184, 200);
        Tertiary90 = ColorKt.Color$default(255, IKnoxCustomManager.Stub.TRANSACTION_getAutoCallNumberAnswerMode, IKnoxCustomManager.Stub.TRANSACTION_getForceAutoShutDownState);
        ColorKt.Color$default(255, IKnoxCustomManager.Stub.TRANSACTION_getAppsButtonState, IKnoxCustomManager.Stub.TRANSACTION_setZeroPageState);
        ColorKt.Color$default(255, IKnoxCustomManager.Stub.TRANSACTION_removeDexURLShortcut, IKnoxCustomManager.Stub.TRANSACTION_addDexURLShortcutExtend);
        ColorKt.Color$default(255, 255, 255);
    }

    private PaletteTokens() {
    }
}
