package androidx.compose.material3.tokens;

import androidx.compose.ui.text.font.FontWeight;
import androidx.compose.ui.text.font.GenericFontFamily;
import androidx.compose.ui.unit.TextUnit;
import androidx.compose.ui.unit.TextUnitKt;

/* compiled from: qb/97869455 e70885ee4e20e40425471e4b47759369a50273352e1b7033cea52247075b3cbb */
/* loaded from: classes.dex */
public final class TypeScaleTokens {
    public static final GenericFontFamily BodyLargeEmphasizedFont;
    public static final long BodyLargeEmphasizedLineHeight;
    public static final long BodyLargeEmphasizedSize;
    public static final long BodyLargeEmphasizedTracking;
    public static final FontWeight BodyLargeEmphasizedWeight;
    public static final GenericFontFamily BodyLargeFont;
    public static final long BodyLargeLineHeight;
    public static final long BodyLargeSize;
    public static final long BodyLargeTracking;
    public static final FontWeight BodyLargeWeight;
    public static final GenericFontFamily BodyMediumEmphasizedFont;
    public static final long BodyMediumEmphasizedLineHeight;
    public static final long BodyMediumEmphasizedSize;
    public static final long BodyMediumEmphasizedTracking;
    public static final FontWeight BodyMediumEmphasizedWeight;
    public static final GenericFontFamily BodyMediumFont;
    public static final long BodyMediumLineHeight;
    public static final long BodyMediumSize;
    public static final long BodyMediumTracking;
    public static final FontWeight BodyMediumWeight;
    public static final GenericFontFamily BodySmallEmphasizedFont;
    public static final long BodySmallEmphasizedLineHeight;
    public static final long BodySmallEmphasizedSize;
    public static final long BodySmallEmphasizedTracking;
    public static final FontWeight BodySmallEmphasizedWeight;
    public static final GenericFontFamily BodySmallFont;
    public static final long BodySmallLineHeight;
    public static final long BodySmallSize;
    public static final long BodySmallTracking;
    public static final FontWeight BodySmallWeight;
    public static final GenericFontFamily DisplayLargeEmphasizedFont;
    public static final long DisplayLargeEmphasizedLineHeight;
    public static final long DisplayLargeEmphasizedSize;
    public static final long DisplayLargeEmphasizedTracking;
    public static final FontWeight DisplayLargeEmphasizedWeight;
    public static final GenericFontFamily DisplayLargeFont;
    public static final long DisplayLargeLineHeight;
    public static final long DisplayLargeSize;
    public static final long DisplayLargeTracking;
    public static final FontWeight DisplayLargeWeight;
    public static final GenericFontFamily DisplayMediumEmphasizedFont;
    public static final long DisplayMediumEmphasizedLineHeight;
    public static final long DisplayMediumEmphasizedSize;
    public static final long DisplayMediumEmphasizedTracking;
    public static final FontWeight DisplayMediumEmphasizedWeight;
    public static final GenericFontFamily DisplayMediumFont;
    public static final long DisplayMediumLineHeight;
    public static final long DisplayMediumSize;
    public static final long DisplayMediumTracking;
    public static final FontWeight DisplayMediumWeight;
    public static final GenericFontFamily DisplaySmallEmphasizedFont;
    public static final long DisplaySmallEmphasizedLineHeight;
    public static final long DisplaySmallEmphasizedSize;
    public static final long DisplaySmallEmphasizedTracking;
    public static final FontWeight DisplaySmallEmphasizedWeight;
    public static final GenericFontFamily DisplaySmallFont;
    public static final long DisplaySmallLineHeight;
    public static final long DisplaySmallSize;
    public static final long DisplaySmallTracking;
    public static final FontWeight DisplaySmallWeight;
    public static final GenericFontFamily HeadlineLargeEmphasizedFont;
    public static final long HeadlineLargeEmphasizedLineHeight;
    public static final long HeadlineLargeEmphasizedSize;
    public static final long HeadlineLargeEmphasizedTracking;
    public static final FontWeight HeadlineLargeEmphasizedWeight;
    public static final GenericFontFamily HeadlineLargeFont;
    public static final long HeadlineLargeLineHeight;
    public static final long HeadlineLargeSize;
    public static final long HeadlineLargeTracking;
    public static final FontWeight HeadlineLargeWeight;
    public static final GenericFontFamily HeadlineMediumEmphasizedFont;
    public static final long HeadlineMediumEmphasizedLineHeight;
    public static final long HeadlineMediumEmphasizedSize;
    public static final long HeadlineMediumEmphasizedTracking;
    public static final FontWeight HeadlineMediumEmphasizedWeight;
    public static final GenericFontFamily HeadlineMediumFont;
    public static final long HeadlineMediumLineHeight;
    public static final long HeadlineMediumSize;
    public static final long HeadlineMediumTracking;
    public static final FontWeight HeadlineMediumWeight;
    public static final GenericFontFamily HeadlineSmallEmphasizedFont;
    public static final long HeadlineSmallEmphasizedLineHeight;
    public static final long HeadlineSmallEmphasizedSize;
    public static final long HeadlineSmallEmphasizedTracking;
    public static final FontWeight HeadlineSmallEmphasizedWeight;
    public static final GenericFontFamily HeadlineSmallFont;
    public static final long HeadlineSmallLineHeight;
    public static final long HeadlineSmallSize;
    public static final long HeadlineSmallTracking;
    public static final FontWeight HeadlineSmallWeight;
    public static final TypeScaleTokens INSTANCE = new TypeScaleTokens();
    public static final GenericFontFamily LabelLargeEmphasizedFont;
    public static final long LabelLargeEmphasizedLineHeight;
    public static final long LabelLargeEmphasizedSize;
    public static final long LabelLargeEmphasizedTracking;
    public static final FontWeight LabelLargeEmphasizedWeight;
    public static final GenericFontFamily LabelLargeFont;
    public static final long LabelLargeLineHeight;
    public static final long LabelLargeSize;
    public static final long LabelLargeTracking;
    public static final FontWeight LabelLargeWeight;
    public static final GenericFontFamily LabelMediumEmphasizedFont;
    public static final long LabelMediumEmphasizedLineHeight;
    public static final long LabelMediumEmphasizedSize;
    public static final long LabelMediumEmphasizedTracking;
    public static final FontWeight LabelMediumEmphasizedWeight;
    public static final GenericFontFamily LabelMediumFont;
    public static final long LabelMediumLineHeight;
    public static final long LabelMediumSize;
    public static final long LabelMediumTracking;
    public static final FontWeight LabelMediumWeight;
    public static final GenericFontFamily LabelSmallEmphasizedFont;
    public static final long LabelSmallEmphasizedLineHeight;
    public static final long LabelSmallEmphasizedSize;
    public static final long LabelSmallEmphasizedTracking;
    public static final FontWeight LabelSmallEmphasizedWeight;
    public static final GenericFontFamily LabelSmallFont;
    public static final long LabelSmallLineHeight;
    public static final long LabelSmallSize;
    public static final long LabelSmallTracking;
    public static final FontWeight LabelSmallWeight;
    public static final GenericFontFamily TitleLargeEmphasizedFont;
    public static final long TitleLargeEmphasizedLineHeight;
    public static final long TitleLargeEmphasizedSize;
    public static final long TitleLargeEmphasizedTracking;
    public static final FontWeight TitleLargeEmphasizedWeight;
    public static final GenericFontFamily TitleLargeFont;
    public static final long TitleLargeLineHeight;
    public static final long TitleLargeSize;
    public static final long TitleLargeTracking;
    public static final FontWeight TitleLargeWeight;
    public static final GenericFontFamily TitleMediumEmphasizedFont;
    public static final long TitleMediumEmphasizedLineHeight;
    public static final long TitleMediumEmphasizedSize;
    public static final long TitleMediumEmphasizedTracking;
    public static final FontWeight TitleMediumEmphasizedWeight;
    public static final GenericFontFamily TitleMediumFont;
    public static final long TitleMediumLineHeight;
    public static final long TitleMediumSize;
    public static final long TitleMediumTracking;
    public static final FontWeight TitleMediumWeight;
    public static final GenericFontFamily TitleSmallEmphasizedFont;
    public static final long TitleSmallEmphasizedLineHeight;
    public static final long TitleSmallEmphasizedSize;
    public static final long TitleSmallEmphasizedTracking;
    public static final FontWeight TitleSmallEmphasizedWeight;
    public static final GenericFontFamily TitleSmallFont;
    public static final long TitleSmallLineHeight;
    public static final long TitleSmallSize;
    public static final long TitleSmallTracking;
    public static final FontWeight TitleSmallWeight;

    static {
        TypefaceTokens typefaceTokens = TypefaceTokens.INSTANCE;
        typefaceTokens.getClass();
        GenericFontFamily genericFontFamily = TypefaceTokens.Plain;
        BodyLargeFont = genericFontFamily;
        BodyLargeLineHeight = TextUnitKt.getSp(24.0d);
        BodyLargeSize = TextUnitKt.getSp(16);
        BodyLargeTracking = TextUnitKt.getSp(0.5d);
        typefaceTokens.getClass();
        FontWeight fontWeight = TypefaceTokens.WeightRegular;
        BodyLargeWeight = fontWeight;
        typefaceTokens.getClass();
        BodyMediumFont = genericFontFamily;
        BodyMediumLineHeight = TextUnitKt.getSp(20.0d);
        BodyMediumSize = TextUnitKt.getSp(14);
        BodyMediumTracking = TextUnitKt.getSp(0.2d);
        typefaceTokens.getClass();
        BodyMediumWeight = fontWeight;
        typefaceTokens.getClass();
        BodySmallFont = genericFontFamily;
        BodySmallLineHeight = TextUnitKt.getSp(16.0d);
        BodySmallSize = TextUnitKt.getSp(12);
        BodySmallTracking = TextUnitKt.getSp(0.4d);
        typefaceTokens.getClass();
        BodySmallWeight = fontWeight;
        typefaceTokens.getClass();
        GenericFontFamily genericFontFamily2 = TypefaceTokens.Brand;
        DisplayLargeFont = genericFontFamily2;
        DisplayLargeLineHeight = TextUnitKt.getSp(64.0d);
        DisplayLargeSize = TextUnitKt.getSp(57);
        long sp = TextUnitKt.getSp(0.2d);
        TextUnitKt.m871checkArithmeticR2X_6o(sp);
        DisplayLargeTracking = TextUnitKt.pack(-TextUnit.m868getValueimpl(sp), sp & 1095216660480L);
        typefaceTokens.getClass();
        DisplayLargeWeight = fontWeight;
        typefaceTokens.getClass();
        DisplayMediumFont = genericFontFamily2;
        DisplayMediumLineHeight = TextUnitKt.getSp(52.0d);
        DisplayMediumSize = TextUnitKt.getSp(45);
        DisplayMediumTracking = TextUnitKt.getSp(0.0d);
        typefaceTokens.getClass();
        DisplayMediumWeight = fontWeight;
        typefaceTokens.getClass();
        DisplaySmallFont = genericFontFamily2;
        DisplaySmallLineHeight = TextUnitKt.getSp(44.0d);
        DisplaySmallSize = TextUnitKt.getSp(36);
        DisplaySmallTracking = TextUnitKt.getSp(0.0d);
        typefaceTokens.getClass();
        DisplaySmallWeight = fontWeight;
        typefaceTokens.getClass();
        HeadlineLargeFont = genericFontFamily2;
        HeadlineLargeLineHeight = TextUnitKt.getSp(40.0d);
        HeadlineLargeSize = TextUnitKt.getSp(32);
        HeadlineLargeTracking = TextUnitKt.getSp(0.0d);
        typefaceTokens.getClass();
        HeadlineLargeWeight = fontWeight;
        typefaceTokens.getClass();
        HeadlineMediumFont = genericFontFamily2;
        HeadlineMediumLineHeight = TextUnitKt.getSp(36.0d);
        HeadlineMediumSize = TextUnitKt.getSp(28);
        HeadlineMediumTracking = TextUnitKt.getSp(0.0d);
        typefaceTokens.getClass();
        HeadlineMediumWeight = fontWeight;
        typefaceTokens.getClass();
        HeadlineSmallFont = genericFontFamily2;
        HeadlineSmallLineHeight = TextUnitKt.getSp(32.0d);
        HeadlineSmallSize = TextUnitKt.getSp(24);
        HeadlineSmallTracking = TextUnitKt.getSp(0.0d);
        typefaceTokens.getClass();
        HeadlineSmallWeight = fontWeight;
        typefaceTokens.getClass();
        LabelLargeFont = genericFontFamily;
        LabelLargeLineHeight = TextUnitKt.getSp(20.0d);
        LabelLargeSize = TextUnitKt.getSp(14);
        LabelLargeTracking = TextUnitKt.getSp(0.1d);
        typefaceTokens.getClass();
        FontWeight fontWeight2 = TypefaceTokens.WeightMedium;
        LabelLargeWeight = fontWeight2;
        TypefaceTokens typefaceTokens2 = TypefaceTokens.INSTANCE;
        typefaceTokens2.getClass();
        GenericFontFamily genericFontFamily3 = TypefaceTokens.Plain;
        LabelMediumFont = genericFontFamily3;
        LabelMediumLineHeight = TextUnitKt.getSp(16.0d);
        LabelMediumSize = TextUnitKt.getSp(12);
        LabelMediumTracking = TextUnitKt.getSp(0.5d);
        typefaceTokens2.getClass();
        LabelMediumWeight = fontWeight2;
        typefaceTokens2.getClass();
        LabelSmallFont = genericFontFamily3;
        LabelSmallLineHeight = TextUnitKt.getSp(16.0d);
        LabelSmallSize = TextUnitKt.getSp(11);
        LabelSmallTracking = TextUnitKt.getSp(0.5d);
        typefaceTokens2.getClass();
        LabelSmallWeight = fontWeight2;
        typefaceTokens2.getClass();
        TitleLargeFont = genericFontFamily2;
        TitleLargeLineHeight = TextUnitKt.getSp(28.0d);
        TitleLargeSize = TextUnitKt.getSp(22);
        TitleLargeTracking = TextUnitKt.getSp(0.0d);
        typefaceTokens2.getClass();
        TitleLargeWeight = TypefaceTokens.WeightRegular;
        typefaceTokens2.getClass();
        TitleMediumFont = genericFontFamily3;
        TitleMediumLineHeight = TextUnitKt.getSp(24.0d);
        TitleMediumSize = TextUnitKt.getSp(16);
        TitleMediumTracking = TextUnitKt.getSp(0.2d);
        typefaceTokens2.getClass();
        TitleMediumWeight = fontWeight2;
        typefaceTokens2.getClass();
        TitleSmallFont = genericFontFamily3;
        TitleSmallLineHeight = TextUnitKt.getSp(20.0d);
        TitleSmallSize = TextUnitKt.getSp(14);
        TitleSmallTracking = TextUnitKt.getSp(0.1d);
        typefaceTokens2.getClass();
        TitleSmallWeight = fontWeight2;
        typefaceTokens2.getClass();
        BodyLargeEmphasizedFont = genericFontFamily3;
        BodyLargeEmphasizedLineHeight = TextUnitKt.getSp(24.0d);
        BodyLargeEmphasizedSize = TextUnitKt.getSp(16);
        BodyLargeEmphasizedTracking = TextUnitKt.getSp(0.15d);
        typefaceTokens2.getClass();
        BodyLargeEmphasizedWeight = fontWeight2;
        typefaceTokens2.getClass();
        BodyMediumEmphasizedFont = genericFontFamily3;
        BodyMediumEmphasizedLineHeight = TextUnitKt.getSp(20.0d);
        BodyMediumEmphasizedSize = TextUnitKt.getSp(14);
        BodyMediumEmphasizedTracking = TextUnitKt.getSp(0.25d);
        typefaceTokens2.getClass();
        BodyMediumEmphasizedWeight = fontWeight2;
        typefaceTokens2.getClass();
        BodySmallEmphasizedFont = genericFontFamily3;
        BodySmallEmphasizedLineHeight = TextUnitKt.getSp(16.0d);
        BodySmallEmphasizedSize = TextUnitKt.getSp(12);
        BodySmallEmphasizedTracking = TextUnitKt.getSp(0.4d);
        typefaceTokens2.getClass();
        BodySmallEmphasizedWeight = fontWeight2;
        typefaceTokens2.getClass();
        GenericFontFamily genericFontFamily4 = TypefaceTokens.Brand;
        DisplayLargeEmphasizedFont = genericFontFamily4;
        DisplayLargeEmphasizedLineHeight = TextUnitKt.getSp(64.0d);
        DisplayLargeEmphasizedSize = TextUnitKt.getSp(57);
        DisplayLargeEmphasizedTracking = TextUnitKt.getSp(0);
        typefaceTokens2.getClass();
        DisplayLargeEmphasizedWeight = fontWeight2;
        typefaceTokens2.getClass();
        DisplayMediumEmphasizedFont = genericFontFamily4;
        DisplayMediumEmphasizedLineHeight = TextUnitKt.getSp(52.0d);
        DisplayMediumEmphasizedSize = TextUnitKt.getSp(45);
        DisplayMediumEmphasizedTracking = TextUnitKt.getSp(0);
        typefaceTokens2.getClass();
        FontWeight fontWeight3 = TypefaceTokens.WeightMedium;
        DisplayMediumEmphasizedWeight = fontWeight3;
        TypefaceTokens typefaceTokens3 = TypefaceTokens.INSTANCE;
        typefaceTokens3.getClass();
        DisplaySmallEmphasizedFont = genericFontFamily4;
        DisplaySmallEmphasizedLineHeight = TextUnitKt.getSp(44.0d);
        DisplaySmallEmphasizedSize = TextUnitKt.getSp(36);
        DisplaySmallEmphasizedTracking = TextUnitKt.getSp(0);
        typefaceTokens3.getClass();
        DisplaySmallEmphasizedWeight = fontWeight3;
        typefaceTokens3.getClass();
        HeadlineLargeEmphasizedFont = genericFontFamily4;
        HeadlineLargeEmphasizedLineHeight = TextUnitKt.getSp(40.0d);
        HeadlineLargeEmphasizedSize = TextUnitKt.getSp(32);
        HeadlineLargeEmphasizedTracking = TextUnitKt.getSp(0);
        typefaceTokens3.getClass();
        HeadlineLargeEmphasizedWeight = fontWeight3;
        typefaceTokens3.getClass();
        HeadlineMediumEmphasizedFont = genericFontFamily4;
        HeadlineMediumEmphasizedLineHeight = TextUnitKt.getSp(36.0d);
        HeadlineMediumEmphasizedSize = TextUnitKt.getSp(28);
        HeadlineMediumEmphasizedTracking = TextUnitKt.getSp(0);
        typefaceTokens3.getClass();
        HeadlineMediumEmphasizedWeight = fontWeight3;
        typefaceTokens3.getClass();
        HeadlineSmallEmphasizedFont = genericFontFamily4;
        HeadlineSmallEmphasizedLineHeight = TextUnitKt.getSp(32.0d);
        HeadlineSmallEmphasizedSize = TextUnitKt.getSp(24);
        HeadlineSmallEmphasizedTracking = TextUnitKt.getSp(0);
        typefaceTokens3.getClass();
        HeadlineSmallEmphasizedWeight = fontWeight3;
        typefaceTokens3.getClass();
        GenericFontFamily genericFontFamily5 = TypefaceTokens.Plain;
        LabelLargeEmphasizedFont = genericFontFamily5;
        LabelLargeEmphasizedLineHeight = TextUnitKt.getSp(20.0d);
        LabelLargeEmphasizedSize = TextUnitKt.getSp(14);
        LabelLargeEmphasizedTracking = TextUnitKt.getSp(0.1d);
        typefaceTokens3.getClass();
        FontWeight fontWeight4 = TypefaceTokens.WeightBold;
        LabelLargeEmphasizedWeight = fontWeight4;
        typefaceTokens3.getClass();
        LabelMediumEmphasizedFont = genericFontFamily5;
        LabelMediumEmphasizedLineHeight = TextUnitKt.getSp(16.0d);
        LabelMediumEmphasizedSize = TextUnitKt.getSp(12);
        LabelMediumEmphasizedTracking = TextUnitKt.getSp(0.5d);
        typefaceTokens3.getClass();
        LabelMediumEmphasizedWeight = fontWeight4;
        typefaceTokens3.getClass();
        LabelSmallEmphasizedFont = genericFontFamily5;
        LabelSmallEmphasizedLineHeight = TextUnitKt.getSp(16.0d);
        LabelSmallEmphasizedSize = TextUnitKt.getSp(11);
        LabelSmallEmphasizedTracking = TextUnitKt.getSp(0.5d);
        typefaceTokens3.getClass();
        LabelSmallEmphasizedWeight = fontWeight4;
        typefaceTokens3.getClass();
        TitleLargeEmphasizedFont = genericFontFamily4;
        TitleLargeEmphasizedLineHeight = TextUnitKt.getSp(28.0d);
        TitleLargeEmphasizedSize = TextUnitKt.getSp(22);
        TitleLargeEmphasizedTracking = TextUnitKt.getSp(0);
        typefaceTokens3.getClass();
        TitleLargeEmphasizedWeight = fontWeight3;
        typefaceTokens3.getClass();
        TitleMediumEmphasizedFont = genericFontFamily5;
        TitleMediumEmphasizedLineHeight = TextUnitKt.getSp(24.0d);
        TitleMediumEmphasizedSize = TextUnitKt.getSp(16);
        TitleMediumEmphasizedTracking = TextUnitKt.getSp(0.15d);
        typefaceTokens3.getClass();
        TitleMediumEmphasizedWeight = fontWeight4;
        typefaceTokens3.getClass();
        TitleSmallEmphasizedFont = genericFontFamily5;
        TitleSmallEmphasizedLineHeight = TextUnitKt.getSp(20.0d);
        TitleSmallEmphasizedSize = TextUnitKt.getSp(14);
        TitleSmallEmphasizedTracking = TextUnitKt.getSp(0.1d);
        typefaceTokens3.getClass();
        TitleSmallEmphasizedWeight = fontWeight4;
    }

    private TypeScaleTokens() {
    }
}
